### PR TITLE
[draw] Implement hb_*_font_draw_glyph for platform libraries

### PR DESCRIPTION
**Pull request by ebraminio**
Maybe better to do this transparently without any extra API, maybe not.

Done for freetype / directwrite / gdi / coretext

### CODE REVIEW

**Comment by behdad** [comment]
Okay trouble for you.  Looks to me like draw should be part of font_funcs :D.

**Comment by ebraminio** [comment]
> Okay trouble for you. Looks to me like draw should be part of font_funcs :D.

#2185

**Comment by ebraminio** [comment]
> Okay trouble for you. Looks to me like draw should be part of font_funcs :D.

Btw it is a very good idea as DirectWrite can 'draw' a hb_buffer_t like object but its callback has SetFillMode (D2D1_FILL_MODE_ALTERNATE | D2D1_FILL_MODE_WINDING) to circumstance glyph overlaps apparently.

**Comment by ebraminio** [comment]
in favor of #2185

**Pull request closed without merging**
