### PR TITLE
[instancer] support *=drop, which would pin all axis to default location

### PR DESCRIPTION
**Pull request by qxliu76**
this is for #3961

### CODE REVIEW

**Review by garretrieger — APPROVED** [review]

**Comment by behdad** [comment]
Please update `harfbuzz-docs.txt`.

The function `hb_subset_input_pin_all_axis_to_default` is a bit too specific.  Also, it probably say `axes` instead of `axis`.

Does pinning all to default, then calling some `hb_subset_input_pin_axis_to_location()` work?

**Comment by qxliu76** [comment]
> Does pinning all to default, then calling some `hb_subset_input_pin_axis_to_location()` work?
Yes that works, because each time we just update the value in the axis_tag->Triple map

**Comment by qxliu76** [comment]
> Please update `harfbuzz-docs.txt`.

Done. There's still a test failure, do you know what it's complaining about?

`Running suite(s): gtk-doc-harfbuzz`
`harfbuzz-unused.txt:1:E: 1 unused documentation entries`

**Comment by qxliu76** [comment]
> > `Running suite(s): gtk-doc-harfbuzz`
> > `harfbuzz-unused.txt:1:E: 1 unused documentation entries`
> 
> Sorry, remove the `harfbuzz-docs.xml` change. Add new API to `harfbuzz-sections.txt`.

Thanks! That error is gone and the newest error is this:
`./harfbuzz-docs.xml:1:E: doesn't appear to include "xml/api-index-REPLACEME.xml"`
Seems we still need the `harfbuzz-docs.xml` change. :) I'll add it back.

**Comment by behdad** [comment]
No no.

Change the line: `Since: REPLACEME` to `XSince: REPLACEME`.

**Comment by qxliu76** [comment]
> No no.
> 
> Change the line: `Since: REPLACEME` to `XSince: REPLACEME`.

Done. The test is fine now. Thank you!

**Pull request merged**
