### PR TITLE
[subset] avoid calling clear on null pool set.

### PR DESCRIPTION
**Pull request by garretrieger**
Fixes: https://oss-fuzz.com/testcase-detail/5617065093365760

### CODE REVIEW

**Comment by behdad** [comment]
This is becoming magic :(.

Doesn't it return nullptr on failed insert? Where does the null set come in?

**Comment by behdad** [comment]
Also, please include the oss-fuzz URL in the commit logs. Thanks. Bonus for adding the fuzzed tests.

**Comment by behdad** [comment]
> > This is becoming magic :(.
> > Doesn't it return nullptr on failed insert? Where does the null set come in?
> 
> Agreed, this is a case where a unique_ptr like construct would make this much simpler. The null set can be created as a result of memory allocation failing for the hb_set_create () call.

Right. As discussed recently, `hb_set_create()` and the null stuff is considered C API. Ideally you would just insert `set_t` directly in there and let move semantics work for you. We're not that far from that. I expect a few more weeks and we'll be there.

**Comment by garretrieger** [comment]
Ah yes, using move() would be even better. Shall I merge this for now and we'll come back an clean up once we have that in place?

**Comment by behdad** [comment]
Actually I think all you need to do is to use the C API `hb_set_clear()`, which does the null-object check for you.

**Comment by garretrieger** [comment]
> Actually I think all you need to do is to use the C API `hb_set_clear()`, which does the null-object check for you.

Done.

**Pull request merged**
