### PR TITLE
Replace "assert (0)"s with "abort ()" to make compilers happy

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by behdad** [comment]
assert is compiled away in production builds.  abort isn't I believe.

**Comment by ebraminio** [comment]
> assert is compiled away in production builds. abort isn't I believe.

Hmm, but do we like to expose such inconsistent state to our clients rather than finding them, weird to have such distinction in not multiple leveled assertion (DEBUG_ASSERT, RELEASE_ASSERT, etc) project.

**Comment by behdad** [comment]
> but do we like to expose such inconsistent state to our clients rather than finding them

you're assuming there *is* a bug.  there's no reason to believe that. :)

**Comment by ebraminio** [comment]
OK then

**Pull request closed without merging**
