### PR TITLE
Include hb-version.h in git

### PR DESCRIPTION
**Pull request by behdad**
Probably needs Cmake updates.

https://github.com/harfbuzz/harfbuzz/issues/817

### CODE REVIEW

**Comment by behdad** [comment]
@ebraminio Can I get some help from you here as well? I'm moving to keeping hb-version.h in git as well. Don't know what's best to do in Cmake. You can remove regenerating it maybe. I don't understand the bot failures enough to fix. Thanks.

**Comment by ebraminio** [comment]
This seems to be OK as well and needs #821. Of course we better to remove hb-version/ragel generation from CMake sometime but for now failings are not related to that.

**Comment by behdad** [comment]
Ah ok. I'm hopeful that one will go through this time.

**Comment by behdad** [comment]
@ebraminio HELP :D

**Pull request merged**
