### PR TITLE
[ci] Add Oracle Developer Studio (former Sun Studio) based compiler

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
@behdad, this just needs a permanent link for ODS before merge.

**Comment by ebraminio** [comment]
And $ODSUSER and $ODSPASS should be set on circleci https://circleci.com/gh/behdad/harfbuzz/edit#env-vars

**Comment by ebraminio** [comment]
So this is waiting for your help, @behdad, downloading the url on your host, host it under a password, set the password on CI https://circleci.com/gh/harfbuzz/harfbuzz/edit#env-vars and letting me know :)

**Comment by behdad** [comment]
Done.

**Comment by ebraminio** [comment]
Thanks!

**Pull request merged**
