### PR TITLE
[indic] Order left-matras inside-out

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3863

How's this for implementation? One test fails currently.  I haven't studied it but is probably expected.
```
hb-shape /home/behdad/harfbuzz/test/shape/data/in-house/fonts/3493e92eaded2661cadde752a39f9d58b11f0326.ttf --unicodes U+0BA4,U+0BC6,U+1133C,U+0BAA,U+1133C,U+0BC6,U+1133C
Actual:   [u1133C=0+0|u0BC6=0+2093|u0BA4=0+1863|u1133C=3+0|u0BC6=3+2093|u0BAA=3+1706|u1133C=3+0]
Expected: [u0BC6=0+2093|u1133C=0+0|u0BA4=0+1863|u0BC6=3+2093|u1133C=3+0|u0BAA=3+1706|u1133C=3+0]
```

### CODE REVIEW

**Review by dscorbett — CHANGES_REQUESTED** [review]
When a reordering spacing mark has a non-spacing mark applied to it, like a nukta or a variation selector, the non-spacing mark should follow the spacing mark, even after the call to `reverse_range`. That is why the test is failing.

Once the code is fixed, it should be copied to the Myanmar shaper. I can’t find any evidence that the current behavior was once tested and found intentional.

Because the Khmer shaper doesn’t support multiple pre-base vowels, it doesn’t need changing, but I think it would be good to add a comment to hb-ot-shaper-khmer-machine.rl explaining that if that restriction is ever lifted, the shaper will need updating.

**Comment by behdad** [comment]
> When a reordering spacing mark has a non-spacing mark applied to it, like a nukta or a variation selector, the non-spacing mark should follow the spacing mark, even after the call to `reverse_range`. That is why the test is failing.

Fixed.



> Once the code is fixed, it should be copied to the Myanmar shaper. I can’t find any evidence that the current behavior was once tested and found intentional.

Working on that.

**Comment by behdad** [comment]
Added Myanmar. I tested the Devanagari case, but not Myanmar. Will add Deva test.

What's a good sequence to test Myanmar?

**Comment by behdad** [comment]
> Because the Khmer shaper doesn’t support multiple pre-base vowels, it doesn’t need changing, but I think it would be good to add a comment to hb-ot-shaper-khmer-machine.rl explaining that if that restriction is ever lifted, the shaper will need updating.

Khmer encoding is visual, so there's no sorting and the issue doesn't occur.

**Comment by behdad** [comment]
PTAL.

**Review by dscorbett — APPROVED** [review]
This looks good now.

Khmer vowels are encoded in phonetic order, not visual order, so they are reordered, but it doesn’t really matter for this issue anyway.

**Pull request merged**
