### PR TITLE
[subset] add share option to pop_pack()

### PR DESCRIPTION
**Pull request by blueshade7**
a solution of #2164 [subset] pop_pack() option to not hash & share table

### CODE REVIEW

**Comment by blueshade7** [comment]
I am not sure why we need to call `pop_pack()` in `end_serialize()` here, but if it is to stay, I suppose it needs share = `false`.
https://github.com/harfbuzz/harfbuzz/blob/a94d1af193ac1601a1725266dbb0dd51195af98b/src/hb-serialize.hh#L169

**Comment by behdad** [comment]
> I am not sure why we need to call `pop_pack()` in `end_serialize()` here, but if it is to stay, I suppose it needs share = `false`.
> https://github.com/harfbuzz/harfbuzz/blob/a94d1af193ac1601a1725266dbb0dd51195af98b/src/hb-serialize.hh#L169

It doesn't *need* share =  false, but can use it, yes.

We need that there such that users of serialize that don't participate in push/pop at all still work.

LGTM.  Thanks.

**Comment by blueshade7** [comment]
>We need that there such that users of serialize that don't participate in push/pop at all still work.

But this condition above the line appears to imply this pop_pack() is executed when push/pop_pack are used.
https://github.com/harfbuzz/harfbuzz/blob/a94d1af193ac1601a1725266dbb0dd51195af98b/src/hb-serialize.hh#L164-L167
copy_bytes() appears to take care of data never pushed/popped. This brought me to the question: why do we need pop_pack() there?

**Comment by blueshade7** [comment]
Let me merge this PR and open an issue for above discussion.

**Pull request merged**
