### PR TITLE
Aggregate and merge number parsing codes

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by behdad** [comment]
I'm slightly confused as to why there's no `uint` version in the internal API.  But whatever works I'm fine.  Feel free to merge.

**Comment by ebraminio** [comment]
> I'm slightly confused as to why there's no uint version in the internal API. But whatever works I'm fine. Feel free to merge.

Added now, wasn't there because parse_uint and parse_uint32 of in hb-common.cc were using `strtol` so -1 could mean a big number, as the current comments indicates but the one in hb_codepoint_parse needed that have added it, have used template and lambda to remove duplicated parsing code also, will merge once wrote test for these and am sure there is no behavior change if you don't object. Thanks for the support :)

**Comment by behdad** [comment]
I like the end result.  Thank you. :)

**Comment by behdad** [comment]
`hb_codepoint_parse` can move into `hb-number.hh` maybe as well.  No strong opinion.

**Comment by behdad** [comment]
Don't worry.  Leave as is.  Thanks for working on this.

**Comment by behdad** [comment]
Don't worry.  Leave as is.  Thanks for working on this.

**Comment by ebraminio** [comment]
> I like the end result. Thank you. :)

Thanks for expressing the feeling :)

**Pull request merged**
