### PR TITLE
[WIP][Zapf] Implement parsing

### LINKED ISSUE #919: Implement Zapf table parsing
Now that we have an issue for every other AAT table, lets have for this one also,

> The 'Zapf' table—named with permission after legendary type designer Hermann Zapf—contains information about the individual glyphs in the font.  Conceptually, this information consists of:
>
> A text string which the glyph represents
> A set of identifiers
> A set of font features
> A set of glyph collections

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6Zapf.html

### PR DESCRIPTION
**Pull request by ebraminio**
Closes #919

Its sanitization is not tested however.

### CODE REVIEW

**Comment by behdad** [comment]
Do you honestly see this used for anything?

**Comment by ebraminio** [comment]
> Do you honestly see this used for anything?

Its glyph collections can be useful but we don't have its OT's equivalent of it also

**Comment by behdad** [comment]
What's the OT equivalent?

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/issues/673#issuecomment-437616964

**Comment by ebraminio** [comment]
no need for, let's close.

**Pull request closed without merging**
