### PR TITLE
Hide more symbols of hb-subset

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
@behdad, is this the correct path? or I should've used `inline` having the same effect with `-fvisibility-inlines-hidden`?

**Comment by ebraminio** [comment]
Our "DOS" bot also has a different complains :) https://circleci.com/gh/harfbuzz/harfbuzz/6894

**Comment by ebraminio** [comment]
Doesn't revive much but moves main complains to https://travis-ci.org/harfbuzz/harfbuzz/jobs/339949244#L2480

**Comment by behdad** [comment]
I pushed more fixes.

Also, you should have just used static here, not HB_INTERNAL. Fixed.

**Pull request merged**
