### PR TITLE
[docs] Don’t recommend outdated FDO releases pages

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by ebraminio** [comment]
Thanks :)

**Comment by behdad** [comment]
Okay now only if we can edit the fdo page and mark the project moved...  I'll do it eventually.

**Comment by khaledhosny** [comment]
Can we also redirect harfbuzz.org to harfbuzz.github.io?

**Comment by behdad** [comment]
> Can we also redirect harfbuzz.org to harfbuzz.github.io?

@behnam Can we do that?

**Comment by behnam** [comment]
> > Can we also redirect harfbuzz.org to harfbuzz.github.io?
> 
> @behnam Can we do that?

I can do this, if this is still what you want. So, let me know if that's the case.

**Comment by behdad** [comment]
> I can do this, if this is still what you want. So, let me know if that's the case.

I don't see anything needing action right now. Thanks @behnam

**Pull request merged**
