### PR TITLE
[debug] Add a memory hex dump

### PR DESCRIPTION
**Pull request by ebraminio**
See if makes sense and is in right, it was useful for me not sure whether for others.

### CODE REVIEW

**Comment by behdad** [comment]
I would have liked it more if it had something integrated with HarfBuzz machinery or sanitizer or something.  As it is, not much.

Maybe put it in a tool in src/ that takes table name and dumps it?

**Comment by ebraminio** [comment]
I used its `_hex_dump_font_table` to see first what is going on and then to see if sanitizer has altered the table so thought be useful like this as it was for me sometimes. OK, lets decide about this later.

**Comment by behdad** [comment]
I like having it as a tool as I said.

**Comment by ebraminio** [comment]
That should be integrated with #950 as the difficulty of getting each table's sanitizer.

**Pull request closed without merging**
