### PR TITLE
CMake: Detect pthread with module FindThread

### PR DESCRIPTION
**Pull request by NikitaFeodonit**
Related to issue #2653 and PR #2874.

### CODE REVIEW

**Comment by NikitaFeodonit** [comment]
See the documentations for the module FindThread:
https://cmake.org/cmake/help/v3.21/module/FindThreads.html

I made a check ```if (NOT MSVC)```, since MinGW-w64 has a support for pthread.

**Comment by khaledhosny** [comment]
Hmm, why didn't any of circleci jobs run?

**Comment by NikitaFeodonit** [comment]
I am not familiar with circleci. I see in
[macos-aat-fonts](https://app.circleci.com/pipelines/github/NikitaFeodonit/harfbuzz/5/workflows/2766084b-7bdb-4605-823a-40da8ee17156/jobs/30)
"Apologies! Your build didn’t run because you haven’t selected a plan that includes macOS yet. Please change to a Performance Plan. If you have any questions please feel free to contact support."

I just included the circleci specifically for your library, and selected Free plan.

**Comment by NikitaFeodonit** [comment]
GitHub Actions have the runners with [macOS](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), like Linux and Windows. You could completely switch to GitHub Actions.

**Comment by khaledhosny** [comment]
I’m fine merging this without the CI change, we intentionally don't test CMake because we don't know how to fix it when it breaks.

**Comment by khaledhosny** [comment]
> You could completely switch to GitHub Actions.

Eventually, yes.

**Comment by NikitaFeodonit** [comment]
> I’m fine merging this without the CI change

Should I delete a commit with changes to CI?

**Comment by khaledhosny** [comment]
> > I’m fine merging this without the CI change
> 
> Should I delete a commit with changes to CI?

Yes, please.

**Comment by NikitaFeodonit** [comment]
I removed the commit via `git rebase`.

**Comment by khaledhosny** [comment]
Thanks!

**Pull request merged**
