### PR TITLE
For discussion purposes, very early sketch of APIs for subsetting

### PR DESCRIPTION
**Pull request by rsheeter**
Not expecting to merge, just wanted to get discussion about API structure going.

### CODE REVIEW

**Comment by rsheeter** [comment]
@behdad PTAL. I can't seem to add you as a reviewer.

**Comment by ebraminio** [comment]
I added him. Interesting, is this going to be a new tool on harfbuzz? Something similar to fonttools one but dynamic for Chrome/Android use, perhaps for online memory reduction or something?

**Comment by rsheeter** [comment]
We need it for Google Fonts. We imagine it will have many applications though. Behdad wrote a nice doc @ goo.gl/Qy3Eqc.

**Comment by behdad** [comment]
Is this obsolete?

**Comment by garretrieger** [comment]
Yes

**Pull request closed without merging**
