### PR TITLE
Add links to files used by python scripts.

### LINKED ISSUE #2150: Where to find files used by python scrips?
`gen-arabic-table.py` requires `ArabicShaping.txt UnicodeData.txt Blocks.txt`.

`gen-tag-table.py` requires `languagetags language-subtag-registry`.

etc.

But I could not find those files in the repo, neither links from where to download them.

Yes, after some googling you can find them, but maybe it would be better if links were included in the scripts itself? They can also auto-download them.

### PR DESCRIPTION
**Pull request by RazrFalcon**
Closes #2150

### CODE REVIEW

**Comment by ebraminio** [comment]
Looks great! Do you believe we can somehow indicate also it is the latest version of the files but the address can be change for next release for future readers somehow? Maybe something like "Input files of the script for the latest unicode release:" or anything you see better or not at all.

**Comment by jfkthame** [comment]
> Looks great! Do you believe we can somehow indicate also it is the latest version of the files but the address can be change for the unicode next release for future readers somehow? Maybe something like "Input files of the script for the latest unicode release:" or anything you see better or not at all.

Would it make more sense to point to the https://www.unicode.org/Public/UCD/latest/ location, rather than having to update links each time a new Unicode version is released?

**Comment by ebraminio** [comment]
Didn't know that, makes sense! Sorry for the bikeshedding anyway, with such addresses, just a little indication that it was there as that specific unicode version, something like "Input files as Unicode 12:" maybe would be nice, considering the chance for the file rename in future releases, or maybe not.

**Comment by RazrFalcon** [comment]
Maybe add something like: "Only Unicode 12.0 files are supported." ?

**Comment by ebraminio** [comment]
On that case guessing direct links are better indicative :/ Or, let's merge and think about it more later. Thanks :)

**Comment by behdad** [comment]
I don't understand why this is a good idea. Make it print in the usage output and don't link to specific Unicode version. What's there now is already stale.

**Comment by ebraminio** [comment]
Sure, 6a390df

**Pull request merged**
