### PR TITLE
Meson freetype

### PR DESCRIPTION
**Pull request by ebraminio**
minor things related to freetype in meson

### CODE REVIEW

**Comment by xclaesse** [comment]
I don't think this will work. Meson currently treat subproject cycle as fatal error even with `required: false`. That's arguably a bug in Meson, but atm it's like that.

As far as I understand why you're trying to support here is that case:
- The system has harfbuzz installed.
- The system does not have freetype2 installed.
- We build harfbuzz, a newer version than the one from system for example.
- Harfbuzz fallback to freetype2 subproject because it's not found on system.
- freetype2 finds harfbuzz from system and enable harfbuzz support.

Is that even a possible scenario given that, at least on Ubuntu, harfbuzz depends on feetype?

**Comment by xclaesse** [comment]
> use dependency's has_headers to make pulled cairo has ft support 

`dependency()` does not have `has_headers` argument, only find_library does. What you probably need there is:
```
if cairo_dep.type_name() == 'internal'
  # Not sure here, is it the same dependency object?
  cairo_ft_dep = cairo_dep
  # maybe cairo subproject needs to provide a dependency object for it:
  cairo_ft_dep = subproject('cairo').get_variable('libcairo_ft_dep')
elif cairo_dep.type_name() == 'library' and \
      cpp.has_function('cairo_ft_font_face_create_for_ft_face', prefix: '#include <cairo-ft.h>', dependencies: cairo_dep)
  cairo_ft_dep = cairo_dep
else
  cairo_ft_dep = dependency('cairo-ft', required: false)
endif
```

**Comment by ebraminio** [comment]
> Is that even a possible scenario given that, at least on Ubuntu, harfbuzz depends on freetype?

My understanding is if I declare a default_options meson favors subproject mechanism over looking into those fallbacks? I just wanted those fallbacks, global variable in meson configuration hierarchy be tested one last time, 

> dependency() does not have has_headers argument

Oh, you are right, uploaded #2523 based on your code

> # Not sure here, is it the same dependency object?

If I understand correctly from https://github.com/ebraminio/cairo/blob/d48569e/src/meson.build#L298 it is. All we need is to have cairo as a subproject, if you know a better port let us know.

> cairo_ft_dep = subproject('cairo').get_variable('libcairo_ft_dep')

That port doesn't feature that IIUC

**Comment by xclaesse** [comment]
> > Is that even a possible scenario given that, at least on Ubuntu, harfbuzz depends on freetype?
> 
> My understanding is if I declare a default_options meson favors subproject mechanism over looking into those fallbacks? I just wanted those fallbacks (global variable in meson configuration hierarchy I guess?) be tested one last time.

I'm not sure to understand what you mean here. `default_options` is only used by Meson when configuring the fallback when the dependency cannot be found on the system. It tells freetype2 subproject to not lookup for harfbuzz dependency because we are currently building harfbuzz it would create a dependency cycle.

**Comment by ebraminio** [comment]
> I'm not sure to understand what you mean here. default_options is only used by Meson when configuring the fallback when the dependency cannot be found on the system. It tells freetype2 subproject to not lookup for harfbuzz dependency because we are currently building harfbuzz it would create a dependency cycle.

Okay, so :) Just uploaded https://github.com/harfbuzz/harfbuzz/pull/2527

**Comment by ebraminio** [comment]
> I'm not sure to understand what you mean here. default_options is only used by Meson when configuring the fallback when the dependency cannot be found on the system. It tells freetype2 subproject to not lookup for harfbuzz dependency because we are currently building harfbuzz it would create a dependency cycle.

Just asking, can we first go for a `dependency('', fallback: ['freetype2', 'freetype_dep'], required: false)`? Those fallbacks are for things that are already defined in parent project, isn't it?

**Comment by ebraminio** [comment]
> Just asking, can we first go for a dependency('', fallback: ['freetype2', 'freetype_dep'], required: false)? Those fallbacks are for things that are already defined in parent project, isn't it?

Ooh, I see, nvm, my misunderstanding, thank you very much :)

For more info, from https://mesonbuild.com/Dependencies.html

>>     foo_dep = dependency('foo', fallback : ['foo', 'foo_dep'])
> What this declaration means is that first Meson tries to look up the dependency from the system (such as by using pkg-config). If it is not available, then it builds subproject named foo and from that extracts a variable foo_dep. That means that the return value of this function is either an external or an internal dependency object. Since they can be used interchangeably, the rest of the build definitions do not need to care which one it is. Meson will take care of all the work behind the scenes to make this work.

**Pull request merged**
