### PR TITLE
[subset] Prune cmap12

### PR DESCRIPTION
**Pull request by garretrieger**
Matches changes in fonttools to prune cmap12's that are equivalent to other cmap subtables: https://github.com/fonttools/fonttools/pull/2146

### CODE REVIEW

**Comment by khaledhosny** [comment]
I personally prefer to update the tests in the same commit that changed the code, otherwise when bisecting the first commit will have failing tests.

**Comment by garretrieger** [comment]
> I personally prefer to update the tests in the same commit that changed the code, otherwise when bisecting the first commit will have failing tests.

Squashed the two commits into one.

**Comment by khaledhosny** [comment]
`distcheck` is failing because you removed the colrv1 expected output directories, but they are still referenced from `test/subset/data/Makefile.am`.

**Comment by garretrieger** [comment]
> `distcheck` is failing because you removed the colrv1 expected output directories, but they are still referenced from `test/subset/data/Makefile.am`.

Fixed.

**Comment by behdad** [comment]
> I personally prefer to update the tests in the same commit that changed the code, otherwise when bisecting the first commit will have failing tests.

Right. But github UI makes it impossible to review individual commits touching thousands of files. We can "squash and merge" the PR.

**Pull request merged**
