### PR TITLE
[instancer] Add MVAR values to OS/2

### PR DESCRIPTION
**Pull request by behdad**
Start of applying MVAR during instancing. Untested, and our test suite doesn't seem to hit it either.

### CODE REVIEW

**Comment by behdad** [comment]
cc @madig

**Comment by behdad** [comment]
Needs to be done: hhea and vhea.

**Comment by behdad** [comment]
I tested this with AdobeVFPrototype and the OS/2 part seems to work.

**Comment by behdad** [comment]
This is complete sans the gasp table, which I don't think we subset much.

**Comment by behdad** [comment]
We need to add tests.

**Review by garretrieger — APPROVED** [review]

**Pull request merged**
