### PR TITLE
[ci] Sort out Travis configuration

### PR DESCRIPTION
**Pull request by khaledhosny**
Use a matrix to avoid a gazillion if's.

### CODE REVIEW

**Comment by behdad** [comment]
THANK YOU!

**Comment by ebraminio** [comment]
Conflict on merge! I guess the next can be https://github.com/harfbuzz/harfbuzz/blob/master/appveyor.yml if you interested :)

**Comment by khaledhosny** [comment]
What is conflicting?

**Comment by ebraminio** [comment]
Sorry for confusion, users conflict on pushing the merge button :)

**Pull request merged**
