### PR TITLE
fuzzer fix: null pointer dereference

### PR DESCRIPTION
**Pull request by qxliu76**

### CODE REVIEW

**Comment by behdad** [comment]
We don't expect `current` to be `nullptr`. Do you have more info on why / when this happens? I feel like the best fix belongs somewhere else.

**Comment by qxliu76** [comment]
> We don't expect `current` to be `nullptr`. Do you have more info on why / when this happens? I feel like the best fix belongs somewhere else.

it happens in COLR subset(), after V0 part, I'll try to get more details

**Comment by qxliu76** [comment]
> We don't expect `current` to be `nullptr`. Do you have more info on why / when this happens? I feel like the best fix belongs somewhere else.

The issue is that calloc () failed in hb_pool_t::alloc (), which is called by serializer push () in start_serialize (). This happened before subset method.

**Review by garretrieger — APPROVED** [review]

**Comment by behdad** [comment]
Much better. Thank you.

**Pull request merged**
