### PR TITLE
[subset] Enable layout subsetting by default.

### PR DESCRIPTION
**Pull request by garretrieger**
Fix all differences in the subset tests exposed by this change:
- Correct variation index collection.
- Match fontTool's ValueRecord optimization behaviour (dropping Value's that are zero where possible).

### CODE REVIEW

**Comment by behdad** [comment]
Thanks Garret.

I believe it's time to get a release out. :) @khaledhosny can you do that?

**Comment by khaledhosny** [comment]
If someone can prepare the NEWS entries I can do it (or anyone, really, it is just a git tag and the CI will take care of the rest).

**Comment by khaledhosny** [comment]
(git tag, and updated version in meson.build and Makefile.am)

**Comment by behdad** [comment]
> If someone can prepare the NEWS entries I can do it

Subsetter now fully supports GSUB/GPOS/GDEF tables (including variations); as such, layout tables are retained by subsetter by default.

Thanks.

**Comment by khaledhosny** [comment]
Done.

**Pull request merged**
