### PR TITLE
[gvar] Fix decoding of private points

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3506

@khaledhosny can you please add test case with that glyph and --show-extents?

### CODE REVIEW

**Review by khaledhosny — APPROVED** [review]
I can’t comment on the code, but with this change `hb_font_get_glyph_extents` works for all glyphs in the font and seems to return sensible glyph extents.

**Comment by khaledhosny** [comment]
The glyph extents from ot functions seems to be often quite different from ft functions, but that is probably independent to this issue.

**Comment by behdad** [comment]
Humm

**Comment by behdad** [comment]
> The glyph extents from ot functions seems to be often quite different from ft functions, but that is probably independent to this issue.

File an issue with a sample glyph please.

**Comment by khaledhosny** [comment]
> > The glyph extents from ot functions seems to be often quite different from ft functions, but that is probably independent to this issue.
> 
> File an issue with a sample glyph please.

I’m seeing the difference in a test C program I wrote, but not in hb-shape, so I’m guessing something is broken on my end.

**Pull request merged**
