### PR TITLE
Ft bitmap

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by behdad** [comment]
> * Build when `FT_Get_Transform` is not available.

@khaledhosny any chance you can work on this?

**Comment by khaledhosny** [comment]
> > > * Build when `FT_Get_Transform` is not available.
> > 
> > 
> > @khaledhosny any chance you can work on this?
> 
> Sure, I’ll do right now.

I guess I need to restore parts of the old code and make it conditional, since now tests are failing on CI with old FreeType.

**Comment by behdad** [comment]
I don't understand the failure.

**Comment by khaledhosny** [comment]
Neither I. But I can reproduce it locally by removing the FT_Get_Transform check from meson.build.

**Comment by behdad** [comment]
Seems like a bitmap font that one.

**Comment by behdad** [comment]
Worked around it.

**Comment by behdad** [comment]
Honestly I don't know how it was working, and how it works now, for a bitmap font!

**Comment by behdad** [comment]
Looks like `FT_Set_Char_Size` does set the size variables even if it fails?

**Comment by behdad** [comment]
I'm very confused now.

**Comment by behdad** [comment]
Nope. I was wrong.

**Comment by behdad** [comment]
> Looks like `FT_Set_Char_Size` does set the size variables even if it fails?

Correct. So I made the second `FT_Set_Char_Size` be conditional on having `FT_Get_Transform` as well and test is fixed.

**Comment by behdad** [comment]
> * Figure out the vertical metrics issue;

`ft_face->ascender` et al are zero in the bitmap case. Sigh...

**Comment by behdad** [comment]
> > * Figure out the vertical metrics issue;
> 
> `ft_face->ascender` et al are zero in the bitmap case. Sigh...

Fixed.

**Comment by behdad** [comment]
Still doesn't work with negative font size. But I'm willing to let that go for now.

**Comment by behdad** [comment]
@khaledhosny I think this is ready.

**Comment by behdad** [comment]
Wait. This broke the normal negative font sizes (non-bitmap). Sigh.

**Comment by behdad** [comment]
> Still doesn't work with negative font size. But I'm willing to let that go for now.

Fixed.

**Pull request merged**
