### PR TITLE
better logic for introspection check, and fails on introspection with…

### PR DESCRIPTION
**Pull request by HinTak**
…out gobject

### CODE REVIEW

**Comment by behdad** [comment]
Humm.  Doesn't seem to work: https://circleci.com/gh/harfbuzz/harfbuzz/39139?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by HinTak** [comment]
Argh, it is because of the auto case...

**Comment by HinTak** [comment]
Missing quotes too.

**Comment by HinTak** [comment]
Close for now, reopening when I figure it out

**Pull request closed without merging**
