### PR TITLE
Cygwin fixes and CI build

### PR DESCRIPTION
**Pull request by khaledhosny**
DirectWrite support failed to build, so I disabled it, not sure we care about building it on Cygwin.

Gobject-Introspection failed on x86 build only, hard to debug without and actual Windows machine, so also disabled for now.

### CODE REVIEW

**Comment by ebraminio** [comment]
> DirectWrite support failed to build, so I disabled it, not sure we care about building it on Cygwin.

Can you look again why? It works on msys2.

**Comment by khaledhosny** [comment]
> Can you look again why? It works on msys2.

See https://ci.appveyor.com/project/khaledhosny/harfbuzz/builds/19649313/job/6i6x0liton5epcdr#L1335

**Comment by ebraminio** [comment]
Aha, the trick is here https://github.com/harfbuzz/harfbuzz/blob/9be8062b4d241f02bb96df436e98f10f08bda4f8/appveyor.yml#L49 please apply it to the bot. Thanks

**Comment by ebraminio** [comment]
Of course if you see worth the hassle (not sure if curl available by default)

**Comment by khaledhosny** [comment]
Lets see if the current build will succeed or not first, it is taking a while already (why running tests on AppVeyor is so slow?)

**Comment by ebraminio** [comment]
Thank you Khaled. Not only it is useful as a CI bot, it is also useful as a how to compile and develop harfbuzz on Cygwin, I like this aspect of CI bot scripts also. Thanks

**Pull request merged**
