### PR TITLE
Make more gen-* scripts py3 compatible

### PR DESCRIPTION
**Pull request by ebraminio**
Don't merge yet however, should be tested more before the merge.

### CODE REVIEW

**Comment by behdad** [comment]
lgtm. Thanks.

Did you get to verify that their outputs didn't change?

**Comment by ebraminio** [comment]
Yes, that why I was saying so. Arabic script update seems to have not any change but have a look again at `src/Makefile.am` and `src/hb-ot-shape-complex-indic-table.cc`

**Comment by dscorbett** [comment]
Some of these scripts use `file` instead of `open` and therefore do not work in Python 3.

**Comment by ebraminio** [comment]
Ops! #941

**Pull request merged**
