### PR TITLE
Fixing compiler warnings

### PR DESCRIPTION
**Pull request by jpcomito**
All warning are for format specifiers (-WFormat) in sprintf().

Test: Compile only

### CODE REVIEW

**Comment by jpcomito** [comment]
Thank you for the speedy turnaround!

**Comment by sezero** [comment]
This broke build on older systems where inttypes.h doesn't define the `PRIxxx` macros in C++ unless `__STDC_FORMAT_MACROS` is defined. See, e.g.:

<details>

```
In file included from /tmp/harfbuzz/src/hb-subset-input.hh:37:0,
                 from /tmp/harfbuzz/src/hb-subset.hh:37,
                 from /tmp/harfbuzz/src/hb-open-type.hh:37,
                 from /tmp/harfbuzz/src/hb-aat-ltag-table.hh:28,
                 from /tmp/harfbuzz/src/hb-aat-layout.hh:33,
                 from /tmp/harfbuzz/src/hb-aat-layout.cc:30,
                 from /tmp/harfbuzz/src/harfbuzz.cc:1:
/tmp/harfbuzz/src/hb-font.hh: In member function 'void hb_font_t::glyph_to_string(hb_codepoint_t, char*, unsigned int)':
/tmp/harfbuzz/src/hb-font.hh:655:43: error: expected ')' before 'PRIu32'
     if (size && snprintf (s, size, "gid%" PRIu32 "", glyph) < 0)
                                           ^
/tmp/harfbuzz/src/hb-font.hh:655:59: warning: spurious trailing '%' in format [-Wformat=]
     if (size && snprintf (s, size, "gid%" PRIu32 "", glyph) < 0)
                                                           ^
/tmp/harfbuzz/src/hb-font.hh:655:59: warning: too many arguments for format [-Wformat-extra-args]
/tmp/harfbuzz/src/hb-font.hh:655:59: warning: spurious trailing '%' in format [-Wformat=]
/tmp/harfbuzz/src/hb-font.hh:655:59: warning: too many arguments for format [-Wformat-extra-args]
In file included from /tmp/harfbuzz/src/harfbuzz.cc:7:0:
/tmp/harfbuzz/src/hb-common.cc: In function 'void hb_feature_to_string(hb_feature_t*, char*, unsigned int)':
/tmp/harfbuzz/src/hb-common.cc:1000:70: error: expected ')' before 'PRIu32'
     len += hb_max (0, snprintf (s + len, ARRAY_LENGTH (s) - len, "%" PRIu32 "", feature->value));
                                                                      ^
/tmp/harfbuzz/src/hb-common.cc:1000:95: warning: spurious trailing '%' in format [-Wformat=]
     len += hb_max (0, snprintf (s + len, ARRAY_LENGTH (s) - len, "%" PRIu32 "", feature->value));
                                                                                               ^
/tmp/harfbuzz/src/hb-common.cc:1000:95: warning: too many arguments for format [-Wformat-extra-args]
/tmp/harfbuzz/src/hb-common.cc:1000:95: warning: spurious trailing '%' in format [-Wformat=]
/tmp/harfbuzz/src/hb-common.cc:1000:95: warning: too many arguments for format [-Wformat-extra-args]
In file included from /tmp/harfbuzz/src/hb.hh:539:0,
                 from /tmp/harfbuzz/src/hb-aat-layout.cc:28,
                 from /tmp/harfbuzz/src/harfbuzz.cc:1:
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh: In function 'void OT::glyf_impl::_write_loca(IteratorIn&&, hb_sorted_vector_t<hb_pair_t<unsigned int, unsigned int> >, bool, TypeOut*, unsigned int)':
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:42:52: error: expected ')' before 'PRIu32'
     DEBUG_MSG (SUBSET, nullptr, "loca entry gid %" PRIu32 " offset %u padded-size %u", gid, offset, padded_size);
                                                    ^
/tmp/harfbuzz/src/hb-debug.hh:232:109: note: in definition of macro 'DEBUG_MSG'
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                             ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc: In function 'void apply_stch(const hb_ot_shape_plan_t*, hb_buffer_t*, hb_font_t*)':
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:563:71: error: expected ')' before 'PRId32'
       DEBUG_MSG (ARABIC, nullptr, "rest of word:    count=%u width %" PRId32 "", start - context, w_total);
                                                                       ^
/tmp/harfbuzz/src/hb-debug.hh:232:109: note: in definition of macro 'DEBUG_MSG'
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                             ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:563:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "rest of word:    count=%u width %" PRId32 "", start - context, w_total);
       ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:563:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "rest of word:    count=%u width %" PRId32 "", start - context, w_total);
       ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:564:71: error: expected ')' before 'PRId32'
       DEBUG_MSG (ARABIC, nullptr, "fixed tiles:     count=%d width=%" PRId32 "", n_fixed, w_fixed);
                                                                       ^
/tmp/harfbuzz/src/hb-debug.hh:232:109: note: in definition of macro 'DEBUG_MSG'
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                             ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:564:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "fixed tiles:     count=%d width=%" PRId32 "", n_fixed, w_fixed);
       ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:564:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "fixed tiles:     count=%d width=%" PRId32 "", n_fixed, w_fixed);
       ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:565:71: error: expected ')' before 'PRId32'
       DEBUG_MSG (ARABIC, nullptr, "repeating tiles: count=%d width=%" PRId32 "", n_repeating, w_repeating);
                                                                       ^
/tmp/harfbuzz/src/hb-debug.hh:232:109: note: in definition of macro 'DEBUG_MSG'
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                             ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:565:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "repeating tiles: count=%d width=%" PRId32 "", n_repeating, w_repeating);
       ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:565:7: note: in expansion of macro 'DEBUG_MSG'
       DEBUG_MSG (ARABIC, nullptr, "repeating tiles: count=%d width=%" PRId32 "", n_repeating, w_repeating);
       ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:605:65: error: expected ')' before 'PRIu32'
    DEBUG_MSG (ARABIC, nullptr, "appending %u copies of glyph %" PRIu32 "; j=%u",
                                                                 ^
/tmp/harfbuzz/src/hb-debug.hh:232:109: note: in definition of macro 'DEBUG_MSG'
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                             ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:605:4: note: in expansion of macro 'DEBUG_MSG'
    DEBUG_MSG (ARABIC, nullptr, "appending %u copies of glyph %" PRIu32 "; j=%u",
    ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/hb-ot-shaper-arabic.cc:605:4: note: in expansion of macro 'DEBUG_MSG'
    DEBUG_MSG (ARABIC, nullptr, "appending %u copies of glyph %" PRIu32 "; j=%u",
    ^
In file included from /tmp/harfbuzz/src/harfbuzz.cc:47:0:
/tmp/harfbuzz/src/hb-ot-tag.cc: In function 'const hb_language_impl_t* hb_ot_tag_to_language(hb_tag_t)':
/tmp/harfbuzz/src/hb-ot-tag.cc:551:37: error: expected ')' before 'PRIx32'
     snprintf (str, 16, "x-hbot-%08" PRIx32 "", tag);
                                     ^
/tmp/harfbuzz/src/hb-ot-tag.cc:551:51: warning: conversion lacks type at end of format [-Wformat=]
     snprintf (str, 16, "x-hbot-%08" PRIx32 "", tag);
                                                   ^
/tmp/harfbuzz/src/hb-ot-tag.cc:551:51: warning: too many arguments for format [-Wformat-extra-args]
/tmp/harfbuzz/src/hb-ot-tag.cc:551:51: warning: conversion lacks type at end of format [-Wformat=]
/tmp/harfbuzz/src/hb-ot-tag.cc:551:51: warning: too many arguments for format [-Wformat-extra-args]
In file included from /tmp/harfbuzz/src/hb.hh:539:0,
                 from /tmp/harfbuzz/src/hb-aat-layout.cc:28,
                 from /tmp/harfbuzz/src/harfbuzz.cc:1:
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh: In instantiation of 'void OT::glyf_impl::_write_loca(IteratorIn&&, hb_sorted_vector_t<hb_pair_t<unsigned int, unsigned int> >, bool, TypeOut*, unsigned int) [with IteratorIn = hb_array_t<const unsigned int>&; TypeOut = OT::IntType<short unsigned int>; typename hb_enable_if<hb_is_source_of<Iterator, unsigned int>::value>::type* <anonymous> = 0u; hb_sorted_vector_t<hb_pair_t<unsigned int, unsigned int> > = hb_vector_t<hb_pair_t<unsigned int, unsigned int>, true>]':
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:106:111:   required from 'bool OT::glyf_impl::_add_loca_and_head(hb_subset_context_t*, Iterator, bool) [with Iterator = hb_array_t<const unsigned int>; typename hb_enable_if<hb_is_source_of<Iterator, unsigned int>::value>::type* <anonymous> = 0u]'
/tmp/harfbuzz/src/OT/glyf/glyf.hh:134:9:   required from here
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:42:5: note: in expansion of macro 'DEBUG_MSG'
     DEBUG_MSG (SUBSET, nullptr, "loca entry gid %" PRIu32 " offset %u padded-size %u", gid, offset, padded_size);
     ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:42:5: note: in expansion of macro 'DEBUG_MSG'
     DEBUG_MSG (SUBSET, nullptr, "loca entry gid %" PRIu32 " offset %u padded-size %u", gid, offset, padded_size);
     ^
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh: In instantiation of 'void OT::glyf_impl::_write_loca(IteratorIn&&, hb_sorted_vector_t<hb_pair_t<unsigned int, unsigned int> >, bool, TypeOut*, unsigned int) [with IteratorIn = hb_array_t<const unsigned int>&; TypeOut = OT::IntType<unsigned int>; typename hb_enable_if<hb_is_source_of<Iterator, unsigned int>::value>::type* <anonymous> = 0u; hb_sorted_vector_t<hb_pair_t<unsigned int, unsigned int> > = hb_vector_t<hb_pair_t<unsigned int, unsigned int>, true>]':
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:108:112:   required from 'bool OT::glyf_impl::_add_loca_and_head(hb_subset_context_t*, Iterator, bool) [with Iterator = hb_array_t<const unsigned int>; typename hb_enable_if<hb_is_source_of<Iterator, unsigned int>::value>::type* <anonymous> = 0u]'
/tmp/harfbuzz/src/OT/glyf/glyf.hh:134:9:   required from here
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: spurious trailing '%' in format [-Wformat=]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:42:5: note: in expansion of macro 'DEBUG_MSG'
     DEBUG_MSG (SUBSET, nullptr, "loca entry gid %" PRIu32 " offset %u padded-size %u", gid, offset, padded_size);
     ^
/tmp/harfbuzz/src/hb-debug.hh:232:120: warning: too many arguments for format [-Wformat-extra-args]
 #define DEBUG_MSG(WHAT, OBJ, ...)    _hb_debug_msg<HB_DEBUG_##WHAT> (#WHAT, (OBJ), nullptr,    false, 0, 0, __VA_ARGS__)
                                                                                                                        ^
/tmp/harfbuzz/src/OT/glyf/glyf-helpers.hh:42:5: note: in expansion of macro 'DEBUG_MSG'
     DEBUG_MSG (SUBSET, nullptr, "loca entry gid %" PRIu32 " offset %u padded-size %u", gid, offset, padded_size);
     ^
make[2]: *** [CMakeFiles/harfbuzz.dir/src/harfbuzz.cc.o] Error 1
make[1]: *** [CMakeFiles/harfbuzz.dir/all] Error 2
make: *** [all] Error 2
```
</details>

My fix is defining `__STDC_FORMAT_MACROS` inthe files touched by this P/R:
```diff
diff --git a/src/OT/glyf/glyf-helpers.hh b/src/OT/glyf/glyf-helpers.hh
index 635cdfd..7faa5ad 100644
--- a/src/OT/glyf/glyf-helpers.hh
+++ b/src/OT/glyf/glyf-helpers.hh
@@ -1,6 +1,9 @@
 #ifndef OT_GLYF_GLYF_HELPERS_HH
 #define OT_GLYF_GLYF_HELPERS_HH
 
+#ifndef __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS 1
+#endif
 
 #include "../../hb-open-type.hh"
 #include "../../hb-subset-plan.hh"
diff --git a/src/hb-common.cc b/src/hb-common.cc
index 6277f46..608625d 100644
--- a/src/hb-common.cc
+++ b/src/hb-common.cc
@@ -26,6 +26,11 @@
  * Google Author(s): Behdad Esfahbod
  */
 
+#ifndef __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS 1
+#endif
+
+
 #include "hb.hh"
 #include "hb-machinery.hh"
 #include "inttypes.h"
diff --git a/src/hb-font.hh b/src/hb-font.hh
index a748ce5..6b54ef4 100644
--- a/src/hb-font.hh
+++ b/src/hb-font.hh
@@ -29,6 +29,10 @@
 #ifndef HB_FONT_HH
 #define HB_FONT_HH
 
+#ifndef __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS 1
+#endif
+
 #include "hb.hh"
 
 #include "hb-face.hh"
diff --git a/src/hb-ot-shaper-arabic.cc b/src/hb-ot-shaper-arabic.cc
index 70a1dff..9751ee0 100644
--- a/src/hb-ot-shaper-arabic.cc
+++ b/src/hb-ot-shaper-arabic.cc
@@ -24,6 +24,10 @@
  * Google Author(s): Behdad Esfahbod
  */
 
+#ifndef __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS 1
+#endif
+
 #include "hb.hh"
 
 #ifndef HB_NO_OT_SHAPE
diff --git a/src/hb-ot-tag.cc b/src/hb-ot-tag.cc
index d8b1151..234d30b 100644
--- a/src/hb-ot-tag.cc
+++ b/src/hb-ot-tag.cc
@@ -26,6 +26,10 @@
  * Google Author(s): Behdad Esfahbod, Roozbeh Pournader
  */
 
+#ifndef __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS 1
+#endif
+
 #include "hb.hh"
 #include "inttypes.h"
 
```

If it is acceptable, please tell me if you want a P/R, or you guys can apply manually.

P.S.: `#include "inttypes.h"` seems wrong to me: It should be `#include <inttypes.h>` no?

**Comment by behdad** [comment]
Thanks.

I suggest moving the include and macro to `hb.hh`.  And probably as `#include <cinttypes>`.

**Comment by behdad** [comment]
I have a slight preference on reverting this patch and just doing casts as needed.

**Comment by sezero** [comment]
OK, anything that works.

**Comment by behdad** [comment]
I reverted this for now, since we probably will have a release today or tomorrow.

**Comment by behdad** [comment]
> All warning are for format specifiers (-WFormat) in sprintf().

Which compiler is this? What's special about it?

**Comment by sezero** [comment]
> > All warning are for format specifiers (-WFormat) in sprintf().
> 
> Which compiler is this? What's special about it?

I'm _guessing_ that maybe it's not the compiler but libc where int32_t is a long instead of int??
(@jpcomito should have the right answers, of course..)

**Comment by jpcomito** [comment]
It is GCC for a Cortex-M33 where uint32_t is a long int.

**Comment by behdad** [comment]
LGTM

**Comment by sezero** [comment]
> LGTM

Created https://github.com/harfbuzz/harfbuzz/pull/4622

**Comment by behdad** [comment]
This is what I mean: https://github.com/harfbuzz/harfbuzz/pull/4623

**Pull request merged**
