### PR TITLE
[directwrite] Support feature ranges

### PR DESCRIPTION
**Pull request by khaledhosny**
Code copied from hb-uniscribe.cc and adapted to use DirectWrite types.
May be there is a better way to de-duplicate the code, though I'm not exactly sure how or if it is worth it.

### CODE REVIEW

**Comment by behdad** [comment]
I'm okay merging this first, then moving common code to a shared template.

We might do something similar for `hb-ot-shape` as well, to avoid doing a buffer loop per user feature.

**Comment by khaledhosny** [comment]
(I don’t know much about C++ templates, except that some people hated them decades ago).

**Comment by behdad** [comment]
> (I don’t know much about C++ templates, except that some people hated them decades ago).

It's simple and nice. Give it a try if you feel like.

C++ has a 1000 problems. Simple use of templates is fine.

**Comment by behdad** [comment]
> (I don’t know much about C++ templates, except that some people hated them decades ago).

It's simple and nice. Give it a try if you feel like.

C++ has a 1000 problems. Simple use of templates is fine.

**Pull request merged**
