### PR TITLE
Skip hb_shape if buffer object is immutable

### PR DESCRIPTION
**Pull request by ebraminio**
@khaledhosny does it make sense? Maybe doesn't worth it as it is highly unlikely or maybe not? Please have a look. Thanks!

### CODE REVIEW

**Comment by khaledhosny** [comment]
No idea.

**Comment by ebraminio** [comment]
Okay, let's have this in, worst case we can revert it later. Thanks!

**Comment by behdad** [comment]
You don't even mention what your are trying to fix. So,  no, doesn't make sense. And doesn't make sense anyway. Empty buffer should be handled just fine. Open issue for what you trying to fix first. And NO DON'T MERGE WHAT NO ONE SAYS IS A GOOD IDEA.  Sigh.

**Comment by ebraminio** [comment]
Oh, it is actually a ENOMEM issue as empty buffer will be given from null poll that's why it is immutable, and easy to reproduce also just remove the added lines from hb_shape and run and this will happen in seconds,

`CXXFLAGS="-fsanitize=address,fuzzer-no-link" meson fuzzbuild --default-library=static -Dfuzzer_ldflags="-fsanitize=address,fuzzer" -Dexperimental_api=true && ninja -C fuzzbuild test/fuzzing/hb-{shape,draw,subset,set}-fuzzer && fuzzbuild/test/fuzzing/hb-shape-fuzzer`

**Comment by ebraminio** [comment]
Just for the reference this is what I easily get if I remove that line from hb_shape, are we touching the null pool? Guess we have to check in our fuzzers also that null pool are intact. 

```
hb-shape-fuzzer: ../src/hb-buffer.cc:1517: void hb_buffer_add_utf(hb_buffer_t *, const typename utf_t::codepoint_t *, int, unsigned int, int) [utf_t = hb_utf8_t]: Assertion `(buffer->content_type == HB_BUFFER_CONTENT_TYPE_UNICODE) || (!buffer->len && (buffer->content_type == HB_BUFFER_CONTENT_TYPE_INVALID))' failed.
==35196== ERROR: libFuzzer: deadly signal
    #0 0x56180b34572b in __sanitizer_print_stack_trace (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x37472b)
    #1 0x56180b296df9 in fuzzer::PrintStackTrace() (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2c5df9)
    #2 0x56180b273089 in fuzzer::Fuzzer::CrashCallback() (.part.0) (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a2089)
    #3 0x56180b273149 in fuzzer::Fuzzer::StaticCrashSignalCallback() (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a2149)
    #4 0x7f526345a95f  (/usr/lib/libpthread.so.0+0x1495f)
    #5 0x7f526328e354 in raise (/usr/lib/libc.so.6+0x3c354)
    #6 0x7f5263277852 in abort (/usr/lib/libc.so.6+0x25852)
    #7 0x7f5263277726 in __assert_fail_base.cold (/usr/lib/libc.so.6+0x25726)
    #8 0x7f5263286935 in __assert_fail (/usr/lib/libc.so.6+0x34935)
    #9 0x56180b457ada in void hb_buffer_add_utf<hb_utf8_t>(hb_buffer_t*, hb_utf8_t::codepoint_t const*, int, unsigned int, int) /home/ebrahim/Desktop/harfbuzz/fuzzbuild/../src/hb-buffer.cc:1516:3
    #10 0x56180b457677 in hb_buffer_add_utf8 /home/ebrahim/Desktop/harfbuzz/fuzzbuild/../src/hb-buffer.cc:1598:3
    #11 0x56180b373fa3 in LLVMFuzzerTestOneInput /home/ebrahim/Desktop/harfbuzz/fuzzbuild/../test/fuzzing/hb-shape-fuzzer.cc:36:5
    #12 0x56180b273a6e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a2a6e)
    #13 0x56180b275ca0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a4ca0)
    #14 0x56180b276639 in fuzzer::Fuzzer::MutateAndTestOne() (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a5639)
    #15 0x56180b2789e7 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2a79e7)
    #16 0x56180b2624d8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2914d8)
    #17 0x56180b2985e3 in main (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x2c75e3)
    #18 0x7f5263279001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #19 0x56180b24fc5d in _start (/home/ebrahim/Desktop/harfbuzz/fuzzbuild/test/fuzzing/hb-shape-fuzzer+0x27ec5d)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 4 ChangeBinInt-CopyPart-CrossOver-EraseBytes-; base unit: 6655ca187ca7982477da01572e2d2ae354853fa8
0xe6,0xa,0x0,0xa,0x31,0x47,0x53,0x55,0xef,0x9,0xa,0x0,0x0,
\xe6\x0a\x00\x0a1GSU\xef\x09\x0a\x00\x00
artifact_prefix='./'; Test unit written to ./crash-4833cbe7ccc4665385c9faa7efb4bb307ebd26bd
Base64: 5goACjFHU1XvCQoAAA==
```

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/blob/4f8753464/src/hb-shape-plan.cc#L328 returns true for a null object and that means modifying the null pool https://github.com/harfbuzz/harfbuzz/blob/679fac8/src/hb-shape.cc#L144-L145 thus uploaded https://github.com/harfbuzz/harfbuzz/pull/2625

Filed https://github.com/google/sanitizers/issues/1291 also as we like to get noticed about null pool modification at the spot not when things gets dirty

**Pull request merged**
