### PR TITLE
[AAT] Support Lookup<OffsetTo<>>, needed by lcar and just

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by behdad** [comment]
Thanks.  A couple comments:
1. No newline between several sanitize() functions of the same struct.
2. Don't rename base.
3. The new argument should be called template <typename T> T user_data.  See ArrayOf<>.

**Comment by ebraminio** [comment]
Applied.

**Comment by behdad** [comment]
user_data needs to be templatized as I said, such that it can pass any type (int for example).  See ArrayOf.

**Comment by ebraminio** [comment]
My bad. Applied

**Pull request merged**
