### PR TITLE
Fix SunCC/ODS compile on CMake

### PR DESCRIPTION
**Pull request by ebraminio**
This obviously doesn't make sense but I tried other combinations with no success.

### CODE REVIEW

**Comment by behdad** [comment]
I was wondering why the __hidden isn't working...

**Comment by ebraminio** [comment]
It doesn't work without __hidden. Interestingly it is similar with MSVC fail, maybe `extern HB_INTERNAL const void * const _hb_NullPool[HB_NULL_POOL_SIZE / sizeof (void *)];` are confusing them?

**Comment by ebraminio** [comment]
So should this be merged or we should get more confident what is going on before the merge? (or ask Oracle guys?)

**Comment by behdad** [comment]
This patch doesn't look right.

Ok, maybe the Sun compiler does not hide data members.  I have another idea for how to fix this and the Windows failure.  For Windows, though, wouldn't using the harfbuzz.def thing fix it?  We also need to produce harfbuzz-subset.def by the way.

**Comment by behdad** [comment]
I ssh'ed and checked. __hidden doesn't seem to do anything on this compiler on this platform (Linux). I'm removing it.

**Pull request closed without merging**
