### PR TITLE
[font] Add public API for synthetic slant

### PR DESCRIPTION
**Pull request by behdad**
New API:

+ hb_font_set_synthetic_slant()
+ hb_font_get_synthetic_slant()

Fixes https://github.com/harfbuzz/harfbuzz/issues/3196

### CODE REVIEW

**Comment by behdad** [comment]
@matthiasclasen see if you can call this from pangofc.

**Comment by behdad** [comment]
This actually should work already.

**Comment by behdad** [comment]
Using `pango-view` and IranNastaliq font, showing artifact in synthetic-slanted font:
```
behdad:build 0 (main)$ ./utils/pango-view --font 'IranNastaliq italic 348' --text سلام --output=slanted.png
```
slanted
```
behdad:build 0 (main)$ ./utils/pango-view --font 'IranNastaliq 348' --text سلام --output=upright.png
```
upright
[IranNastaliq.zip](https://github.com/harfbuzz/harfbuzz/files/7740953/IranNastaliq.zip)

**Comment by matthiasclasen** [comment]
Here is a small fix: https://github.com/harfbuzz/harfbuzz/pull/3339

**Comment by matthiasclasen** [comment]
Here is the result I get with that fix:

Screenshot from 2021-12-19 21-26-44

**Comment by matthiasclasen** [comment]
The slant isn't applied to the the caret slope metrics, afaics. Do you plan on doing that ?

**Comment by behdad** [comment]
Good catch re sub-font. And yes, I'll apply it to caret slope.

**Comment by behdad** [comment]
> The slant isn't applied to the the caret slope metrics, afaics. Do you plan on doing that ?

Yes. That, and to the font slant returned by hb-style API.

**Comment by matthiasclasen** [comment]
Oh, I was thinking of HB_OT_METRICS_TAG_HORIZONTAL_CARET_RISE and HB_OT_METRICS_TAG_HORIZONTAL_CARET_RUN, which I'm using in pango for determining at which angle to draw the caret

**Comment by behdad** [comment]
> Oh, I was thinking of HB_OT_METRICS_TAG_HORIZONTAL_CARET_RISE and HB_OT_METRICS_TAG_HORIZONTAL_CARET_RUN, which I'm using in pango for determining at which angle to draw the caret

I know. I'll get to those as well.

**Comment by behdad** [comment]
> @matthiasclasen see if you can call this from pangofc.

https://gitlab.gnome.org/GNOME/pango/-/merge_requests/474

**Comment by behdad** [comment]
@matthiasclasen Okay, I implemented caret slope part as well. Please test & review.

**Comment by behdad** [comment]
@jfkthame @drott Something you might want to hook up in Firefox / Chrome Linux as well.

**Comment by matthiasclasen** [comment]
Works fine in my testing

Screenshot from 2022-01-02 13-28-49

**Comment by behdad** [comment]
> Works fine in my testing

Yoohoo. Thanks!

**Review by matthiasclasen — APPROVED** [review]
Looks all good to me.

**Comment by behdad** [comment]
Webpage test: http://behdad.org/slant/

**Comment by khaledhosny** [comment]
> Webpage test: http://behdad.org/slant/

Interestingly, it looks good in Firefox already:
Screenshot_20220103-162446~2

Compared to Chrome:
Screenshot_20220103-162551~2

**Pull request merged**
