### PR TITLE
removed assert

### PR DESCRIPTION
**Pull request by blueshade7**
get rid of assert for issue #1443 and handle default case silently

### CODE REVIEW

**Comment by behdad** [comment]
Silently ignoring would be more like "return 0" or something to me.  This is defaulting to opCode_version, which I find weird.

**Comment by behdad** [comment]
Or, it definitely cannot happen, even for bad input?

**Comment by blueshade7** [comment]
When double-checking the code to say "can't happen", I realized that `OpCode_BaseFontName` is not handled when it must be. I will open an issue for it.

**Comment by blueshade7** [comment]
At first I had OpCodes as enum actually, then some compiler complained about value duplicates. I could have split it in two, OpCode_Dict and OpCode_CS and cast between two as necessary, but simply just used macro constants.

**Pull request merged**
