### PR TITLE
 [minor] Fix common typos: substition, the the.

### PR DESCRIPTION
**Pull request by HalCanary**
s/substition/substitution/
    s/the the/the/

### CODE REVIEW

**Comment by behdad** [comment]
Thank you!  The indicies ones are autogenerated from respective .rl files.  Please update the .rl as well.

**Comment by HalCanary** [comment]
> Thank you! The indicies ones are autogenerated from respective .rl files. Please update the .rl as well.

D'oh!  The spelling "indicies" actually comes from Ragel.  I should send them a pull request too!

**Comment by HalCanary** [comment]
Please review latest version.

**Comment by behdad** [comment]
Thanks.  You're right.  Others have had pointed 'indicies' out before and I had reported it to ragel maintainer.  Might be fixed in ragel master.

**Comment by ebraminio** [comment]
Nice. Thank you :)

**Comment by HalCanary** [comment]
And I fixed Ragel upstream:
https://github.com/ehdtee/colm-suite/commit/1a1662476e5717916619c3d0797678f68f5d29d3

**Pull request merged**
