### PR TITLE
[ot-shape] Enable dist feature by default

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes https://github.com/harfbuzz/harfbuzz/issues/1907

Not sure if I did this right.

### CODE REVIEW

**Comment by dscorbett** [comment]
Some specific shapers currently enable 'dist'; they should be changed not to explicitly, but instead inherit from the default setting.

**Comment by khaledhosny** [comment]
> Some specific shapers currently enable 'dist'; they should be changed not to explicitly, but instead inherit from the default setting.

Right, but I’m not sure what is the way to do this, just drop `dist` from their feature lists?

**Comment by dscorbett** [comment]
I guess so: USE etc. all enable 'mark' too, and that isn’t explicit in each one’s feature list.

**Comment by khaledhosny** [comment]
Waiting for Behdad, I’m pretty much stabbing in the dark here.

**Comment by behdad** [comment]
1. I think it should go into `horizontal_features`.  The `F_GLOBAL` is correct.

2. Remove from indic, USE, khmer, myanmar.

I wonder if we should also apply `abvm`/`blwm` unconditionally.

**Comment by khaledhosny** [comment]
>     1. I think it should go into `horizontal_features`.  The `F_GLOBAL` is correct.
> 
>     2. Remove from indic, USE, khmer, myanmar.

I just did so.

> I wonder if we should also apply `abvm`/`blwm` unconditionally.

Good question. Core Text seems to apply them to Latin text, but Uniscribe doesn’t.

**Comment by behdad** [comment]
> > I wonder if we should also apply `abvm`/`blwm` unconditionally.
> 
> Good question. Core Text seems to apply them to Latin text, but Uniscribe doesn’t.

I'd say we do it.  Feel free to merge this and do that later though.

I think dist goes into horizontal-features, whereas abvm/blwm go in common-features.

**Pull request merged**
