### PR TITLE
[SVG ] Implementation

### PR DESCRIPTION
**Pull request by ebraminio**
Works on https://github.com/symbolset/ss-emoji-beta/blob/master/ss-emoji-adobe-mozilla.ttf and I was able to dump the SVGs inside the font with it!

### CODE REVIEW

**Comment by ebraminio** [comment]
Works on https://github.com/adobe-fonts/emojione-color but needs a gz extractor in order to work.

**Comment by KrasnayaPloshchad** [comment]
So there is a necessary to add hb-gz.cc in order to allow HarfBuzz build with gz, isn’t it?

**Comment by ebraminio** [comment]
I think the short/medium plan is to provide the very gzipped blob to users so they can decode the blob for themselves and use their own SVG renderer (as librsvg or anything available on the client) with the provided blobs.

**Comment by ebraminio** [comment]
Oh I think I was unclear on what I mean, I provided a temporarily and commented dump function that saves blob of the font on files. The functionality works great on the first font but on the Adobe fonts, it extracts the SVGs as well but they are not in correct format as the need to be extracted first, basically they are SVGZ instead SVG.

**Comment by behdad** [comment]
Yeah, we don't decode it. Just return.

**Comment by ebraminio** [comment]
The added tables are starving for public API Behdad :) I believe we can start with COLR/CPAL.

**Pull request merged**
