### PR TITLE
BASE table

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by ebraminio** [comment]
Build issues are fixed

**Comment by ebraminio** [comment]
Of course whether `hb_ot_base_has_data` API is needed is another question.

**Comment by behdad** [comment]
Thanks. :)

**Comment by ebraminio** [comment]
What APIs do you imagine for this Behdad?

**Comment by ebraminio** [comment]
Or, sorry [again] for rush you on this.

**Comment by behdad** [comment]
> What APIs (or any) do you imagine for this Behdad?

Have to think about it. Let's remove the has_info() API and merge this; figure out API later.

**Comment by eroux** [comment]
Oh, thanks a lot for merging that, that comes as a very pleasant surprise!

**Comment by behdad** [comment]
Thank you!!

**Pull request merged**
