### PR TITLE
Override USE category for Grantha and Tirhuta visargas to allow udatta and anudatta

### PR DESCRIPTION
**Pull request by punchcutter**
https://github.com/harfbuzz/harfbuzz/issues/1631

### CODE REVIEW

**Comment by behdad** [comment]
Thanks.  Would be nice to add tests as well.

**Comment by punchcutter** [comment]
Yes, I've been meaning to add a few other tests as well. I'll try to get something in here soon.

**Comment by behdad** [comment]
Thanks!

**Comment by Richard57** [comment]
What was the justification for this change?  It seems that Devanagari (dev2, deva?) has the wrong order.  See https://unicode.org/mail-arch/unicode-ml/y2019-m12/0046.html et seq for a discussion on the Unicode list that extends to this month.

**Pull request merged**
