### PR TITLE
Update to Unicode 12.0.0

### PR DESCRIPTION
**Pull request by dscorbett**

### CODE REVIEW

**Comment by behdad** [comment]
Thanks. We should also update ucdn.

**Comment by dscorbett** [comment]
Okay, I’ll do that.

**Comment by behdad** [comment]
Thanks.  Can you make a PR for ucdn update as well?

**Comment by dscorbett** [comment]
grigorig/ucdn#22 has already been merged.

**Comment by behdad** [comment]
Right.  I meant against HB.  I can do that as well, but feel free to go ahead.

**Comment by dscorbett** [comment]
This pull request already included the latest commit of UCDN.

**Comment by behdad** [comment]
I see.  Thanks.

**Pull request merged**
