### PR TITLE
HB_NO_VAR: Fix build, drop fvar, avar, cvar, MVAR tables from subsets

### PR DESCRIPTION
**Pull request by tpetillon**
In the same vein as #3736, this fixes compilation when in `HB_NO_VAR` mode.

I’m not familiar with the code, so I hope I didn’t `#ifndef` out too much or too little code.

### CODE REVIEW

**Comment by qxliu76** [comment]
I'd suggest add this `ifndef` wrapper here: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset.cc#L518
fvar, avar,cvar and MVAR should be all wrapped.

```
#ifndef HB_NO_VAR
case HB_OT_TAG_fvar:
    if (plan->user_axes_location.is_empty ()) return _passthrough (plan, tag);
    return _subset<const OT::fvar> (plan, buf);
  case HB_OT_TAG_avar:
    if (plan->user_axes_location.is_empty ()) return _passthrough (plan, tag);
    return _subset<const OT::avar> (plan, buf);
  case HB_OT_TAG_cvar:
    if (plan->user_axes_location.is_empty ()) return _passthrough (plan, tag);
    return _subset<const OT::cvar> (plan, buf);
  case HB_OT_TAG_MVAR:
    if (plan->user_axes_location.is_empty ()) return _passthrough (plan, tag);
    return _subset<const OT::MVAR> (plan, buf);
#endif
```

**Comment by tpetillon** [comment]
@qxliu76 I’ve pushed the suggested `#ifndef` wrapper in hb-subset.

**Comment by qxliu76** [comment]
> @qxliu76 I’ve pushed the suggested `#ifndef` wrapper in hb-subset.

Thanks! Can you also delete the first commit? Since cvar is dropped, the first commit is not needed now.

**Comment by behdad** [comment]
> > @qxliu76 I’ve pushed the suggested `#ifndef` wrapper in hb-subset.
> 
> Thanks! Can you also delete the first commit? Since cvar is dropped, the first commit is not needed now.

I think that's needed, otherwise the `face->ot.tables.fvar` will not compile.

**Comment by qxliu76** [comment]
> > > @qxliu76 I’ve pushed the suggested `#ifndef` wrapper in hb-subset.
> > 
> > 
> > Thanks! Can you also delete the first commit? Since cvar is dropped, the first commit is not needed now.
> 
> I think that's needed, otherwise the `face->ot.tables.fvar` will not compile.

Oh I think we can get rid of that code block because it's covered by below passthrough: 
```
case HB_OT_TAG_fvar:
    if (plan->user_axes_location.is_empty ()) return _passthrough (plan, tag);
    return _subset<const OT::fvar> (plan, buf);
```
What do you think?

**Comment by behdad** [comment]
> What do you think?

I believe so, yes.

**Comment by qxliu76** [comment]
@tpetillon can you help remove the whole code block wrapped by your 1st commit? After that, your 1st commit can be deleted. Thanks!

**Comment by behdad** [comment]
Thank you!

**Comment by tpetillon** [comment]
All right, I deleted the block altogether.

**Pull request merged**
