### PR TITLE
[cmake] fix symbol exporting issue on newer gcc

### LINKED ISSUE #723: CMake builds exposing "roundf" as a "weak" symbol
Not that important (or at all) but as [this bot log](https://circleci.com/gh/harfbuzz/harfbuzz/5035) "_ZSt5roundf" is exposed as a weak symbol but this just happens on Ubuntu 17.10 and was not happening on an older version and it only happens on CMake builds. Steps to reproduce:

1. `cmake -DHB_CHECK=ON -Bbuild -H. -GNinja && ninja -Cbuild && CTEST_OUTPUT_ON_FAILURE=1 CTEST_PARALLEL_LEVEL=8 ninja -Cbuild test`
2. `nm build/libharfbuzz.so | grep ' W '`

It can't see why why just this symbol is exposed on this way. [This](https://github.com/harfbuzz/harfbuzz/commit/8b60e7c2c301a24906d591c80c42fd5e506072d2#diff-af3b638bc2a3e6c650974192a53c7291) can be reverted if this could be fixed.

### PR DESCRIPTION
**Pull request by ebraminio**
Closes #723

### CODE REVIEW

**Comment by behdad** [comment]
What's the "fix"?

**Comment by ebraminio** [comment]
Adding -D__CORRECT_ISO_CPP11_MATH_H_PROTO_FP, bringing back links to libc libm.

**Comment by ebraminio** [comment]
Of course I am not sure why -D__CORRECT_ISO_CPP11_MATH_H_PROTO_FP was needed but that was the only way to bring back disabled exported symbols tests on CMake.

**Comment by behdad** [comment]
Where did you get that from?
This cmake experiment just made me appreciate the good old autotools a lot more :).

**Comment by ebraminio** [comment]
From looking at its header, hehe.

**Pull request merged**
