### PR TITLE
[subset] Add a test for CFF2 instancing.

### PR DESCRIPTION
**Pull request by garretrieger**
Adds option to disable the fonttools comparison check in the test. This is needed since CFF2 instancing is not yet supported in fonttools.

For #4125

### CODE REVIEW

**Comment by khaledhosny** [comment]
FontTools varLib.mutator supports CFF2 instancing

**Comment by garretrieger** [comment]
I'm running into this error: https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/varLib/instancer/__init__.py#L1085 when trying to use fonttools. Should that check be removed on the fonttools side then?

**Comment by khaledhosny** [comment]
[varLib.mutator](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/varLib/mutator.py) is a different one (older, and officially “deprecated”, and does not support L3 and L4 instancing, but it supports CFF2). Just in case you want to check CFF2 instancing against it.

**Comment by behdad** [comment]
I don't think mutator supports blending the Private dict etc. So it needs more work to be in par with HarfBuzz now. Not sure it's worth trying. Or maybe it is.

**Pull request merged**
