### PR TITLE
[serialize] Extract iterable copy, copy_all

### PR DESCRIPTION
**Pull request by ebraminio**
https://github.com/harfbuzz/harfbuzz/pull/1985#discussion_r327272300 IIUC

### CODE REVIEW

**Comment by behdad** [comment]
Why call it `copy_all` and not just `copy`?

**Comment by behdad** [comment]
That way it would work for iterators of iterators as well.

**Comment by ebraminio** [comment]
> Why call it copy_all and not just copy?

Confused the compiler to pick which method :/

**Comment by behdad** [comment]
> > Why call it copy_all and not just copy?
> 
> Confused the compiler to pick which method :/

That's what hb_priority is about.  It's already in the implementation of copy(), check it out.

**Comment by ebraminio** [comment]
> That's what hb_priority is about. It's already in the implementation of copy(), check it out.

That's nice, I didn't know about it and can understand it now but couldn't make it work :/

**Comment by behdad** [comment]
Can you comment on status of this?  Where you are blocked?  I like to help, but don't know how.

**Comment by ebraminio** [comment]
And needs someway to detect if iteration needs `auto &x` or `auto i`

**Comment by behdad** [comment]
Use decltype(*it)?

**Comment by ebraminio** [comment]
Great. Now applying something like this over the current working patch,

```diff
diff --git a/src/hb-ot-layout-gpos-table.hh b/src/hb-ot-layout-gpos-table.hh
index 42887399..40d833ab 100644
--- a/src/hb-ot-layout-gpos-table.hh
+++ b/src/hb-ot-layout-gpos-table.hh
@@ -544,7 +544,7 @@ struct SinglePosFormat1
     if (unlikely (!c->extend_min (*this))) return;
     if (unlikely (!c->check_assign (valueFormat, valFormat))) return;
 
-    c->copy_all (hb_second (*it));
+    c->copy (hb_second (*it));
 
     auto glyphs =
     + it
diff --git a/src/hb-serialize.hh b/src/hb-serialize.hh
index ea6b3fce..5fb5349f 100644
--- a/src/hb-serialize.hh
+++ b/src/hb-serialize.hh
@@ -365,6 +365,12 @@ struct hb_serialize_context_t
   Type *embed (const Type &obj)
   { return embed (hb_addressof (obj)); }
 
+  template<typename Iterator,
+          hb_requires (hb_is_iterator (Iterator)),
+          typename ...Ts>
+  Iterator _copy (Iterator it, hb_priority<2>, Ts&&... ds)
+  { for (decltype (*it) _ : it) copy (_, hb_forward<Ts> (ds)...); return it; }
+
   template <typename Type, typename ...Ts> auto
   _copy (const Type &src, hb_priority<1>, Ts&&... ds) HB_RETURN
   (Type *, src.copy (this, hb_forward<Ts> (ds)...))
```

Makes this compile warning

```
In file included from hb.hh:610,
                 from hb-aat-layout.cc:28:
hb-array.hh: In instantiation of ‘hb_array_t< <template-parameter-1-1> >::operator T*() const [with T = hb_array_t<const OT::IntType<short unsigned int, 2> >; Type = const OT::IntType<short unsigned int, 2>]’:
hb-serialize.hh:391:61:   required from ‘Type* hb_serialize_context_t::copy(const Type&, Ts&& ...) [with Type = hb_array_t<const OT::IntType<short unsigned int, 2> >; Ts = {}]’
hb-ot-layout-gpos-table.hh:547:5:   required from ‘void OT::SinglePosFormat1::serialize(hb_serialize_context_t*, Iterator, OT::ValueFormat) [with Iterator = hb_zip_iter_t<hb_map_iter_t<hb_filter_iter_t<OT::Coverage::iter_t, const hb_set_t&, const<unnamed struct>&, 0>, const hb_map_t&, hb_function_sortedness_t::RETAINS_SORTING, 0>, hb_repeat_iter_t<hb_array_t<const OT::IntType<short unsigned int, 2> > > >; typename hb_enable_if<hb_is_iterator_of<Lhs, typename Lhs::item_t>::value>::type* <anonymous> = 0]’
hb-ot-layout-gpos-table.hh:721:13:   required from ‘void OT::SinglePos::serialize(hb_serialize_context_t*, Iterator, OT::ValueFormat) [with Iterator = hb_zip_iter_t<hb_map_iter_t<hb_filter_iter_t<OT::Coverage::iter_t, const hb_set_t&, const<unnamed struct>&, 0>, const hb_map_t&, hb_function_sortedness_t::RETAINS_SORTING, 0>, hb_repeat_iter_t<hb_array_t<const OT::IntType<short unsigned int, 2> > > >; typename hb_enable_if<hb_is_iterator_of<Lhs, typename Lhs::item_t>::value>::type* <anonymous> = 0]’
hb-ot-layout-gpos-table.hh:754:3:   required from ‘void OT::SinglePos_serialize(hb_serialize_context_t*, Iterator, OT::ValueFormat) [with Iterator = hb_zip_iter_t<hb_map_iter_t<hb_filter_iter_t<OT::Coverage::iter_t, const hb_set_t&, const<unnamed struct>&, 0>, const hb_map_t&, hb_function_sortedness_t::RETAINS_SORTING, 0>, hb_repeat_iter_t<hb_array_t<const OT::IntType<short unsigned int, 2> > > >]’
hb-ot-layout-gpos-table.hh:571:56:   required from here
hb-array.hh:99:56: error: cannot convert ‘const OT::IntType<short unsigned int, 2>* const’ to ‘hb_array_t<const OT::IntType<short unsigned int, 2> >*’ in return
   99 |   template <typename T> operator T * () const { return arrayZ; }
      |                                                        ^~~~~~
      |                                                        |
      |                                                        const OT::IntType<short unsigned int, 2>* const
```

**Comment by behdad** [comment]
I feel like I can debug this for you.  Can you rebase in master and produce a branch that fails to compile, so I can dig in?  Ideally with small incremental commits and last one failing.  Thanks!

**Comment by ebraminio** [comment]
Current patch is small and merge-able with master, I just can't rename it
to copy and make it recursive, but it seems to me is hard to do. Thanks

**Comment by behdad** [comment]
Fine. Merged. :)  Make a PR for the rename?

**Comment by behdad** [comment]
You're missing prioritization at least.  I'm sure it's workable.

**Pull request merged**
