### PR TITLE
[subset] Add "--name-languages" and "--name-legacy" options

### PR DESCRIPTION
**Pull request by qxliu76**
Make name table subsetting consistent with fontTools

### CODE REVIEW

**Comment by ebraminio** [comment]
Thanks!

**Comment by ebraminio** [comment]
So this was basically the same as #2119? (for the future referenced it was reviewed there). I just am not sure why 12 bots were failing on https://github.com/harfbuzz/harfbuzz/commit/fd85818b5b85fb0ad2db71c60e94ca0689d38bca but not on its parent https://github.com/harfbuzz/harfbuzz/commit/c370da45ff0dd64c2868be313e640272931cffed Sorry for the trouble.

**Comment by ebraminio** [comment]
Hmmm, for some reasons it will fail only if is merged, WEIRD!

**Comment by qxliu76** [comment]
> Hmmm, for some reasons it will fail only if is merged, WEIRD!

Is it still failing now?

**Comment by ebraminio** [comment]
OK, now I see. Guess you didn't rebase the patches that's why it fails when is merged. It fails locally also like this,

```
-drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix
b''fonttools ttx expected/japanese/Mplus1p-Regular.default.25771.ttf
b''fonttools ttx /tmp/tmpro8mpva6/Mplus1p-Regular.default.25771.ttf-subset.ttf
b''stripping checksums.
--- 
+++ 
@@ -883,24 +883,6 @@
   </glyf>
 
   <name>
-    <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus 1p
-    </namerecord>
-    <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Regular
-    </namerecord>
-    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      1.061g;GoogleFonts;Mplus1p-Regular
-    </namerecord>
-    <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus 1p
-    </namerecord>
-    <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Version 1.061
-    </namerecord>
-    <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus1p-Regular
-    </namerecord>
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
       Copyright 2016 The M+ Project Authors.
     </namerecord>
ERROR: ttx for expected and actual does not match.
Test State:
  test.unicodes	    25771/Mplus1p-Regular.default.25771.ttf
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmp8x8g8bru/Mplus1p-Regular.drop-hints.660E.ttf-subset.ttf --unicodes=660E --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.660E.ttf
b''fonttools ttx /tmp/tmp8x8g8bru/Mplus1p-Regular.drop-hints.660E.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmp7xuyviic/Mplus1p-Regular.drop-hints.61,63,65,6B.ttf-subset.ttf --unicodes=61,63,65,6B --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.61,63,65,6B.ttf
b''fonttools ttx /tmp/tmp7xuyviic/Mplus1p-Regular.drop-hints.61,63,65,6B.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmphzrb_qyz/Mplus1p-Regular.drop-hints.660E,6975,73E0,5EA6,8F38,6E05.ttf-subset.ttf --unicodes=660E,6975,73E0,5EA6,8F38,6E05 --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.660E,6975,73E0,5EA6,8F38,6E05.ttf
b''fonttools ttx /tmp/tmphzrb_qyz/Mplus1p-Regular.drop-hints.660E,6975,73E0,5EA6,8F38,6E05.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmpyjcffkzi/Mplus1p-Regular.drop-hints.3042,3044,3046,3048,304A,304B.ttf-subset.ttf --unicodes=3042,3044,3046,3048,304A,304B --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.3042,3044,3046,3048,304A,304B.ttf
b''fonttools ttx /tmp/tmpyjcffkzi/Mplus1p-Regular.drop-hints.3042,3044,3046,3048,304A,304B.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmp36_i2mut/Mplus1p-Regular.drop-hints.3042,3044,3046,73E0,5EA6,8F38.ttf-subset.ttf --unicodes=3042,3044,3046,73E0,5EA6,8F38 --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.3042,3044,3046,73E0,5EA6,8F38.ttf
b''fonttools ttx /tmp/tmp36_i2mut/Mplus1p-Regular.drop-hints.3042,3044,3046,73E0,5EA6,8F38.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmpylt5mtm8/Mplus1p-Regular.drop-hints.1D715,1D7D8,41,42.ttf-subset.ttf --unicodes=1D715,1D7D8,41,42 --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.1D715,1D7D8,41,42.ttf
b''fonttools ttx /tmp/tmpylt5mtm8/Mplus1p-Regular.drop-hints.1D715,1D7D8,41,42.ttf-subset.ttf
b''stripping checksums.
../../../util/hb-subset --font-file=./fonts/Mplus1p-Regular.ttf --output-file=/tmp/tmp87tdm866/Mplus1p-Regular.drop-hints.25771.ttf-subset.ttf --unicodes=25771 --drop-tables+=DSIG,GPOS,GSUB,GDEF --drop-tables-=sbix --no-hinting
b''fonttools ttx expected/japanese/Mplus1p-Regular.drop-hints.25771.ttf
b''fonttools ttx /tmp/tmp87tdm866/Mplus1p-Regular.drop-hints.25771.ttf-subset.ttf
b''stripping checksums.
--- 
+++ 
@@ -218,24 +218,6 @@
   </glyf>
 
   <name>
-    <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus 1p
-    </namerecord>
-    <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Regular
-    </namerecord>
-    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      1.061g;GoogleFonts;Mplus1p-Regular
-    </namerecord>
-    <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus 1p
-    </namerecord>
-    <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Version 1.061
-    </namerecord>
-    <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Mplus1p-Regular
-    </namerecord>
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
       Copyright 2016 The M+ Project Authors.
     </namerecord>
ERROR: ttx for expected and actual does not match.
Test State:/Mplus1p-Regular.drop-hints.25771.ttf
2 test(s) failed.
```

But I am updating the tests https://github.com/harfbuzz/harfbuzz/commit/d1830437c92caf1ba3869c9ddae8acb5f8f96739 so it won't fail. Please just check if that is the expected result. Thanks!

**Comment by qxliu76** [comment]
Yes that's expected. By default we only keep namerecords with"langID=0x0409", so those record with "langID=0x0" are removed. I realized that I had 2 PRs merged so the latter one needs a rebase before merge. Thanks for updating ttf files!

**Pull request merged**
