### PR TITLE
Bump minimum required versions for glib and cairo in configure.ac.

### PR DESCRIPTION
**Pull request by sezero**
Bumps minimum required versions for glib and cairo in configure.ac:
glib2 >= 2.30 is needed for g_unicode_script_from_iso15924() and
g_unicode_script_to_iso15924(), and cairo >= 1.10 is needed for the
new cairo_operator_t members like CAIRO_OPERATOR_SCREEN. It also
defines g_assert_false and g_assert_nonnull for old glib2 versions
in hb-test.h (like it is done for g_assert_true.)

For meson: It doesn't check versions at all. It walks through a lot of
weirdness when a requirement isn't found, so I didn't touch it as I am
not proficient with it.

For cmake: It doesn't check versions at all. It is weirdly written, so
I didn't touch it as I am not very proficient with it..

Reference issue: https://github.com/harfbuzz/harfbuzz/issues/4577
Reference issue: https://github.com/harfbuzz/harfbuzz/issues/4624

CC: @khaledhosny
CC: @lzsiga

### CODE REVIEW

**Review by alerque — APPROVED** [review]
The autoconf bits look good. I'm not qualified to comment on Meson.

**Comment by sezero** [comment]
About meson changes: I have cairo 1.8.8 so it should be rejected, but I get this:
```
Dependency cairo found: NO found 1.8.8 but need: '>= 1.10.0'
Run-time dependency cairo found: NO (tried pkgconfig and cmake)
Run-time dependency cairo-ft found: YES 1.8.8
Run-time dependency cairo found: YES 1.8.8
Dependency cairo-ft found: YES 1.8.8 (cached)
[...]
  Dependencies used for command-line utilities
    Cairo                     : YES
    Chafa                     : NO
```

**Comment by sezero** [comment]
Also of note: `    GObject bindings          : YES`
glib2 and gobject are version 2.28.8 on this setup. glib is rejected but gobject is not?

**Comment by sezero** [comment]
What is left for this to be merged (other than the CI fuzz using an old meson version casing failure)? Cmake side?

**Comment by khaledhosny** [comment]
> What is left for this to be merged (other than the CI fuzz using an old meson version casing failure)? Cmake side?

I’m waiting for this oss-fuzz PR https://github.com/google/oss-fuzz/pull/11697 to get merged to fix the failure here.

**Comment by khaledhosny** [comment]
I reverted the meson requirement change.

**Comment by sezero** [comment]
Will cmake side get any updates? (I can attempt at it, w/o any promises though.)

**Comment by khaledhosny** [comment]
Feel free to work on it of you want, the CMake support is community maintained and I basically just rubber stamp the PRs.

**Pull request merged**
