### PR TITLE
[gpos] in PairPos, always advance next-glyph by one only

### PR DESCRIPTION
**Pull request by behdad**
This goes against the spec.

WIP. Needs comments at least.

https://github.com/harfbuzz/harfbuzz/issues/3824

### CODE REVIEW

**Comment by behdad** [comment]
@jfkthame comments?

**Comment by jfkthame** [comment]
While I think this makes much better sense than the current spec behavior, I'm a bit uneasy about diverging from the other main implementations here. Can we try to get some feedback from Microsoft and Apple to see if they would be willing to consider an actual spec change, and updating their engines to match?

If there's no prospect of the spec and other implementations changing, then I'm leaning (reluctantly) towards saying that interoperability is more important than having improved-but-incompatible behavior for this edge case.

**Comment by behdad** [comment]
Thanks Jonthan. I reported against OpenType. Closing this since I now have an alternate fix for the original issue.

**Comment by behdad** [comment]
Reopening, since in my testing, CoreText implements this behavior.

For test font and further discussion see https://github.com/harfbuzz/harfbuzz/issues/3876

**Pull request closed without merging**
