### PR TITLE
Hash-pin Python dependencies in CI

### PR DESCRIPTION
**Pull request by pnacht**
See #4273.

As described in the issue above, this PR ensures the Python dependencies used in GitHub workflows are immutable.

This is done by creating a `requirements.in` file within the `.ci` directory. This file contains all the dependencies used across the workflows, as defined there. From this file, `pip-compile --generate-hashes .ci/requirements.in` creates a `requirements.txt` file that defines the specific hashes expected for each dependency.

The PR also sets up dependabot to keep these dependencies up-to-date. For an example of how that works, see this dependabot PR on my fork: https://github.com/pnacht/harfbuzz/pull/1.

### CODE REVIEW

**Comment by behdad** [comment]
Thanks!  Looks like glib requires meson >= 0.60.

**Comment by behdad** [comment]
> I just tested a change on my fork and setting meson == 0.60.0 passes all checks. However, some of the workflows are currently running with meson == 0.56.0.
> 
> Would it be okay to upgrade everything to 0.60.0 or would you rather keep the 0.56.0 ones as they are?

Thanks. I don't know the answer. I leave to @khaledhosny to decide.

**Comment by khaledhosny** [comment]
We currently require meson 0.56.0 because it is the earliest version of meson that can build HarfBuzz (earlier versions have bugs that prevented building HarfBuzz) and we try not to use too versions of meson. 0.60.0 was released less than two years ago. I don’t mind myself what version of meson we use.

**Comment by behdad** [comment]
I think it's fine to hashpin to meson 0.60 while leaving the required versions as they are.

**Comment by khaledhosny** [comment]
> I think it's fine to hashpin to meson 0.60 while leaving the required versions as they are.

One reason we pin required version on (some) CI jobs is too avoid accidentally depending on newer meson version (which does happen and gets caught by CI failures).

**Comment by behdad** [comment]
Sigh. Now pip is failing in installing ninja...

**Comment by pnacht** [comment]
Yep, I saw that, have been investigating it. It's some issue with msys2 or mingw32, dunno if those are supported. I'm creating a separate requirements file for fonttools, since that's the only dependency actually used in that workflow. I'm just making sure dependabot is well-behaved with multiple requirements files before pushing the commit here.

**Comment by behdad** [comment]
Thank you. I'm gone using newer meson in CI.

**Comment by pnacht** [comment]
I assume you meant "fine", so just sent a new commit with that change.

**Comment by behdad** [comment]
Thank you!!

**Pull request merged**
