### PR TITLE
Fix collect lookups logic

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes https://crbug.com/oss-fuzz/20021 and https://crbug.com/oss-fuzz/20022

### CODE REVIEW

**Comment by ebraminio** [comment]
@qxliu76 does the change look good? The fact it is not test covered so my change doesn't change anything makes it worrisome :/

**Comment by ebraminio** [comment]
Ok am confident now that is the fix as "Offset to a feature table substitution table, from beginning of the FeatureVariations table." from https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2

**Comment by qxliu76** [comment]
thank you for the fix!

**Comment by ebraminio** [comment]
No problem, please make sure some test will cover it however. Thanks

**Pull request merged**
