### PR TITLE
Add messages for GPOS/GSUB (take 2)

### PR DESCRIPTION
**Pull request by simoncozens**
See feedback in #2261.

### CODE REVIEW

**Comment by justvanrossum** [comment]
Ping @behdad, any chance to get a review on this?

**Comment by behdad** [comment]
Can we take a step back and design this together please?  What I had in mind was that start/end will signify what you'd think of as XML open/close tags.  So to me:
```
start table GSUB
start lookup 10
end lookup 10
end table GSUB
```
will roughly translate to:
```
  <table tag="GSUB">
    <lookup index="10"/>
  </table>
```
The point is, receiving endpoint needs to keep some state.  So repeating the table tag in each lookup line sounds unnecessary to me.  While that info is currently available in `GSUB`/`GPOS` code, note that the `morx` code is shared by `mort` table, so current PR is wrong in that.  `kerx` and `kern` also share code.  I suggest we reduce duplication and rely on client tracking where we are right now than duplicating.

**Comment by behdad** [comment]
Also, eg. any message starting with `start table morx` should only mean one thing: beginning of morx table processing.  Current PR will emit messages like `start table morx chainsubtable %d`.  That's just wrong.

**Comment by simoncozens** [comment]
OK. So how does this sound:

```
start table XXXX
end table XXXX
start lookup NNNN
end lookup NNNN
```

Only question is what to do with morx/kerx. Should we regard their subtables as "lookups"? In OpenType terms that's essentially what they are.

**Comment by simoncozens** [comment]
Linking #2468. With those patches in place, you get a nicely nested "XML tree":

```
trace: start lookup 19	buffer: ...
trace: start lookup 16	buffer: ...
trace: end lookup 16	buffer: ... 
trace: end lookup 19	buffer: ... 
```

**Comment by behdad** [comment]
> Only question is what to do with morx/kerx. Should we regard their subtables as "lookups"? In OpenType terms that's essentially what they are.

I agree in general.  From my debugging experience is obviously revealing what's going on when i trace and see "chain" instead of "lookup".  But your point is valid.  Same as kern subtables.

**Comment by simoncozens** [comment]
I don't mind calling them `chain`.

**Comment by simoncozens** [comment]
OK, with this patch, messages can be:

start/end table  XXXX
start/end lookup NNNN
start/end subtable NNNN (for kerx/kern)
start/end chainsubtable NNNN (for morx)

**Pull request merged**
