### PR TITLE
[ci] Try to fix MSVC build failure

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by behdad** [comment]
Life used to be lighter...

**Comment by khaledhosny** [comment]
> Life used to be lighter...

Indeed. We are supposedly building specific versions of everything to avoid stuff like this, yet the ground keeps changing under our feet!

**Comment by khaledhosny** [comment]
OK, this started failing when GitHub deployed a new virtual environment image, whatever this is seems no have changed something and some meson tool is now silently failing.

**Comment by khaledhosny** [comment]
I give up, the command `meson --internal symbolextractor` is always failing on these CI machines and it does not seem to produce any error messages.

**Comment by khaledhosny** [comment]
I guess we have to wait for this one to fix itself.

**Pull request closed without merging**
