### PR TITLE
Comment out entries in ot_languages where fallback suffices

### PR DESCRIPTION
**Pull request by dscorbett**
Note that this changes the behavior of `hb_ot_tag_to_language` for unknown tags.

### CODE REVIEW

**Comment by behdad** [comment]
> Note that this changes the behavior of `hb_ot_tag_to_language` for unknown tags.

Right...  

I see what you did (assuming it's ISO 639-3 and encoding it as is).  I'm fine with that.  However, wouldn't that fail if there's an existing ISO 639-3 with that code, that maps to some other tag?  You can just try mapping it forward and only do what you're doing if result is consistent.

**Comment by dscorbett** [comment]
I’ll fix it.

**Comment by dscorbett** [comment]
I think it’s fixed now.

**Comment by behdad** [comment]
Thanks.

Humm. I don't see how your new code doesn't have the same problem.  I don't see what you changed actually.

Let's say, `hb_ot_tag_to_language()` called on `ACQ `.  We should NOT return `acq`, since that maps to `ARA `.  How is that handled?

**Comment by dscorbett** [comment]
What I fixed was 'ALT ' and 'HND '. They correspond to the BCP 47 tags "alt" and "hnd", so they are commented out of `ot_languages`. "atv" and "hno" also correspond to 'ALT ' and 'HND ', so 'ALT ' and 'HND ' were therefore converted to "atv" and "hno". The fix was to add such tags to `hb_ot_ambiguous_tag_to_language`.

'ACQ ' will indeed not round-trip properly. I think that is okay since it is not a registered language system tag.

**Comment by behdad** [comment]
> 'ACQ ' will indeed not round-trip properly. I think that is okay since it is not a registered language system tag.

Right.  But you just need to one `if (hb_ot_tag_from_languge (...) == ...) return` to fix that.  Right?

**Comment by behdad** [comment]
In the end no one cares, so maybe just add a comment and we're done here.  Thanks!

**Comment by dscorbett** [comment]
I’ve added a comment.

**Comment by behdad** [comment]
Thank you.

**Pull request merged**
