### PR TITLE
Sanitize barrier properly

### PR DESCRIPTION
**Pull request by behdad**
I'm sure I've forgot some. But this is a good start.

Fixes https://github.com/harfbuzz/harfbuzz/issues/4478

### CODE REVIEW

**Comment by behdad** [comment]
CircleCI bot roll forward was because the `asan-ubsan` bot compiler was crashing.

**Comment by behdad** [comment]
@khaledhosny Can I get some help from you with the bots? I don't know what's going on.

**Comment by khaledhosny** [comment]
> @khaledhosny Can I get some help from you with the bots? I don't know what's going on.

Looks like the job is getting killed because it is stuck (or at least that is what the runnuer thinks). Dropping the `-j9` or using a less number of parallel jobs might help. You can also rerurn the job with ssh access to debug directly on the remote machine.

**Comment by khaledhosny** [comment]
But something is making these jobs much slower than before, may be a compiler bug?

**Comment by behdad** [comment]
> But something is making these jobs much slower than before, may be a compiler bug?

That's my feeling.  Both get stuck linking `test/threads/hb-subset-threads`.

**Review by khaledhosny — APPROVED** [review]

**Pull request merged**
