### PR TITLE
Check input info length when assigning next glyph

### PR DESCRIPTION
**Pull request by drott**
Fixes oss-fuzz:28234 but needs further review and approval from someone
who knows this code better.

### CODE REVIEW

**Comment by behdad** [comment]
Please put the full issue URL (even for our own issues) in the commit log.  Also, please include your assessment of what the problem is. For example, here's two excellent reports by someone new to the project:

https://github.com/harfbuzz/harfbuzz/issues/2501
https://github.com/harfbuzz/harfbuzz/issues/2493

The change doesn't look right to me. `idx < len` shall hold always when `next_glyph()` is called. So we need to figure out why we get into a position that this is violated.

**Comment by drott** [comment]
Yes, sorry, this was a bit brief and incomplete. I don't have the full analysis yet - my intention was to nudge and start a discussion on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28234 - as this issue has been reported early in December and has not been picked up so far. 

Unfortunately, I am not sure which of the allocations fails yet, but it looks like at the point in question, `len` may not be in sync with the length of `info`. I tried setting a breakpoint in `rr` on the `mov 0x0, %eax` instruction of all the allocation `hb_*alloc` functions (i.e. the case when they return `nullptr`) after building `hb-shape-fuzzer` with `-DHB_CUSTOM_MALLOC` but those did not get hit and the build was not build with `llvm` and not with `-fsanitize`. Is there an easy way to locally build with `libFuzzer` and the MSAN or other sanitisation options?

**Comment by behdad** [comment]
I haven't built any of that myself. Let's see if @ebraminio can help in.

**Comment by ebraminio** [comment]
`CXXFLAGS="-fsanitize=address,fuzzer-no-link" meson fuzzbuild --default-library=static -Dfuzzer_ldflags="-fsanitize=address,fuzzer" -Dexperimental_api=true && ninja -C fuzzbuild test/fuzzing/hb-{shape,draw,subset,set}-fuzzer && fuzzbuild/test/fuzzing/hb-shape-fuzze YOURTESTCASE` this builds with failing alloc

**Comment by behdad** [comment]
This *should* be fixed by the audit I did a couple weeks ago.

**Comment by behdad** [comment]
Yep. Status of referenced oss-fuzz issue is Verified.

**Comment by drott** [comment]
Thanks for the follow-up.

**Pull request closed without merging**
