### PR TITLE
Simplify 'using' statements in namespace 'OT::Layout'.

### PR DESCRIPTION
**Pull request by ascherer**
Just an observation.

### CODE REVIEW

**Comment by ascherer** [comment]
Just another observation.

**Comment by behdad** [comment]
This was changed to current way to fix gcc <= 7 build apparently.

**Comment by kleisauke** [comment]
FWIW, this change should probably be fine with GCC < 7. I also tried this initially, but some files expect `PosLookup` and `SubstLookup` to be present within the `OT` namespace (hence the CI failures on this PR).

**Comment by ascherer** [comment]
That was my second observation above. The use of `OT::SubstLookup` appears in files that seem to date prior to sub-namespaces `Layout` and `GSUB`(`_impl`). In the new version **5.0.1** the code base is somewhat cleaner in this respect. Thanks!

(Apart from observing compilation and use of Harfbuzz in the TeX Live code base – which broke hard four weeks ago with **GCC 5** and **GCC 6** –, I'm not invested in this software.)

**Pull request closed without merging**
