### PR TITLE
libpng.wrap: update to 1.6.37

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by khaledhosny** [comment]
This breaks building Cairo subproject.

**Review by khaledhosny — CHANGES_REQUESTED** [review]
This breaks building Cairo subproject.

**Comment by alatiera** [comment]
ah indeed, didn't notice harfbuzz was still pointing at a fork.

The meson port got merged upstream and we also updated libpng in cairo yday. 

I added a commit to switch cairo and fontconfig wraps to the upstream repos.

**Comment by alatiera** [comment]
blah, cairo from git looks like it requires meson 0.54+ which breaks the win32 build.

```
subprojects/cairo/meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >= 0.54.0
```

**Comment by khaledhosny** [comment]
For Cairo see #2700.

**Comment by alatiera** [comment]
indeed, maybe @xclaesse  could bump libpng and included in #2700

**Comment by alatiera** [comment]
Now part of #2700

**Pull request closed without merging**
