### PR TITLE
[fuzz] Fix oss-fuzz/16639

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes https://crbug.com/oss-fuzz/16639

### CODE REVIEW

**Comment by ebraminio** [comment]
I think we had some idiom to avoid manual freeing of blob but I don't remember where it was and whether works with hb_blob_t

**Comment by behdad** [comment]
lgtm.

**Comment by ebraminio** [comment]
PTAL again, disallowed a subset much bigger than the table itself as to msan failure and https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/26913998/job/lkp2osx2l5fwwkd8#L1563

**Comment by behdad** [comment]
How do a leak fix and some other fix belong to the same PR?

**Comment by ebraminio** [comment]
Both revealed by the same test case. Ok should investigate more

**Pull request merged**
