### PR TITLE
Remove unnecessary check in hb_buffer_t::set_masks.

### LINKED ISSUE #2073: Unnecessary check in hb_buffer_t::set_masks?
In [hb_buffer_t::set_masks](https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-buffer.cc#L430) we have this check:

https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-buffer.cc#L441

But `hb_buffer_t::set_masks` used only once in [hb_ot_shape_setup_masks](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape.cc#L727) and we already filtered this case there:

https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-ot-shape.cc#L740

Should we remove it and maybe add an `assert`?

PS: and probably, we should use `UINT_MAX` or `HB_FEATURE_GLOBAL_END` instead of `(unsigned int)-1`.

### PR DESCRIPTION
**Pull request by RazrFalcon**
Bounds are already checked by the caller.

Closes #2073

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Not sure what's wrong with `clang-tsan`. There is a timeout error, but this change should not cause it.

**Comment by RazrFalcon** [comment]
Looks like my other pull requests are failed with the same error, so this probably `clang-tsan` error and not the code related bug.

**Comment by behdad** [comment]
@ebraminio can you look into increasing timeout for tsan, other sans?

**Comment by ebraminio** [comment]
Ok https://github.com/harfbuzz/harfbuzz/commit/80762cc4d0663a9ca465e94e73424e3b352de24c

**Pull request merged**
