### PR TITLE
[cmake] Add header existence tests

### PR DESCRIPTION
**Pull request by ebraminio**
Hmm, but why isatty is detected on macOS but couldn't be used?

### CODE REVIEW

**Comment by ebraminio** [comment]
Similar goes to sys/mman.h, why cmake detects it on macOS but can't use it?

**Comment by ebraminio** [comment]
Lots of CI breakage, help please!

**Comment by khaledhosny** [comment]
I’m afraid I don’t know enough of CMake to be of any help here.

**Comment by ebraminio** [comment]
No problem Khaled. I will try to sort it out somehow :) It is so weird, something interesting going on perhaps

**Pull request merged**
