### PR TITLE
Remove cmake-config support of HarfBuzz

### PR DESCRIPTION
**Pull request by ebraminio**
Reverts d38f37b2 as discussed in #2316

### CODE REVIEW

**Comment by lisyarus** [comment]
Maybe it would be a good idea to wait for @mathstuf's comment on this?

**Comment by ebraminio** [comment]
> Maybe it would be a good idea to wait for @mathstuf's comment on this?

Best idea, no rush at all.

**Comment by mathstuf** [comment]
Seems like a clean removal of the CMake config support to me.

**Comment by ebraminio** [comment]
@mathstuf, @lisyarus: Thank you so much :)

**Pull request merged**
