### PR TITLE
[ci] Switch msys2 bot to meson

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
@lazka I think I need your help here, I want to use meson in our msys2 bot, and currently I couldn't https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/32289790#L204

Basically what we have right now is:
```
pacman --noconfirm --force -S --needed mingw-w64-$MSYS2_ARCH-{gcc,freetype,cairo,icu,gettext,gobject-introspection,gcc,gcc-libs,glib2,graphite2,pkg-config,python3,python3-pip,ragel,meson,ninja}"
pip install fonttools
PATH=$PATH:/mingw64/bin:/mingw32/bin; meson build --wrap-mode=nofallback -Dfreetype=enabled -Dglib=enabled -Dcairo=enabled -Dgobject=enabled -Dgdi=enabled -Ddirectwrite=enabled && ninja -Cbuild test
```

But it can't find freetype, we used to pass `--host=x86_64-w64-mingw32 --prefix=/mingw64` but meson's cross compile feels needs `--cross-file`, is there any shortcut for this other than adding one file to the project?

**Comment by lazka** [comment]
The key issue is that you have to set MSYSTEM=MINGW64 and then the login shell should set all env vars for you and you don't have to pass any prefixes etc. You can also do `set CHERE_INVOKING=yes` so the working directory isn't changed when running bash.

**Comment by lazka** [comment]
(I can have a look myself if you want, but not sure when I have time)

**Comment by ebraminio** [comment]
> The key issue is that you have to set MSYSTEM=MINGW64 and then the login shell should set all env vars for you and you don't have to pass any prefixes etc.

Thanks has fixed my issue, I didn't know that at all :)

> (I can have a look myself if you want, but not sure when I have time)

Oh nooo, I just want to have your need in our CI so we won't regress all your efforts in future :)

`meson build --wrap-mode=nofallback -Dfreetype=enabled -Dglib=enabled -Dcairo=enabled -Dgobject=enabled -Dgdi=enabled -Ddirectwrite=enabled -Dgraphite=enabled && ninja -Cbuild test`

https://github.com/harfbuzz/harfbuzz/pull/2350/files#diff-180360612c6b8c4ed830919bbb4dd459R46

Hopefully that matches with msys2 project need, and oh, I have to give this another try https://github.com/Alexpux/mingw-w64/pull/5 to make our dwrite need resolved from msys2 side.

**Comment by lazka** [comment]
> > The key issue is that you have to set MSYSTEM=MINGW64 and then the login shell should set all env vars for you and you don't have to pass any prefixes etc.
> 
> Thanks, that has fixed my issue, I didn't know that at all :)

yeah, we need to document that better. good thing is we have a new website now which should make things easier.

I've ported our msys2 package already using current master, and things look fine so far: https://github.com/msys2/MINGW-packages/commits/harfbuzz-meson

Once there is a new release I'll switch our packaging over.

**Comment by ebraminio** [comment]
After lots of trial and error 😅
Thank you @lazka ! :)

**Pull request merged**
