### PR TITLE
[sanitize] Try a barrier

### PR DESCRIPTION
**Pull request by behdad**
Not sure it works.

To fix https://github.com/harfbuzz/harfbuzz/issues/4478

### CODE REVIEW

**Comment by behdad** [comment]
This makes the code size grow by about 1%; which makes me think it's doing its job...

**Comment by behdad** [comment]
Humm, compiler crash in the `asan+ubsan` bug :(
https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/7735/workflows/43c7f1fc-b0b9-459e-9c4f-763f8027762b/jobs/213155

**Comment by garretrieger** [comment]
Unfortunately this doesn't resolve the crash I'm getting. Where-as adding:

(_hb_memory_r_barrier (), true) &&

In between the sanitize and the data access does work for me.

**Comment by behdad** [comment]
> (_hb_memory_r_barrier (), true) &&
> 
> In between the sanitize and the data access does work for me.

Yeah that's what I was afraid of, that we have to audit all sanitize() methods and adjust.

**Comment by behdad** [comment]
Proper fix in https://github.com/harfbuzz/harfbuzz/pull/4480

**Pull request closed without merging**
