### PR TITLE
[draw] Move outline draw API behind HB_EXPERIMENTAL_API directive

### PR DESCRIPTION
**Pull request by ebraminio**
Just to have a one-click away patch to disable the API.

### CODE REVIEW

**Comment by behdad** [comment]
I'm fine having a `HB_EXPERIMENTAL_API` in general...

**Comment by ebraminio** [comment]
Let's close this, better to discuss on #2145 anyway, can be revived and merged when needed.

**Comment by ebraminio** [comment]
Update this.

Behdad please have a look at the API and things I tried to aggregate on #2145, if you are still unsure about the and like to have a release, feel free to have this merged. Thanks!

**Comment by ebraminio** [comment]
Move it behind the flag as the apparently top release blocker

**Pull request merged**
