### PR TITLE
Load DirectWrite dynamically

### PR DESCRIPTION
**Pull request by lb90**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3478

### CODE REVIEW

**Comment by lb90** [comment]
extern "C" shouldn't really matter, do you prefer to have it removed?

**Comment by behdad** [comment]
Oh, because it's just a typedef.

**Comment by lb90** [comment]
> We should also remove the -ldwrite from Makefile.am and meson.build.

Right! Should be OK now

**Comment by lb90** [comment]
Looks like [UuicCreate](https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidcreate) is only used in `hb-uniscribe.cc`:

    $ grep -r --exclude-dir=".git" UuidCreate
    perf/texts/en-words.txt:UuidCreate
    src/hb-uniscribe.cc:  UuidCreate ((UUID*) &id);

It's also the only function imported from `rpcrt4.lib`:

    RPCRT4.dll
             2AE6627E8 Import Address Table
             2AE662360 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         22F UuidCreate

So I took the liberty to remove `rpcrt4.lib` from `CMakeLists.txt`, right where it adds dependencies needed for `hb-directwrite.cc`. `rpcrt4` is still linked if Uniscribe/GDI is enabled. Hope it's ok 😄

**Comment by behdad** [comment]
> Looks like [UuidCreate](https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidcreate) is only used in `hb-uniscribe.cc`:

We should actually test if the same code is needed in the directwrite backend, but for now it LGTM.

The issue that solves is this: if someone tries to shape a font with the uniscribe backend and the font has the same name as a font installed on the system, uniscribe will prefer the font installed on the system instead of the font provided. For that reason, we rewrite the font to change the name to an arbitrary UUID so the name is unique.

**Pull request merged**
