### PR TITLE
port instancer solver normalizeValue fixes from fonttools

### PR DESCRIPTION
**Pull request by qxliu76**
This is for #4290 , avar fix will be added later, currently we don't have code for avar yet.

### CODE REVIEW

**Comment by behdad** [comment]
Did you actually port the optimization?
https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6

**Comment by qxliu76** [comment]
> Did you actually port the optimization? [fonttools/fonttools@10bc7a8](https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6)
> 
> This doesn't look like it does anything: [73ce301](https://github.com/harfbuzz/harfbuzz/commit/73ce3015bbaa04ce5a2a9da358e3695c7db10c44)

Yes I think my changes are combination of these 2 commits together:[fonttools/fonttools@10bc7a8](https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6) and https://github.com/fonttools/fonttools/pull/3179/commits/71cca00b05d164fb9ccfb093133f21e8982c7cc9

**Comment by qxliu76** [comment]
ah, you ported some optimization fixes, so my changes are small: https://github.com/harfbuzz/harfbuzz/commit/dbac23357f0ad9cba73965a4a00ca85bf01dcef9

**Comment by behdad** [comment]
> ah, you ported some optimization fixes, so my changes are small: [dbac233](https://github.com/harfbuzz/harfbuzz/commit/dbac23357f0ad9cba73965a4a00ca85bf01dcef9)

I see. Thanks.

**Comment by behdad** [comment]
Humm. I still don't see https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6

**Comment by qxliu76** [comment]
> Humm. I still don't see [fonttools/fonttools@10bc7a8](https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6)

It's covered by this: https://github.com/harfbuzz/harfbuzz/commit/244f3224b9a6e9e22f65796a984ef7058e7af930

**Comment by behdad** [comment]
> > Humm. I still don't see [fonttools/fonttools@10bc7a8](https://github.com/fonttools/fonttools/commit/10bc7a804aa8e840da89a8a09dc12bbef79288e6)
> 
> It's covered by this: [244f322](https://github.com/harfbuzz/harfbuzz/commit/244f3224b9a6e9e22f65796a984ef7058e7af930)

Got it. Thanks.

**Pull request merged**
