### PR TITLE
Make more 'coords' params const.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by behdad** [comment]
How did you notice these ones?

**Comment by waywardmonkeys** [comment]
I ran `clang-tidy` with the `readability-non-const-parameter` check which pointed out a couple of them ... I then manually found the others based on that. That check isn't perfect and sometimes has false positives (which I haven't reported), but it is useful at times!

**Comment by behdad** [comment]
Nice.  Thanks.

**Comment by ebraminio** [comment]
Great. Can you give us exact command you use? I like to integrate it to some bot (just for information). Do you have experience on making `.clangformat` configuration files also?

**Comment by ebraminio** [comment]
There is https://clangformat.com/ also but don't know how to describe the format harfbuzz has, indention with 2 spaces but converting 8 spaces to tabs, are you aware of some project with similar code style having `.clang-format` Behdad?

**Comment by behdad** [comment]
No automatic formatting please.

**Pull request merged**
