### PR TITLE
Reduce complexity

### PR DESCRIPTION
**Pull request by behdad**
I know this is controversial since just renaming files. This change basically renames 'ot-shape-complex' to just 'ot-shaper' for brevity.

### CODE REVIEW

**Review by khaledhosny — APPROVED** [review]

**Comment by khaledhosny** [comment]
My only concern is that commits that fail to build interfere badly with bisecting. Otherwise it is a welcome change, and I personally always disliked the stigma of “complex”.

**Comment by behdad** [comment]
I'll rewrite those commits so it all builds. I agree re complex. That term was from a different era.

**Comment by behdad** [comment]
> I'll rewrite those commits so it all builds.

Done.

**Comment by behdad** [comment]
> My only concern is that commits that fail to build interfere badly with bisecting.

For changes like this I merge with a merge commit, such that bisect sees them as all-or-nothing.

**Comment by behdad** [comment]
> > My only concern is that commits that fail to build interfere badly with bisecting.
> 
> For changes like this I merge with a merge commit, such that bisect sees them as all-or-nothing.

Though maybe this one is better without a merge commit. Higher chance that git can follow the logic.

**Comment by khaledhosny** [comment]
> > My only concern is that commits that fail to build interfere badly with bisecting.
> 
> For changes like this I merge with a merge commit, such that bisect sees them as all-or-nothing.

Interesting, I didn’t know about this behavior of git bisect.

**Comment by khaledhosny** [comment]
We still have `hb_ot_substitute_complex`, `hb_ot_position_complex`, do we want to rename them as well (I’m not sure what complex refers to here). There is also `//Complex shapers` in `hb-subset-input.cc`.

**Comment by khaledhosny** [comment]
I’m updating the documentation to speak less about “complex” shapers/scripts.

**Comment by behdad** [comment]
> We still have `hb_ot_substitute_complex`, `hb_ot_position_complex`, do we want to rename them as well (I’m not sure what complex refers to here). There is also `//Complex shapers` in `hb-subset-input.cc`.

Fixed.

**Comment by behdad** [comment]
> > > My only concern is that commits that fail to build interfere badly with bisecting.
> > 
> > 
> > For changes like this I merge with a merge commit, such that bisect sees them as all-or-nothing.
> 
> Interesting, I didn’t know about this behavior of git bisect.

git-bisect takes the first parent of each commit. Merge commits have multiple parents, typically two. This typically becomes frustrating, when bisect tells you the first bad commit is a merge commit, you are left to your own to then do a separate bisect to find out where in the merged branch the regression was introduced, perhaps by another bisect with a different start point, which would route the bisect path to the merged branch.

**Comment by behdad** [comment]
> git-bisect takes the first parent of each commit. Merge commits have multiple parents, typically two. This typically becomes frustrating, when bisect tells you the first bad commit is a merge commit, you are left to your own to then do a separate bisect to find out where in the merged branch the regression was introduced, perhaps by another bisect with a different start point, which would route the bisect path to the merged branch.

Looks like I'm wrong, and that's the behavior only if you specify `--first-parent`.

https://git-scm.com/docs/git-bisect#Documentation/git-bisect.txt---first-parent

What I said is still valid, I think, if the merged branch started its life before the starting point of the bisect (which is not the case for short-lived branches).

**Comment by khaledhosny** [comment]
I see, thanks!

**Pull request merged**
