### PR TITLE
[subset] fix memory leak when map insert fails.

### PR DESCRIPTION
**Pull request by garretrieger**

### CODE REVIEW

**Comment by behdad** [comment]
Wish we could mark this and previous similar change to be reverted when we add proper lifetime-tracking to our hashmap.

LGTM. Thanks.

**Comment by behdad** [comment]
Then we can / should insert a reference-wrapper into the hashmap instead of raw pointers.

**Comment by behdad** [comment]
Also, we can make `set()` return bool. Sounds nicer.

**Comment by garretrieger** [comment]
sounds good.

**Pull request merged**
