### PR TITLE
[aat] Correct array indexing when looking up actions in KerxSubTableFormat4

### PR DESCRIPTION
**Pull request by jfkthame**
Fixes https://github.com/harfbuzz/harfbuzz/issues/2531.

### CODE REVIEW

**Comment by behdad** [comment]
Thanks!

How about changing `ankr_data` to `hb_pair_t<HBUINT16, HBUINT16>? Then instead of `check_array` just do a `check_struct`.

The two `HB_UNUSED` near the first block your are touching can also be removed.

**Comment by behdad** [comment]
LGTM otherwise.

**Comment by jfkthame** [comment]
> Thanks!
> 
> How about changing `ankr_data` to `hb_pair_t<HBUINT16, HBUINT16>? Then instead of `check_array`just do a`check_struct`.

I wondered about changing the type there, but wasn't sure it was worth it for something just used in the one place. Changing the type of the KerxSubTableFormat4::ankrData field isn't entirely satisfactory, because it's not always an array of pairs of uint16 ... in the case where action_type is 3, there are 4 values per action entry.

Which, now that I look at it, means that code fragment is also wrong; it needs a `* 4` inserted. I guess we don't have any test coverage here... :(

**Comment by behdad** [comment]
Thanks. I'll touch up later.

**Comment by behdad** [comment]
I'm on phone. Feel free to merge.

**Pull request merged**
