### PR TITLE
[fuzz] Add oss-fuzz/16810 testcase

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes https://crbug.com/oss-fuzz/16810

### CODE REVIEW

**Comment by ebraminio** [comment]
While having this makes sense but what if we unlimited number of other tables, two additional things we can have instead or in addition to this,

* Disallowing duplicated tables at all, as we have lsearch https://github.com/harfbuzz/harfbuzz/blob/27de7c44fe80e69c527578c99c26280ba9f26c15/src/hb-face.cc#L671 anyway
* Limiting number of table a font can have

**Comment by behdad** [comment]
First, explain what's happening.

**Comment by behdad** [comment]
How can a font insert unlimited tables??????

**Comment by ebraminio** [comment]
This is the font that causing issue,

```
Opened font file test/fuzzing/fonts/clusterfuzz-testcase-minimized-hb-subset-fuzzer-5675720390475776: 299037 bytes long
OpenType font with TrueType outlines
1 font(s) found in file
Font 0 of 1:
  8224 table(s) found in font
  Table  0 of 8224:      (0x20202020+0xff202020)
  Table  1 of 8224:      (0x20202020+0x20202020)
  Table  2 of 8224:      (0x20202020+0x20202020)
  Table  3 of 8224:      (0x20202020+0x20202020)
  Table  4 of 8224: �    (0x20202020+0x00000678)
  Table  5 of 8224:  (0x00070007+0x000007b6)
  Table  6 of 8224:  (0x196f93e4+0x000000ec)
  Table  7 of 8224:  (0x0229cc7d+0x00000590)
  Table  8 of 8224:  (0x0d73047a+0x000005f4)
  Table  9 of 8224:  (0x35c3ff51+0x000005c8)
  Table 10 of 8224:  (0x05d806a4+0x000005f8)
  Table 11 of 8224:  (0x001700a9+0x00000558)
  Table 12 of 8224:  (0x0523a5fc+0xd805806f)
  Table 13 of 8224: O_iW (0x8ed4f8e2+0xbe4ab39c)
  Table 14 of 8224: ��y� (0xabfec1fe+0xf4c0000a)
  Table 15 of 8224: �� (0x00010000+0x000a004e)
  Table 16 of 8224:  (0x000e0500+0x00000000)
  Table 17 of 8224:  (0x00180000+0xff0a0004)
  Table 18 of 8224:  (0x0000ffff+0x00040001)
  Table 19 of 8224:  (0x00000000+0xffff0003)
  Table 20 of 8224:  (0x6de8796d+0x0d796170)
  Table 21 of 8224: osta (0x796d0066+0x3c000000)
  Table 22 of 8224:  (0x00032400+0x03000100)
  Table 23 of 8224:  (0x22000200+0x0300ffff)
  Table 24 of 8224: � (0x03000500+0x0a000200)
  Table 25 of 8224:  (0x00000100+0x00000a00)
  Table 26 of 8224: $ (0x32000e6d+0x6c796d00)
  Table 27 of 8224:  (0xff000100+0x0000019c)
  Table 28 of 8224: ��� (0x01000000+0x01000400)
  Table 29 of 8224:  (0x01001200+0x04000000)
  Table 30 of 8224:  (0x2c000201+0x01000727)
  Table 31 of 8224: 
 (0x6400e806+0xff000100)
  Table 32 of 8224: 
�� (0x64000100+0x00000a00)
  Table 33 of 8224: N (0x32000e05+0x00000000)
  Table 34 of 8224:  (0x20001800+0x00ff0a00)
  Table 35 of 8224:  (0x060000ff+0xff000400)
  Table 36 of 8224:  (0x04000000+0x00ffff00)
  Table 37 of 8224:  (0x08616b68+0x6e003363)
  Table 38 of 8224: cwp (0x66003e70+0x72656600)
  Table 39 of 8224: Dts3 (0x0f232203+0xba7881f1)
  Table 40 of 8224: ͸�� (0x3fbda176+0xbc64ae01)
  Table 41 of 8224: <�$ (0xfcd80580+0x6f4f5f69)
  Table 42 of 8224: W��I (0xe2be4ab3+0x9ca6c379)
  Table 43 of 8224: �� (0xfef4c0fe+0xd76801c7)
  Table 44 of 8224: ��m_ (0xff01fdaa+0x04bb0090)
  Table 45 of 8224: � (0x06011416+0x33323635)
  Table 46 of 8224: 4'7 (0x22263534+0xfdbe980c)
  Table 47 of 8224: lggl (0x5252c606+0x8b1c2d37)
  Table 48 of 8224: bccb (0x4098b1b1+0x98470000)
  Table 49 of 8224: �� (0x068b0226+0x00010000)
  Table 50 of 8224:  (0xffff0050+0xffe80673)
  Table 51 of 8224:  �& (0x00070004+0x05e30000)
  Table 52 of 8224:  (0xe56e0024+0x00000706)
  Table 53 of 8224: 4 (0x26272626+0x35341237)
  Table 54 of 8224: 3�y� (0xfd2d666f+0x6e6e6170)
  Table 55 of 8224: a0m (0x29423e2b+0x4e4abb52)
  Table 56 of 8224: M$=0 (0xb3d00689+0x1e21666d)
  Table 57 of 8224: lkF� (0x77011180+0x89ee874f)
  Table 58 of 8224: ��{u (0xc1a12627+0x0001005a)
  Table 59 of 8224: ��� (0x00000102+0x11141633)
  Table 60 of 8224: 27 (0x34121302+0x03f6869c)
  Table 61 of 8224: 8DP (0x7c046efd+0xedfe35c3)
  Table 62 of 8224: �
                     �
                       (0x01e50121+0x00040050)
  Table 63 of 8224: ��- (0x70610046+0x004e0000)
  Table 64 of 8224: 66 (0x00071633+0x32003534)
  Table 65 of 8224: &'7 (0x07112127+0x01363726)
  Table 66 of 8224: '#" (0x12333201+0x36123534)
  Table 67 of 8224: &#" (0x26232286+0x15141216)
  Table 68 of 8224: 327& (0x06070117+0x3e332103)
  Table 69 of 8224: ";�N (0x3c38ec01+0x80ff4a8e)
  Table 70 of 8224: ^_PX (0x89466185+0x6586a4ce)
  Table 71 of 8224: �Ȭ� (0x778d8773+0x778c86fc)
  Table 72 of 8224: Eg|� (0x38858404+0x12d3c6fd)
  Table 73 of 8224: �Z� (0x3030fe34+0x26232206)
  Table 74 of 8224:  (0x15141216+0x33323726)
  Table 75 of 8224: 54 (0x3e332103+0x223b894e)
  Table 76 of 8224: �茁 (0x80ff4a8e+0x5e5f5858)
  Table 77 of 8224: ~ (0x6586a4ce+0xfec8acf3)
  Table 78 of 8224: Ɂ{ (0x778c86fc+0x45677c90)
  Table 79 of 8224: )�C (0x12d3c6fd+0xac015aac)
  Table 80 of 8224: �* (0xdfa8fedd+0x5f0a011e)
  Table 81 of 8224: �t�Y (0x9095ef5a+0x000003e8)
  Table 82 of 8224: 3 (0x46d30c00+0x00000000)
  Table 83 of 8224:  (0xfeeb02b9+0x4ab39e9c)
  Table 84 of 8224: �� (0x8efce913+0x10285804)
  Table 85 of 8224: (0xfdd702aa+0x14062322)
  Table 86 of 8224: &188 (0x5a29423e+0x2b4e4abb)
  Table 87 of 8224: RM$= (0xaa0687a7+0xc31e2ac8)
  Table 88 of 8224: fsE� (0x84fe8000+0x761178b0)
  Table 89 of 8224: ��{u (0xc3aaa7c3+0x06891e2a)
  Table 90 of 8224: �fsE (0x59770111+0x8089ee87)
  Table 91 of 8224: O��{ (0x00200100+0x00000e00)
  Table 92 of 8224: � (0x46002200+0x3bff0007)
  Table 93 of 8224: � (0x535abe3f+0xe4000007)
  Table 94 of 8224: � (0x42a95ce0+0xf3000008)
  Table 95 of 8224: \�?� (0x327703f2+0x7b000006)
  Table 96 of 8224: � (0x700d5b1a+0xc8000006)
  Table 97 of 8224: x (0x70000700+0x07000007)
  Table 98 of 8224: � (0x66196f93+0xe4000000)
  Table 99 of 8224: � (0x64027f9d+0x7fa47fa8)
  Table 100 of 8224: �� (0x7fbd7fc1+0x7fc57fcc)
  Table 101 of 8224: �� (0x7ff07ff3+0x7ffb8000)
  Table 102 of 8224: �
                      � (0x80178033+0x8036803b)
  Table 103 of 8224: �=�F (0x80568058+0x805a805e)
  Table 104 of 8224: �a�o (0x8076807d+0x80848089)
  Table 105 of 8224: ���� (0x809d80a1+0x80a580a9)
  Table 106 of 8224: ���� (0x80c380c6+0x80cc80ce)
  Table 107 of 8224: �ր� (0x80e480ef+0x80f180f4)
  Table 108 of 8224: ���� (0x810a811a+0x8129812f)
  Table 109 of 8224: �1�3 (0x814b814e+0x81508153)
  Table 110 of 8224: �e�k (0x8178817f+0x81828188)
  Table 111 of 8224: ���� (0x819c81a0+0x81a381a8)
  Table 112 of 8224: ���� (0x81c281c6+0x81c981cd)
  Table 113 of 8224: �с� (0x81e381e5+0x81e881ea)
  Table 114 of 8224: ��� (0x82058207+0x820c820e)
  Table 115 of 8224: �� (0x821e822a+0x822e8233)
  Table 116 of 8224: �5�9 (0x8258825f+0x82648266)
  Table 117 of 8224: �h�k (0x82768278+0x827e828b)
  Table 118 of 8224: ���� (0x82a582ad+0x82af82b1)
  Table 119 of 8224: ���� (0x82c582d1+0x82d382d7)
  Table 120 of 8224: �ۂ� (0x82f182f4+0x82fa8302)
  Table 121 of 8224: ��	 (0x831c8328+0x832b8332)
  Table 122 of 8224: �6�8 (0x8349834f+0x83528358)
  Table 123 of 8224: �w�{ (0x83a283ab+0x83b183c5)
  Table 124 of 8224: �ʃ� (0x83d683dc+0x83df83e9)
  Table 125 of 8224: ��� (0x840e8413+0x84208429)
  Table 126 of 8224: �,�1 (0x844e8457+0x845b8461)
  Table 127 of 8224: �c�f (0x8475847a+0x848b8490)
  Table 128 of 8224: ���� (0x84a184b2+0x84b884bb)
  Table 129 of 8224: ���� (0x84d184da+0x84ec84ee)
  Table 130 of 8224: ��� (0x8517851a+0x8526852d)
  Table 131 of 8224: �5�= (0x8548854e+0x85578568)
  Table 132 of 8224: �m�~ (0x8587858a+0x85948597)
  Table 133 of 8224: ���� (0x0001fb01+0x29000008)
  Table 134 of 8224: GSUB (0x0000001a+0x003a0001)
    0 script(s) found in table
    0 feature(s) found in table
    0 lookup(s) found in table
  Table 135 of 8224:  (0x00016466+0x6c740008)
  Table 136 of 8224:  (0x00100000+0x11000d00)
  Table 137 of 8224: (0x06000a00+0x02000600)
  Table 138 of 8224:  (0x2e000100+0x02002600)
  Table 139 of 8224:  (0xfff7ffc0+0x0011000c)
  Table 140 of 8224:  (0xae85c185+0xc985cd85)
  Table 141 of 8224: υ݅ (0xf785f985+0xfb860286)
  Table 142 of 8224: �
� (0x4d865086+0x54865a86)
  Table 143 of 8224: \�^� (0x79867b86+0x8a869586)
  Table 144 of 8224: ���� (0xb686c486+0xc686c986)
  Table 145 of 8224: ˆ͆ (0xde86e486+0xed86f886)
  Table 146 of 8224: �� (0x09870d87+0x18871c87)
  Table 147 of 8224: )�4� (0x3f874987+0x4b874e87)
  Table 148 of 8224: U�W� (0x63876687+0x6a877487)
  Table 149 of 8224: v�x� (0x8d879f87+0xa287b387)
  Table 150 of 8224: ��ć (0xe087ef87+0xf287f787)
  Table 151 of 8224: ���� (0x0d881588+0x22883188)
  Table 152 of 8224: ;�@� (0x52885788+0x59885b88)
  Table 153 of 8224: ]�a� (0x6b887088+0x77887d88)
  Table 154 of 8224: ���� (0x92889688+0x9988a288)
  Table 155 of 8224: ���� (0xb788bf88+0xc188cf88)
  Table 156 of 8224: Ԉ܈ (0xe888f288+0xf888fc89)
  Table 157 of 8224: �� (0x10891289+0x00010000)
  Table 158 of 8224:  (0x00030060+0x47444546)
  Table 159 of 8224:  (0x0001002a+0x47284f53)
  Table 160 of 8224: Z�?� (0x00000070+0x47535542)
  Table 161 of 8224: �\�� (0xfa3ff7f7+0x4f532f32)
  Table 162 of 8224: w�{ (0xff011cd0+0x636d6170)
[�� (0x0000053c+0x67617370)
  Table 164 of 8224:  (0x0200000c+0x676c7966)
  Table 165 of 8224: o�� (0x0041046c+0x68746164)
  Table 166 of 8224: )�} (0x00000036+0x68686561)
sz (0x00000024+0x686d7478)
  Table 168 of 8224: 5��Q (0x0000002c+0x6c6f6361)
  Table 169 of 8224: �� (0x002b0018+0x6d617870)
  Table 170 of 8224:  (0x00000020+0x6e616d65)
  Table 171 of 8224: #�� (0x4f5f6957+0x756f49e4)
  Table 172 of 8224: ���� (0xa6c379e3+0x98cb0138)
  Table 173 of 8224: ���� (0xff880001+0x000a0064)
  Table 174 of 8224:  (0x00b80002+0x6d6c6d31)
  Table 175 of 8224:  (0x00000001+0x5b414c20)
  Table 176 of 8224:  (0x00000003+0x00040006)
  Table 177 of 8224:  (0x00030004+0x00060004)
  Table 178 of 8224:  (0x00020005+0x00070008)
  Table 179 of 8224: m�ym (0x6f737461+0x6c746d6c)
  Table 180 of 8224: ym (0x00000000+0x00032400)
  Table 181 of 8224:  (0x00000000+0x22000200)
  Table 182 of 8224:  (0x04000400+0x03000500)
  Table 183 of 8224: 
 (0x01000900+0x00000100)
  Table 184 of 8224:  (0x026dec6d+0x32000e6d)
  Table 185 of 8224: lym (0x000000ff+0xff000100)
  Table 186 of 8224:  (0x08000000+0x01000000)
  Table 187 of 8224:  (0x01000800+0x01001200)
  Table 188 of 8224:  (0x1c002600+0x2c000201)
  Table 189 of 8224:  (0x020002ff+0x6400e806)
[..]
  Table 8220 of 8224:  (0x00000000+0x00000000)
  Table 8221 of 8224:  (0x00000000+0x00000000)
  Table 8222 of 8224:  (0x00000000+0x00000000)
  Table 8223 of 8224:  (0x00000000+0x00000000)
```

Every table that had 0 zero was causing `_hb_face_builder_reference_table` to create font header, which is not a table even but reversed value for creating font header, making OOM for the font.

**Comment by behdad** [comment]
We shod replace 0 tags with something else (0xFfffffff) when enumerating tables then?

**Comment by behdad** [comment]
The merged patch doesn't look right fix to me.

O
Maybe 0x7fffffff since 0xffffffff doesn't for in enum.

**Comment by ebraminio** [comment]
Hmm, hard to imagine 0 tags are useful.

> The merged patch doesn't look right fix to me.

I think we shouldn't let subset tables that have alloc be triggered more than one, specially with empty tables tags, keeping amount of memory we are going to allocate not that different from input font.

**Comment by behdad** [comment]
Do two things:
1. when enumerating font table tags, replace 0 tags with 0x7fffffff.
2. in face-builder, maybe silently drop all tables with tags that are not ascii printable.

**Comment by ebraminio** [comment]
> when enumerating font table tags, replace 0 tags with 0x7fffffff.

And turning back the value to zero while building the font?

**Comment by behdad** [comment]
> > when enumerating font table tags, replace 0 tags with 0x7fffffff.
> 
> And turning back the value to zero while building the font?

No.

Or better, don't touch enumerate.  Just reject 0 tags in `hb_face_reference_table` and return nil blob in that case.  That should be all we really need to do.  Yeah, let's do just that.

**Comment by ebraminio** [comment]
Done on #1947.

Can we go for processing a table only once however? In that case we won't need to care about zero also, for example a case like this,

```
0 gsub (0x00b80002+0x6d6c6d31)
1 gsub (0x00000000+0x00000000)
2 gsub (0x00000000+0x00000000)
[..]
8000 gsub (0x00000000+0x00000000)
```

We will do gsub (or some other expensive to subset table) just 8000 times, probably causes timeout and OOM.

**Comment by behdad** [comment]
Shouldn't cause OOM.

I'm fine if you want to add a hb_set_t inside the subsetter to process each tag at most once.

**Pull request merged**
