### PR TITLE
Add Travis based Coverity trigger

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
The caveat, IIUC, is you should push coverity_scan manually as:

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

Is using master is OK with coverity guys? If not I am not sure whether current time to time is better than pushing to that branch.

**Comment by behdad** [comment]
Looks like we are allowed 3 builds a day. How about we were some code for our Travis to push master to coverity_scan branch once a day? Oh, I read we can even set cron jobs on Travis now? Or in confusing with something else?

**Comment by ebraminio** [comment]
Ok, I guess now everything theoretically should work.

**Comment by ebraminio** [comment]
PTAL

**Comment by behdad** [comment]
Thanks! Please go ahead and set this up.

**Comment by ebraminio** [comment]
Lets see how it goes

**Comment by pwithnall** [comment]
Assuming you’re using the old Coverity project for results, rather than the new one (I strongly suggest using the old one, in order to keep your result, triage and statistical history), then everything seems set for you to maintain the Coverity scans for Harfbuzz yourselves. I’ll step back from providing them. :-)

**Pull request merged**
