### PR TITLE
[glyf] Switch to ttf-parser's glyf to path algorithm

### PR DESCRIPTION
**Pull request by ebraminio**
It consumes only one point at a time and doesn't need to know contour size beforehand, can be extended to not allocate when `gvar` not present and it gives the very first point on the contour instead a synthetic one.

@RazrFalcon can you give a permission to use it? Thanks!

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Sure. It's under MIT anyway.

PS: It's kinda funny that you are borrowing some parts from ttf-parser to harfbuzz, while I doing the same [in reverse](https://github.com/RazrFalcon/ttf-parser/blob/0e10e84e69ef25ff7d5a8787102d8f19c1fba57f/src/avar.rs#L60). But in the end, ttf-parser/rustybuzz will have a completely different TrueType/OpenType implementation. Not sure if it was a good decision.

**Comment by ebraminio** [comment]
> PS: It's kinda funny that you are borrowing some parts from ttf-parser to harfbuzz, while I doing the same in reverse. But in the end, ttf-parser/rustybuzz will have a completely different TrueType/OpenType implementation. Not sure if it was a good decision.

That enriches both projects specially from quality standpoint I guess :) I think we are very open to Rust and like it also (I for sure would try to do new project with it anyway and honestly like to get involved in your numerous awesome projects also!). We may also go for a gradual port to Rust eventually using your very codes/crates and experiences (how interestingly you've done that gradual port for example hb_buffer_t port process and have broken the project into crates), and allsorts', but guess that would be in some years given some of our clients such as Chrome/Flutter/etc that have embedded HarfBuzz don't have Rust in their build system yet which can be easily be imagined will happen just in some time and some other size and compatibility converns. In the meanwhile my own attempt will be keeping HarfBuzz as an already in use Linux package updated and add useful features for our current clients to benefit them in short term such as this outline extraction API, subset, hb-style, etc.

So maybe there will be some diverge between harfbuzz/rustybuzz/allsorts in short term but we will try to converge goals and codes of the projects eventually so I believe all the parallel developments that are happening here independently won't be a zero sum game and are bringing new ideas on code quality and implementation on the table.

Thanks!

**Comment by RazrFalcon** [comment]
Thanks! 

In short term, I hope rustybuzz will help with testing, since there are a lot of areas in harfbuzz that are not tested yet. For example, I've noticed that Thai is basically untested. So I plan to write some tests for it, which will benefit both projects.

But don't get me wrong, harfbuzz's extensive and independent test suite is the main reason why rustybuzz was possible in the first place. And as someone who wrote thousands of tests for resvg, I can only image how much work was put into this.

As for allsorts, it's a promising project, but I don't think that it's something I could use, in let's say resvg, in near future.

**Comment by ebraminio** [comment]
> I hope rustybuzz will help with testing, since there are a lot of areas in harfbuzz that are not tested yet.

That sounds fantastic! Let me know when is ready. Thanks! :)

> I've noticed that Thai is basically untested.

Guess was tested with some other approach that is related to https://github.com/harfbuzz/harfbuzz-testing-wikipedia/ but not sure

> As for allsorts, it's a promising project, but I don't think that it's something I could use, in let's say resvg, in near future.

No problem, found their https://github.com/yeslogic/ddl interesting.

**Comment by RazrFalcon** [comment]
>Guess was tested with some other approach

Yes, I meant that there are no Thai related tests right now. I'm sure it works fine.

**Comment by ebraminio** [comment]
> Yes, I meant that there are no Thai related tests right now. I'm sure it works fine.

Oh, meant there are some tests that are ran using the corpus here https://github.com/harfbuzz/harfbuzz-testing-wikipedia but I don't remember much of its details :/ We definitely will need the test you come in the repo however, please keep us updated update those, I will also follow the project also AFAIC. Thanks :)

**Comment by RazrFalcon** [comment]
This is a bit offtopic, but do you how to outline a variable glyph via freetype? I could not find a related API. I've also tried looking into the pango sources, but no luck there.

And, afaiu, harfbuzz support outlining only in master. Is this correct?

Basically, I'm trying to tests variable fonts rendering, but I cannot find a valid reference implementation.

**Comment by ebraminio** [comment]
> This is a bit offtopic, but do you how to outline a variable glyph via freetype? I could not find a related API.

Oh, have a look at https://github.com/behdad/glyphy/blob/master/src/glyphy-freetype.h#L85 also pass these flags https://github.com/behdad/glyphy/blob/73d7fbd96975249c4eb806be94b9889df839335b/demo/demo-font.cc#L126-L133 so it disables hinting

> And, afaiu, harfbuzz support outlining only in master. Is this correct?

Correct. Not hinting ATM which should be addressed later in order to make it something useful for those so called `tricky` fonts, https://github.com/personal-mirrors/freetype2/blob/e5038be70414cf66da6c4d5ce4e30375884c30d8/ChangeLog.23#L3614 (which are not that common one however should address them anyway) https://github.com/personal-mirrors/freetype2/blob/e5038be70414cf66da6c4d5ce4e30375884c30d8/src/truetype/ttobjs.c#L151 this https://crbug.com/1010396 also is worth to look where using hb-subset in hinting removal mode has caused issue. I haven't studied much on how to implement it but it shouldn't be that hard to do, here is a JavaScript implementation for it https://github.com/opentypejs/opentype.js/blob/master/src/hintingtt.js which may can be useful.

> Basically, I'm trying to tests variable fonts rendering, but I cannot find a valid reference implementation.

GDI/Direct2D and CoreText are worth to check also, an example on how to use `GetGlyphOutlineW` https://github.com/tml1024/glyphy/blob/45ad6c9336e78b0fc5aeec4cd7d602333751a93f/demo/demo-font.cc#L194 and this `CTFontCreatePathForGlyph` https://stackoverflow.com/questions/50812934

**Comment by RazrFalcon** [comment]
It seems that `glyphy` doesn't support variable fonts:



And I don't see any variable font related code. I want to test `wght` and other features.

**Comment by ebraminio** [comment]
> It seems that glyphy doesn't support variable fonts:

Interesting has hit that 'A' issue also! https://github.com/behdad/glyphy/pull/34 It is just an experiment, not used anywhere seriously AFAIK.

> And I don't see any variable font related code. I want to test wght and other features.

It doesn't need to be handled by rasterizer despite having some other weight altering strategy AFAIK. And guess glyphy was developed before variation getting popular and added into opentype IIRC. You should configure a FT_Font (or Face?) object for variations and `wght`.

**Comment by RazrFalcon** [comment]
>You should configure a FT_Font (or Face?) object for variations and wght.

Yes, but I don't know how. Right now, the only solution to test variable fonts is via browser, which isn't perfect.

**Comment by RazrFalcon** [comment]
>Interesting that has hit that 'A' issue also!

Yes, I saw that issue. We are using the same font anyway (SourceSansVariable-Roman.otf).

**Comment by ebraminio** [comment]
> Yes, but I don't know how. Right now, the only solution to test variable fonts is via browser, which isn't perfect.

Oh you can use hb-view for starters and pass variation arguments to it, or, the just introduced ot-draw https://github.com/harfbuzz/harfbuzz/blob/master/test/api/test-draw.c#L213

**Comment by RazrFalcon** [comment]
I guess hb is my only option. FreeType definitely supports variable fonts, but the API is absurd. Can't find the right method.

Or maybe I will use pango for now. Something like

```
pango-view --font="Source Sans Variable @wght=700" --text=Test --dpi 600
```

works fine, but I do not understand at what point they are applying variation metrics.

**Comment by ebraminio** [comment]
Guess the best poitner to freetype API is reading harfbuzz freetype
integration, hb-ft :)

**Comment by RazrFalcon** [comment]
The journey is complete: https://www.freetype.org/freetype2/docs/reference/ft2-multiple_masters.html#ft_set_var_design_coordinates

Found here: https://github.com/freedesktop/cairo/blob/52a7c79fd4ff96bb5fac175f0199819b0f8c18fc/src/cairo-ft-font.c#L2314

**Comment by ebraminio** [comment]
Btw HarfBuzz is "loose transliteration of Persian حرف‌باز harf-bāz, meaning “open type”" ([source](https://en.wikipedia.org/wiki/HarfBuzz](https://en.wikipedia.org/wiki/HarfBuzz )) and is pronounced like [this](https://upload.wikimedia.org/wikipedia/commons/1/12/Fa-%D8%AD%D8%B1%D9%81%E2%80%8C%D8%A8%D8%A7%D8%B2.oga), RustyBuzz, means [Truth](https://translate.google.com/#view=home&op=translate&sl=fa&tl=en&text=%D8%B1%D8%A7%D8%B3%D8%AA%DB%8C)-Open/Buzz and is pronounced like [this](https://upload.wikimedia.org/wikipedia/commons/5/5a/Fa-%D8%B1%D8%A7%D8%B3%D8%AA%DB%8C%E2%80%8C%D8%A8%D8%A7%D8%B2.oga), to share what the naming means on the original language :)

**Comment by RazrFalcon** [comment]
Hmm... I always thought that *harf* is *open* and not *buzz*. But I guess it makes sense for a RTL language. *truly open* sounds a bit pretentious, but I guess it fine for an English-speaking audience. 

The original name is closer to a "rusty buzz saw".

**Comment by ebraminio** [comment]
lol, you are right of course, the way that HarfBuzz name is ordered is
probably has more to do with sounding better and of course Persian is not a
RTL language but a language that is mainly written in a RTL script (but Old
Persian was written with LTR script
https://en.wikipedia.org/wiki/Old_Persian ) and its variant that is used in
Tajikestan, Tajiki, is written with Cyrillic.

**Comment by ebraminio** [comment]
Have implemented `hb_ft_font_draw_glyph` and am going to implement it for the rest of platforms, interestingly however our previous way of creating paths was more similar to freetype,

This is hb-ft's result,
```
M1626,1522Q1626,1522 1626,1522Q1626,1522 1626,1522Z

M530,1984Q436,1764 436,1522Q436,1280 530,1059Q625,839 784,680
Q943,521 1163,426Q1384,332 1626,332Q1868,332 2088,426
Q2309,521 2468,680Q2627,839 2721,1059Q2816,1280 2816,1522
Q2816,1764 2721,1984Q2627,2205 2468,2364Q2309,2523 2088,2617
Q1868,2712 1626,2712Q1384,2712 1163,2617Q943,2523 784,2364
Q625,2205 530,1984Z

M305,1164Q256,1342 256,1528Q256,1714 305,1891
Q355,2069 443,2219Q531,2370 657,2496Q784,2623 934,2711
Q1085,2799 1262,2848Q1440,2898 1626,2898Q1812,2898 1989,2848
Q2167,2799 2317,2711Q2468,2623 2594,2496Q2721,2370 2809,2219
Q2897,2069 2946,1891Q2996,1714 2996,1528Q2996,1342 2946,1164
Q2897,987 2809,836Q2721,686 2594,559Q2468,433 2317,345
Q2167,257 1989,207Q1812,158 1626,158Q1440,158 1262,207
Q1085,257 934,345Q784,433 657,559Q531,686 443,836Q355,987 305,1164Z;
```

Here is our current hb-ot's (based on ttf-parser):
```
M1626,1522Q1626,1522 1626,1522Q1626,1522 1626,1522Z

M436,1522Q436,1280 531,1060Q625,839 784,680Q943,521 1164,427Q1384,332 1626,332
Q1868,332 2089,427Q2309,521 2468,680Q2627,839 2722,1060Q2816,1280 2816,1522
Q2816,1764 2722,1985Q2627,2205 2468,2364Q2309,2523 2089,2618Q1868,2712 1626,2712
Q1384,2712 1164,2618Q943,2523 784,2364Q625,2205 531,1985Q436,1764 436,1522Z

M256,1528 Q256,1714 306,1892Q355,2069 443,2220Q531,2370 658,2497Q784,2623 935,2711
Q1085,2799 1263,2849Q1440,2898 1626,2898Q1812,2898 1990,2849Q2167,2799 2318,2711
Q2468,2623 2595,2497Q2721,2370 2809,2220Q2897,2069 2947,1892Q2996,1714 2996,1528
Q2996,1342 2947,1165Q2897,987 2809,837Q2721,686 2595,560Q2468,433 2318,345
Q2167,257 1990,208Q1812,158 1626,158Q1440,158 1263,208Q1085,257 935,345
Q784,433 658,560Q531,686 443,837Q355,987 306,1165Q256,1342 256,1528Z
```

And here is our previous opentype.js based one:
```
M1626,1522Q1626,1522 1626,1522Q1626,1522 1626,1522Z

M531,1985Q436,1764 436,1522Q436,1280 531,1060Q625,839 784,680Q943,521 1164,427
Q1384,332 1626,332Q1868,332 2089,427Q2309,521 2468,680Q2627,839 2722,1060
Q2816,1280 2816,1522Q2816,1764 2722,1985Q2627,2205 2468,2364
Q2309,2523 2089,2618Q1868,2712 1626,2712Q1384,2712 1164,2618
Q943,2523 784,2364Q625,2205 531,1985Z

M306,1165Q256,1342 256,1528 Q256,1714 306,1892Q355,2069 443,2220Q531,2370 658,2497
Q784,2623 935,2711Q1085,2799 1263,2849Q1440,2898 1626,2898
Q1812,2898 1990,2849Q2167,2799 2318,2711Q2468,2623 2595,2497
Q2721,2370 2809,2220Q2897,2069 2947,1892Q2996,1714 2996,1528
Q2996,1342 2947,1165Q2897,987 2809,837Q2721,686 2595,560
Q2468,433 2318,345Q2167,257 1990,208Q1812,158 1626,158
Q1440,158 1263,208Q1085,257 935,345Q784,433 658,560
Q531,686 443,837Q355,987 306,1165Z
```

Visually they have not different but it made me a bit unsure about the change, let's see other platforms results also.

**Comment by RazrFalcon** [comment]
Hmm... I've tested ttf-parser against freetype, but only visually. Will investigate it later.

**Comment by RazrFalcon** [comment]
Here is the difference:



As you can see, the only difference it MoveTo/CloseTo order. I'm not sure if it's important. But I guess I can change ttf-parser to match this behavior.

**Comment by ebraminio** [comment]
I like to test other platforms first here is my directwrite attempt which is currently returning random number, https://gist.github.com/ebraminio/e2d18feea65adaaeff6d6e041b7a3161 and here is my https://gist.github.com/ebraminio/4dd7b90a87edf0ed0624aee23e6b3645 GDI attempt which is more incomplete (hard APIs they've got!) Should test CoreText also

**Comment by ebraminio** [comment]
Which glyph is this btw?

**Comment by RazrFalcon** [comment]
What do you mean?

**Comment by ebraminio** [comment]
What font and glyph you've shown on your comment above? My paths didn't show the artifacts on browser using this tool
```
 data:text/html;charset=utf8,<textarea onkeyup="document.querySelector('svg path').setAttribute('d', value)">M0,1000Q500,1500 1000,1000Z</textarea><br><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000"><g transform="scale(.2, -.2) translate(0, -1500)"><path d="M0,1000Q500,1500 1000,1000Z"></g></svg>
```

**Comment by RazrFalcon** [comment]
I've manually moved the MoveTo segments in Inkscape. The paths themselves are from your comment.

**Comment by ebraminio** [comment]
Have put CoreText result on https://github.com/harfbuzz/harfbuzz/pull/2178#issuecomment-588724213 which aligns better with freetype (and not sure where that 1 unit move is coming from) but it is visually different also,

image

Guess they don't try do these zero alloc anyway as AFAICT from opentype.js which guess was based freetype it needs end point of contour and couldn't consume one point at a time.

https://github.com/harfbuzz/harfbuzz/pull/2183/commits/1b74c776c44a38cc348096f7f633e17dca14131b#diff-1da6023328b90ffee82045cdd357d482R913

Have added a `hb_directwrite_font_draw_glyph` there also but isn't function for some reason, should add one GDI based one also later.

**Comment by RazrFalcon** [comment]
I've written `glyf` parsing a long time ago, so I don't really remember how it works. But I will try to tweak it so it will match the freetype results.

**Comment by ebraminio** [comment]
Thanks, guess it worths some double checking but of course they and paths
I've extracted can have errors.

**Pull request merged**
