### PR TITLE
[face] Destroy blob if face closure can not be created

### PR DESCRIPTION
**Pull request by sebras**
This fixes issue #2489.

### CODE REVIEW

**Comment by sebras** [comment]
I see that the coverage test fails to reach 67% coverage for the new allocation error handling code. Looking through `test/api`, `test/fuzzing`, etc. I can't find that there is an existing framework for testing such error handling code. I'll need some advice of how to add that in this case, should that be a requirement for this PR to be merged.

**Comment by behdad** [comment]
We don't currently have a "fork & fail malloc" or similar test setup. Ideas about how to set up are welcome.

**Comment by behdad** [comment]
Oh. This is wrong slightly wrong. The "sanitize" call might return a different blob. Just assign that to blob first before the creation of the closure.

**Comment by sebras** [comment]
> We don't currently have a "fork & fail malloc" or similar 
> test setup. Ideas about how to set up are welcome.

Doing something similar to MuPDF, i.e. `-Dhb_malloc_impl=my_malloc` and have `my_malloc()` have a triggerable allocation limit may be possible. I think it would require HarfBuzz to be linked statically into the test binary, and the execution time might be prohibitive. I can try to play around with something in a separate pull request to illustrate my idea. Doing this will take some time (I'm not well versed in HarfBuzz's test framework).

**Comment by behdad** [comment]
> have a triggerable allocation limit

Yeah but that doesn't do a thorough job...
fork-and-fail shouldn't be that bad. In cairo we used to do these with LD_PRELOAD, so didn't require a differently compiled harfbuzz either.

**Comment by sebras** [comment]
Thanks for guiding me to make a better fix, and merging it. :)

> Yeah but that doesn't do a thorough job...

I'm not sure I understand what it would miss?
If you have an example it would be helpful.

> fork-and-fail shouldn't be that bad.
> In cairo we used to do these with LD_PRELOAD, so 
> didn't require a differently compiled harfbuzz either.

Looking in cairos git I found [sphinx](https://cgit.freedesktop.org/cairo/tree/util/cairo-sphinx/sphinx.c#n2) -- is this what you referred to?

The test parent there transfers information over a socket to each child, for an allocator test that ought to be the desired point at which the child's allocator should return `NULL`. By replacing `malloc()` for via `LD_PRELOAD` it would not just test HarfBuzz, but also all libraries it and HarfBuzz itself depend on. I can't make up my mind whether that's a stability benefit or a problem (not HarfBuzz's code).

**Comment by behdad** [comment]
> I'm not sure I understand what it would miss?

Yeah same as what you said about the runtime.

> The test parent there transfers information over a socket to each child, for an allocator test that ought to be the desired point at which the child's allocator should return `NULL`. By replacing `malloc()` for via `LD_PRELOAD` it would not just test HarfBuzz, but also all libraries it and HarfBuzz itself depend on. I can't make up my mind whether that's a stability benefit or a problem (not HarfBuzz's code).

Right. In cairo we started hitting issues in FreeType. And you don't want to hit issues in FreeType...

> Looking in cairos git I found [sphinx](https://cgit.freedesktop.org/cairo/tree/util/cairo-sphinx/sphinx.c#n2) -- is this what you referred to?

Sorry I don't remember. Has been quite a while. No doesn't look like that. Nevermind. My be my bad memory. I don't want to send you goose-chasing but check DBus as well. I'm fairly sure that one had.

**Comment by behdad** [comment]
at any rate the logic is simple: on every malloc you fork and fail in the child...

**Pull request merged**
