### PR TITLE
Turn more of simple dagger chains to foreach

### PR DESCRIPTION
**Pull request by ebraminio**
Less noise, as was agreed before and applied 385741d565de also

### CODE REVIEW

**Comment by behdad** [comment]
Would help if you say what problem you face when doing that.

**Comment by ebraminio** [comment]
> Would help if you say what problem you face when doing that.

Uploaded it as a PR just to show CI failures, https://travis-ci.org/harfbuzz/harfbuzz/jobs/587812319#L2265 for example

**Comment by behdad** [comment]
> Uploaded it as a PR just to show CI failures, https://travis-ci.org/harfbuzz/harfbuzz/jobs/587812319#L2265 for example

Right.  Not helpful...

Feel free to assign to @qxliu76 maybe.

**Comment by ebraminio** [comment]
> Right. Not helpful...

I was thinking like 0u/0 thing something else, and, not with the specific code here has went wrong that something with apparently same semantic is resulting to weird difference.

**Pull request merged**
