### PR TITLE
Add HB_NO_SETLOCALE

### PR DESCRIPTION
**Pull request by ebraminio**
#1764 related

### CODE REVIEW

**Comment by behdad** [comment]
I like this.

Wider question: should we switch to using HAVE_SETLOCALE, etc, for these?  That would change the default for people who build custom.

Alternatively, maybe have these HB_NO_SETLOCALE etc as is, and have a HB_NO_LIBC that disables all libc functions?

**Comment by ebraminio** [comment]
> Alternatively, maybe have these HB_NO_SETLOCALE etc as is, and have a HB_NO_LIBC that disables all libc functions?

An HB_LEAN_LIBC that defines HB_NO_SETLOCALE and HB_USE_INTERNAL_QSORT and defining some round fallback, and maybe enabling our baked mem* str* of libc, sad that malloc and friends involve more magic, I wish we had a zero allocation mode like https://www.sqlite.org/malloc.html#memsys5

**Comment by behdad** [comment]
> An HB_LEAN_LIBC that defines HB_NO_SETLOCALE and HB_USE_INTERNAL_QSORT and defining some round fallback, and maybe enabling our baked mem* str* of libc, sad that malloc and friends involve more magic, I wish we had a zero allocation mode like https://www.sqlite.org/malloc.html#memsys5

`HB_NO_QSORT` please. :)

Also, no internal memory allocator.  Imagine if every library did that...

**Comment by ebraminio** [comment]
> HB_NO_QSORT please. :)

Already added in https://github.com/harfbuzz/harfbuzz/commit/9407ef8d4bb96346b1f8b07757d79d3f8cc61cf7 :/ This `HB_NO_QSORT` feel to be not that nice naming but I am OK with rename

**Comment by behdad** [comment]
> Already added in [9407ef8](https://github.com/harfbuzz/harfbuzz/commit/9407ef8d4bb96346b1f8b07757d79d3f8cc61cf7) :/ This `HB_NO_QSORT` feel to be not that nice naming but I am OK with rename

Fine, let's keep your naming.  I just don't like adding all kinds of arbitrary macros.

**Pull request merged**
