### PR TITLE
[appveyor] Limit make to three jobs

### PR DESCRIPTION
**Pull request by khaledhosny**
https://github.com/harfbuzz/harfbuzz/pull/1309#issuecomment-432778270

### CODE REVIEW

**Comment by khaledhosny** [comment]
All look fine now, except Cygwin; it takes 10 minutes to just install the packages! I’m OK with disabling it again, one failure every ~5 years is an acceptable rate IMO.

**Comment by behdad** [comment]
Agreed.

**Comment by khaledhosny** [comment]
Next would to move MingW builds to another service and limit AppVeyor to MSVC builds.

**Comment by ebraminio** [comment]
> Next would to move MingW builds to another service and limit AppVeyor to MSVC builds.

I've enabled Azure Pipeline CI again https://dev.azure.com/harfbuzz/harfbuzz/_build?definitionId=3 and invited you to it.
It config is here https://github.com/harfbuzz/harfbuzz/blob/master/azure-pipelines.yml
But it is only compiling vcpkg itself https://dev.azure.com/harfbuzz/harfbuzz/_build/results?buildId=9&view=logs
Its script is in PowerShell, don't if possible to run cmd instead and I have no preference on whether msys2 builds should be moved there or msvc or both, so apply any one of them if you like and had time for.

Thanks

**Comment by khaledhosny** [comment]
I was thinking of cross-compiling with MingW from Linux, that should be faster I guess.

**Comment by ebraminio** [comment]
Hmmm, Fedora packages can be used there I guess, CircleCI can provide that. I will try finish Azure one for MSVC

**Comment by ebraminio** [comment]
> Fedora packages can be used there I guess

Or a custom Docker image, reducing compile time of third party libraries.

**Pull request merged**
