### PR TITLE
[subset-serialize] release discarded objects

### PR DESCRIPTION
**Pull request by qxliu76**

### CODE REVIEW

**Comment by behdad** [comment]
Thanks. How did you discover this?

**Comment by qxliu76** [comment]
> Thanks. How did you discover this?

It's sad story, I was still struggling with porting the serializer into Rust. So I looked into the code and see if I could change the logic a bit(just need to change the order of a few lines of code to resolve the rust compiler error)

**Comment by behdad** [comment]
Bot failure seems unrelated? @khaledhosny

**Review by garretrieger — APPROVED** [review]

**Comment by khaledhosny** [comment]
> Bot failure seems unrelated? @khaledhosny

Fixed in https://github.com/harfbuzz/harfbuzz/pull/4933

**Pull request merged**
