### PR TITLE
[instancer] add a warning for CFF partial instancing

### PR DESCRIPTION
**Pull request by qxliu76**
For #4700

### CODE REVIEW

**Comment by behdad** [comment]
CFF1 has no variations so no need there.

**Comment by qxliu76** [comment]
Updated the PR. Thanks!

**Comment by ebraminio** [comment]
Maybe subsetter can raise some similar warning for unsupported AAT layout tables subsetting, or maybe it could suggest adding using keep gid flag, sorry if that's already considered.

**Comment by behdad** [comment]
Feel free to add l send PR.

**Comment by khaledhosny** [comment]
This change is breaking the WASM port. It seems to cause filesystem support to be needed (it wasn’t before), and this seem to be problematic for the way we build hb-subset to WASM. I also think it is not appropriate for the library to printf stuff like this. I think this should be moved to the command line utility of possible, or be behind some ifdef that I can turn off when building to WASM.

**Comment by behdad** [comment]
I agree library shouldn't print. Let's remove it. hb-subset cmdline can do if it wants.

**Pull request merged**
