### PR TITLE
Use CreateFileW explicitly and pass wchar_t to it

### LINKED ISSUE #1086: error: no matching function for call to 'CreateFileW'
Chrome Windows build has this issue:
https://logs.chromium.org/v/?s=chromium%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8942035310612106064%2F%2B%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout

cc @drott

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1086 and I guess #1046 also (hopefully)

### CODE REVIEW

**Comment by dscorbett** [comment]
`mbstowcs` uses the current locale. Could that unpredictability make this fix ever do the wrong thing?

**Comment by ebraminio** [comment]
> `mbstowcs` uses the current locale. Could that unpredictability make this fix ever do the wrong thing?

:/

We have one here already https://github.com/harfbuzz/harfbuzz/blob/159ddb872986f121818e816d2ea75d271075ba1f/util/options.cc#L152

Worst case I'd guess would be fallback to `fopen` reader.

**Comment by dscorbett** [comment]
On Windows, `_mbstowcs_l` is the locale-sensitive version. I am not sure this is a real problem: [the locale is always initially set to `"C"`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale#generic-text-routine-mappings), but maybe a client of HarfBuzz can override that and mess something up. You should confirm with someone who knows C++ locales.

**Comment by ebraminio** [comment]
Ok. Lets merge this and think about our two instance of `mbstowcs` on the project (the other is on hb-directwrite, we is also added by me). At least we have `fopen` around as a fallback for this cases, for now.

**Comment by ebraminio** [comment]
For the reference, I asked my C/C++ expert friend and he was undecided about what to do here but I try to fix this and will apply any solution you will find @dscorbett also. Thank you

**Pull request merged**
