### PR TITLE
Appropriate fix for msys2 bot fail on gen-def.py

### PR DESCRIPTION
**Pull request by ebraminio**
Reverts the hack happened here #885 with @anthrotype help. Thanks!

### CODE REVIEW

**Comment by anthrotype** [comment]
I hope that doesn't break other stuff :)
it also changes the encoding of the stdout/stderr streams, so if we print anything to the console and the latter uses some weird ANSI codepage.. 

Maybe you should only set that env variable when calling glib-mkenums

**Comment by anthrotype** [comment]
https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/1.0.1076/job/ici5gkiglm79meo6#L556

still getting UnicodeDecodeError.

Are we sure that cmake's execute_process that calls the glib-mkenums script is reading the PYTHONIOENCODING variable properly?

maybe you could try doing `SET(ENV{PYTHONIOENCODING} "UTF-8")` just before `EXECUTE_PROCESS(...)`? 
https://cmake.org/pipermail/cmake/2011-August/045665.html

**Comment by ebraminio** [comment]
msys2 bot which is failing uses autotools, Behdad's territory, I fear to touch it and then get blamed :D

**Comment by behdad** [comment]
Um. No blame. :) I'll check.

**Comment by ebraminio** [comment]
Hehehe, done, lets see.

**Comment by anthrotype** [comment]
> msys2 bot which is failing uses autotools

oh I see. I presume it would give the same error if one attempted to run glib-mkenums under cmake on msys2, if that env variable isn't set.

**Comment by ebraminio** [comment]
@anthrotype does it look good now? If so I think this can be merged now.

**Pull request merged**
