### PR TITLE
[GPOS.PairPos] Adjust unsafe-to-break for non-zero ValueFormat2

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3824

### CODE REVIEW

**Comment by behdad** [comment]
@caolanm can you test this?

**Comment by behdad** [comment]
There's a further adjustment that can be done here. Currently we skip second glyph even if the kerning did not apply any adjustment whatsoever. We can instead, in a rather non-conforming reading of the spec, only skip the second glyph if there was actually any adjustment. @jfkthame

**Comment by jfkthame** [comment]
> There's a further adjustment that can be done here. Currently we skip second glyph even if the kerning did not apply any adjustment whatsoever. We can instead, in a rather non-conforming reading of the spec, only skip the second glyph if there was actually any adjustment. @jfkthame

Do the other engines do that? While I think it'd make sense to modify the spec (and everyone's behavior) -- thanks for opening that issue -- if we can't get agreement there, then I think having consistent behavior across engines takes priority over a non-conforming improvement in an obscure edge case.

**Review by jfkthame — APPROVED** [review]

**Comment by behdad** [comment]
> Do the other engines do that?

Seems to me like CoreText does that, but not Uniscribe.

**Comment by caolanm** [comment]
@behdad yes this solves our problem, thanks

**Pull request merged**
