### PR TITLE
Insert a dotted circle within <U+0B85, U+0BC2>

### PR DESCRIPTION
**Pull request by dscorbett**
This adds the Tamil vowel constraint mentioned in MicrosoftDocs/typography-issues#205. I removed HBIndicVowelConstraints.txt because the file is now available at https://github.com/microsoft/font-tools/blob/master/USE/IndicShapingInvalidCluster.txt.

### CODE REVIEW

**Comment by behdad** [comment]
Oh those data files from MS are amazing!

Can we copy the one we use into our git tree, so it's tracked?  Unlike Unicode, there's no easy versioning for those.

**Comment by behdad** [comment]
Just import the one you are using now.  We process the rest in https://github.com/harfbuzz/harfbuzz/issues/1012

**Comment by dscorbett** [comment]
Where should I put [the license file](https://github.com/microsoft/font-tools/blob/d6514ee7f25cf04cd0ce6427dc9626cab191db1e/LICENSE)?

**Comment by behdad** [comment]
> Where should I put [the license file](https://github.com/microsoft/font-tools/blob/d6514ee7f25cf04cd0ce6427dc9626cab191db1e/LICENSE)?

It's very similar to ours.  Maybe create the directory src/ms-use and put the data files and their license there.

**Comment by behdad** [comment]
Data files like those are not quite covered by copyright per se also.

**Comment by dscorbett** [comment]
Better safe than sorry! I added the file.

**Comment by behdad** [comment]
Thanks!

**Comment by behdad** [comment]
Probably should add a README to that directory pointing to the source repo.  No need to include hash of the commit we have pulled down though.

Also need to make `make dist` distribute them. :)

**Comment by dscorbett** [comment]
I’ll do that for #1012.

**Pull request merged**
