### PR TITLE
Implement hmtx/vmtx metrics read from hvar/vvar

### PR DESCRIPTION
**Pull request by ebraminio**
First step toward #1594 per @blueshade7 and needed for #1999 (so going to be tested there)

### CODE REVIEW

**Comment by behdad** [comment]
I'm also not sure what the purpose of `hmtxvmtx_accelerator_base_t` is.

**Comment by blueshade7** [comment]
If my memory serves me right, it had something to do with a cyclic reference between `glyf::accelerator_t` and `hmtxvmtx::accelerator_t`. Since both can’t own each other, I ended up with the former owning the latter, the latter temporary using the former through hb-ot-hmtx-table.cc. To simplify this code, I created this base class.

**Comment by ebraminio** [comment]
No problem I turned it into a private API afterward.

**Comment by behdad** [comment]
> No problem I turned it into a private API afterward.

In that case, maybe we can remove the base class?  Or use templates to break down the recursive use.

**Comment by ebraminio** [comment]
I tried to keep the original change untouched and had removed that base
class and some other refactoring after it on the same PR or next. There is
a recursive use between hmtx and glyf headers which if it could be resolved
I didn't need that private API also but guess that is fine.

**Pull request merged**
