### PR TITLE
Use a unified and internal bsearch

### PR DESCRIPTION
**Pull request by ebraminio**
Unintentionally but part of #593, I didn't know its essence at the time! :)

### CODE REVIEW

**Comment by behdad** [comment]
I'm fine w doing this but also for both bsearch and qsort, if HB_OPTIMIZE_SIZE is enabled we should introduce overload without extra args to call the C lib one.  Curious what the size diff will be.

**Comment by behdad** [comment]
Maybe combine the two?

**Comment by ebraminio** [comment]
> I'm fine w doing this but also for both bsearch and qsort, if HB_OPTIMIZE_SIZE is enabled we should introduce overload without extra args to call the C lib one. Curious what the size diff will be.

Actually this brought to my attention as I wanted reduce harfbuzzjs size, so I see that as unnecessary complication as I have to do that only when there is no extra variable.

> Maybe combine the two?

Which two?

**Comment by ebraminio** [comment]
> Actually this brought to my attention as I wanted reduce harfbuzzjs size,

And doing so undermines my wish on writing some slim libc to reduce harfbuzzjs wasm size even more.

**Comment by ebraminio** [comment]
Merged this as it didn't have size implication and works correctly apparently, now #1739 remains which I don't why fails even

**Pull request merged**
