### PR TITLE
COLRv1: use ClipBoxes for extents

### PR DESCRIPTION
**Pull request by matthiasclasen**
This is a first step; ultimatively, we should compute the extents is ClipBoxes are missing.

### CODE REVIEW

**Comment by matthiasclasen** [comment]
This also needs support for the variable clipbox format.

**Comment by behdad** [comment]
Would be nice to add a small test.

**Comment by behdad** [comment]
This now just need variations to be hooked up. I'll see what I can do.

**Comment by matthiasclasen** [comment]
I tried with your variation hookup, but I can't observe any clipbox changes, despite dragging the right axis sliders, and seeing get_extents() getting called in response - your code always adds 0s. Printing out the coords shows that my slider changes are applied.

**Comment by matthiasclasen** [comment]
This works in quick testing (at least I can confirm that variations are applied to these extents now).

**Comment by behdad** [comment]
Let's open new issue for v0

**Pull request merged**
