### PR TITLE
bug fix in optimizing coverage table format

### PR DESCRIPTION
**Pull request by qxliu76**

### CODE REVIEW

**Comment by behdad** [comment]
Please explain what the bug is first.  What you observing.  Why fix is correct.

I understand it now.  But could easily have a description: "We are comparing number of shorts, NOT number of bytes."

**Comment by qxliu76** [comment]
sorry, will do provide details next time!

> Please explain what the bug is first. What you observing. Why fix is correct.
> 
> I understand it now. But could easily have a description: "We are comparing number of shorts, NOT number of bytes."

sorry, will do provide details next time!

**Comment by behdad** [comment]
No worries.  Thanks.

**Comment by drott** [comment]
> Please explain what the bug is first. What you observing. Why fix is correct.
> 
> I understand it now. But could easily have a description: "We are comparing number of shorts, NOT number of bytes."

I'd still be curious to hear a bit more about what this fixes. When is the affected code used - in subsetting or command line serialisation?

**Comment by behdad** [comment]
> > 
> 
> I'd still be curious to hear a bit more about what this fixes. When is the affected code used - in subsetting or command line serialisation?

Whenever we build a Coverage table from scratch.  Currently only done by the subsetter.

**Pull request merged**
