### PR TITLE
[ci/appveyor] Adopt with Meson

### LINKED ISSUE #2244: [meson] Enable CI bots on Windows
cmake bots on Windows https://github.com/harfbuzz/harfbuzz/blob/master/appveyor.yml needs to be replaced with meson

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #2244 

Temporarily setting wraps clone depth to 1, will remove before merge

### CODE REVIEW

**Comment by ebraminio** [comment]
https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/31466127/job/anow9kaer8tjh23o#L39

apparently needs 0.53 but we have 0.52 in appveyor so closing for now

**Comment by khaledhosny** [comment]
You can install latest meson with `pip`.

**Comment by ebraminio** [comment]
> You can install latest meson with pip.

Thanks :) Am trying to make it work

**Comment by ebraminio** [comment]
@tp-m @khaledhosny thanks for your help here :)

**Pull request merged**
