### PR TITLE
Move gh-pages docs to harfbuzz.github.io

### LINKED ISSUE #624: Move documentations to harfbuzz/harfbuzz.github.io
previous location of live documentation behdad.github.io/harfbuzz is broken now and harfbuzz.github.io/harfbuzz can be used instead. I think it is better to to go further and separate gh-pages into harfbuzz/harfbuzz.github.io to remove need of /harfbuzz on urls. Recently added config.yml also can be removed as no dummy circleci config would be needed for a separate repo. Token of that repo should be set on travisci environment variables.

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #624

Adds harfbuzz.github.io link to README also.

### CODE REVIEW

**Comment by ebraminio** [comment]
@khaledhosny or @behdad, can you review this and put GH_TOKEN of https://github.com/harfbuzz/harfbuzz.github.io on https://travis-ci.org/harfbuzz/harfbuzz/settings then merge this? Thanks

**Comment by ebraminio** [comment]
After that gh-pages branch of this repository can be deleted https://stackoverflow.com/a/2003515

**Comment by ebraminio** [comment]
Also circleci seems need a reset somewhere on https://circleci.com/gh/harfbuzz/harfbuzz/edit I guess

**Comment by ebraminio** [comment]
HarfBuzz.png was updated before this PR but this changes it again to exact version Khaled sent.

Also added a CNAME that later can be used for routing harfbuzz.org to http://behdad.github.io

**Comment by behdad** [comment]
> @khaledhosny or @behdad, can you review this and put GH_TOKEN of https://github.com/harfbuzz/harfbuzz.github.io on https://travis-ci.org/harfbuzz/harfbuzz/settings then merge this? Thanks

Turns out GH_TOKEN's are user-based, so they same token would have worked.  I created a new one and set again.

**Comment by behdad** [comment]
Also, you could have done as well.

**Comment by ebraminio** [comment]
Great, now you can delete it from `git push -d <remote_name> <branch_name>`

And I think it would be nice if harfbuzz.org is routed to the address, that can be done with "Custom domain" on https://github.com/harfbuzz/harfbuzz.github.io/settings it seems then https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

**Comment by khaledhosny** [comment]
I deleted the `gh-pages` branch.

**Comment by behdad** [comment]
@behnam can redirect harfbuzz.org; but we first need to decide on the landing page.  Should it redirect to harfbuzz.github.io?  That is the documentation right now.  We should move the content from harfbuzz.org to somewhere. I don't mind if it's the front page of the documentation.

**Comment by khaledhosny** [comment]
We probably can move any relevant bits from current harfbuzz.org to the documentation front page, or have a static front page and move the documentation to a docs sub directory.

**Comment by behdad** [comment]
Using docs infrastructure sounds good.  We should be able to add the static page right in there.

**Comment by ebraminio** [comment]
BUMP at harfbuzz.org

**Comment by behdad** [comment]
What do you want me to do? I'm happy to give you all the access you need. @behnam can redirect domain.

Any volunteers to upload old releases?! Maybe we can all chip in; there's like 80 of them.

**Comment by behnam** [comment]
Do we want the domain redirected, or hosted on GitHub? I prefer redirect, so we can release the domain at some point in the future.

About current <https://harfbuzz.github.io/>, looks like it's very focused on the C API. I was under the assumption that it's going to be more of a landing page, have more space for language bindings, and the C-only matters, like the API docs would stay in the main repo, so they can be updated in sync.

**Comment by behdad** [comment]
Putting the entire website into the docs/ directory sounds like a win for everyone. I agree with eventually retiring domain.

**Pull request merged**
