### PR TITLE
Better hash

### PR DESCRIPTION
**Pull request by behdad**
Towards fixing https://github.com/harfbuzz/harfbuzz/issues/4227

### CODE REVIEW

**Review by garretrieger — APPROVED** [review]

**Comment by behdad** [comment]
Number of probes by length:

Before:
```
      4 61
      4 62
      8 60
     20 59
     24 58
     34 57
     46 56
     62 55
     64 54
     78 53
     92 52
    102 51
    116 50
    138 49
    156 48
    190 47
    218 46
    252 45
    294 44
    344 43
    386 42
    444 41
    494 40
    586 39
    704 38
    758 37
    788 36
    868 35
    976 34
   1060 33
   1137 32
   1200 31
   1297 30
   1394 29
   1479 28
   1533 27
   1586 26
   1639 25
   1693 24
   1761 23
   1836 22
   1918 21
   2044 20
   2138 19
   2245 18
   2356 17
   2483 16
   2614 15
   2750 14
   3295 13
   3688 12
   4578 11
   5065 10
   6435 9
   7220 8
   9518 7
  11356 6
  14195 5
  18165 4
  22666 3
  31777 2
1125146 1
```

After:
```
      2 19
      2 20
      2 21
      2 22
      2 23
      4 18
      6 17
     23 16
     32 15
     44 14
     54 13
     83 12
    144 11
    226 10
    357 9
    867 8
   1219 7
   2152 6
   4022 5
   8224 4
  19188 3
  55419 2
1119223 1
```

Other than the length reduction, the number of long probes drops down rather quickly.

**Comment by behdad** [comment]
While these improve the worst-case performance of the hashmap, I do see 6% slowdown on this benchmark case though. So I'm undecided. :(

**Comment by behdad** [comment]
With fasthash. Not that different. Perhaps because saturated by int hash.
```
      2 19
      2 20
      6 17
      6 18
     12 16
     17 15
     31 14
     51 13
     90 12
    134 11
    206 10
    329 9
    614 8
    947 7
   1690 6
   3008 5
   7432 4
  18397 3
  53821 2
1119453 1
```

**Comment by behdad** [comment]
With the latest change the performance seems to be a net gain slightly. New numbers:
```
      2 19
      2 20
      8 18
     22 17
     28 16
     34 15
     50 14
     73 13
    127 12
    183 11
    272 10
    419 9
    755 8
   1132 7
   1731 6
   3131 5
   5574 4
   9357 3
  36606 2
1116277 1
```

**Comment by behdad** [comment]
Humm. Just for `hb_bytes_t` I get the following:
```
      2 19
      2 20
      6 17
      6 18
     12 16
     16 15
     30 14
     50 13
     89 12
    133 11
    198 10
    315 9
    588 8
    895 7
   1413 6
   2592 5
   4748 4
   7981 3
  14511 2
  37638 1
```

**Comment by behdad** [comment]
> Humm. Just for `hb_bytes_t` I get the following:

This is still surprisingly long, given the small number of operations.

**Comment by behdad** [comment]
> > Humm. Just for `hb_bytes_t` I get the following:
> 
> This is still surprisingly long, given the small number of operations.

Or not. Seems correct assumptotically.

**Comment by behdad** [comment]
I ended up disabling the integer hash function since it has negative performance effect.

**Comment by behdad** [comment]
> I ended up disabling the integer hash function since it has negative performance effect.

1. The subset benchmarks show a slowdown of ~5% according to @garretrieger 

2. The `benchmark-map` diff is a lot more interesting:
```
Comparing before to after
Benchmark                              Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------
BM_MapInsert/16                     +0.9944         +0.9949            27            53            26            53
BM_MapInsert/64                     +0.5324         +0.5328            34            53            34            53
BM_MapInsert/512                    +0.2256         +0.2259            43            53            43            53
BM_MapInsert/4096                   -0.5521         -0.5520           118            53           118            53
BM_MapInsert/32768                  -0.7956         -0.7956           259            53           258            53
BM_MapInsert/262144                 -0.8242         -0.8243           316            55           315            55
BM_MapInsert/1048576                -0.8764         -0.8764           647            80           645            80
BM_MapLookup/16                     +0.0975         +0.0975             3             3             3             3
BM_MapLookup/64                     +0.1666         +0.1663             3             4             3             4
BM_MapLookup/512                    +0.2666         +0.2686             3             4             3             4
BM_MapLookup/4096                   +1.7377         +1.7374             3             9             3             9
BM_MapLookup/32768                  +0.3670         +0.3671             7             9             7             9
BM_MapLookup/262144                 +0.9840         +0.9854             7            14             7            14
BM_MapLookup/1048576                +1.1744         +1.1729             7            15             7            15
OVERALL_GEOMEAN                     -0.1102         -0.1101             0             0             0             0
```
Let's look at the before/after separately:

Before:
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BM_MapInsert/16            26.6 ns         26.5 ns     33423282
BM_MapInsert/64            34.4 ns         34.3 ns     28868762
BM_MapInsert/512           43.0 ns         42.8 ns     20134729
BM_MapInsert/4096           118 ns          118 ns      5452951
BM_MapInsert/32768          259 ns          258 ns      4198637
BM_MapInsert/262144         316 ns          315 ns      1773352
BM_MapInsert/1048576        647 ns          645 ns      1408436
BM_MapLookup/16            3.10 ns         3.09 ns    226235463
BM_MapLookup/64            3.19 ns         3.18 ns    220335005
BM_MapLookup/512           3.33 ns         3.32 ns    206349995
BM_MapLookup/4096          3.47 ns         3.46 ns    198738054
BM_MapLookup/32768         6.86 ns         6.84 ns    103205802
BM_MapLookup/262144        6.90 ns         6.87 ns    102260716
BM_MapLookup/1048576       6.85 ns         6.84 ns    102540738
```
After:
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BM_MapInsert/16            53.0 ns         52.8 ns     10000000
BM_MapInsert/64            52.7 ns         52.5 ns     10000000
BM_MapInsert/512           52.7 ns         52.5 ns     10000000
BM_MapInsert/4096          52.8 ns         52.7 ns     10000000
BM_MapInsert/32768         53.0 ns         52.8 ns     10000000
BM_MapInsert/262144        55.5 ns         55.3 ns     10000000
BM_MapInsert/1048576       80.0 ns         79.8 ns     11023447
BM_MapLookup/16            3.40 ns         3.39 ns    206079247
BM_MapLookup/64            3.72 ns         3.71 ns    189178653
BM_MapLookup/512           4.22 ns         4.21 ns    166123694
BM_MapLookup/4096          9.50 ns         9.48 ns     73851363
BM_MapLookup/32768         9.38 ns         9.36 ns     74429576
BM_MapLookup/262144        13.7 ns         13.6 ns     51010831
BM_MapLookup/1048576       14.9 ns         14.9 ns     47329274
```

We observe two things, one good and one bad:

== The good

The MapInsert performance used to get worse as the initial number of items in the map increased:
```
BM_MapInsert/16            26.6 ns         26.5 ns     33423282
BM_MapInsert/64            34.4 ns         34.3 ns     28868762
BM_MapInsert/512           43.0 ns         42.8 ns     20134729
BM_MapInsert/4096           118 ns          118 ns      5452951
BM_MapInsert/32768          259 ns          258 ns      4198637
BM_MapInsert/262144         316 ns          315 ns      1773352
BM_MapInsert/1048576        647 ns          645 ns      1408436
```
That's because of hitting long chains (square-root?) with the poor integer hash function. With the improved (Knuth's multiplicative) hash function, the time is even across the benchmark:
```
BM_MapInsert/16            53.0 ns         52.8 ns     10000000
BM_MapInsert/64            52.7 ns         52.5 ns     10000000
BM_MapInsert/512           52.7 ns         52.5 ns     10000000
BM_MapInsert/4096          52.8 ns         52.7 ns     10000000
BM_MapInsert/32768         53.0 ns         52.8 ns     10000000
BM_MapInsert/262144        55.5 ns         55.3 ns     10000000
BM_MapInsert/1048576       80.0 ns         79.8 ns     11023447
```

== The bad

The MapLookup performance used to be this:
```
BM_MapLookup/16            3.10 ns         3.09 ns    226235463
BM_MapLookup/64            3.19 ns         3.18 ns    220335005
BM_MapLookup/512           3.33 ns         3.32 ns    206349995
BM_MapLookup/4096          3.47 ns         3.46 ns    198738054
BM_MapLookup/32768         6.86 ns         6.84 ns    103205802
BM_MapLookup/262144        6.90 ns         6.87 ns    102260716
BM_MapLookup/1048576       6.85 ns         6.84 ns    102540738
```

Now it's this:
```
BM_MapLookup/16            3.40 ns         3.39 ns    206079247
BM_MapLookup/64            3.72 ns         3.71 ns    189178653
BM_MapLookup/512           4.22 ns         4.21 ns    166123694
BM_MapLookup/4096          9.50 ns         9.48 ns     73851363
BM_MapLookup/32768         9.38 ns         9.36 ns     74429576
BM_MapLookup/262144        13.7 ns         13.6 ns     51010831
BM_MapLookup/1048576       14.9 ns         14.9 ns     47329274
```

So, instead of, roughly, 3,3,3,3,7,7,7; we now get 4,4,4,9,9,14,14.  After lots of studying (with `perf stat` and `cachegrind`) I'm convinced that this is just memory cache latency of the more random read access with the better hash function. The test case does map lookups of successive integers, which is very advantageous to the identity hash function.

So. Mystery solved. I think we might want to use the better hash function after all, to avoid long chains.

**Pull request merged**
