### PR TITLE
[use] Avoid O(n^2) in the machine

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3502

I couldn't generate the ragel-generated machine file. Can someone do that and update please? cc @khaledhosny

### CODE REVIEW

**Comment by behdad** [comment]
@dscorbett review?

**Comment by dscorbett** [comment]
It does seem to work, but I’m not versed in Ragel enough to be certain this does not introduce an obscure bug. If Ragel is setting a variable to 0, there must be a reason for it, but I don’t know whether this machine uses any feature that relies on it.

**Comment by behdad** [comment]
It sets it for hygiene but has no way to query for it currently.

**Comment by behdad** [comment]
I explicitly deleted `operator bool` now, to ensure the code does not try to check for nullptr... 

Please regenerate the .hh file. Thanks.

**Comment by dscorbett** [comment]
To regenerate, I’m just rebuilding with `-Dragel_subproject=true`. Does that not work for you?

**Comment by behdad** [comment]
> It does seem to work, but I’m not versed in Ragel enough to be certain this does not introduce an obscure bug. If Ragel is setting a variable to 0, there must be a reason for it, but I don’t know whether this machine uses any feature that relies on it.

`ts` and `te` record the start and end of the last found match. Then it clears them when it starts looking for the next match.

We can make the machine record null via a boolean. But then that boolean will never be used.

**Comment by behdad** [comment]
> But then that boolean will never be used.

Unless we use it in the `==` implementation. But since the machine has been working so far, that would be extra overhead...

**Comment by dscorbett** [comment]
Should the copy constructor copy `o.is_null`?

**Comment by behdad** [comment]
This is weird. The `hb-ot-font`'s `get_glyph_path` is not called at all for this particular glyph. I'm suspecting a cairo bug :(.

**Comment by dscorbett** [comment]
I built and tested `main` with this PR’s test file and it passed. Can you show that there was a problem and that this fixes it?

**Comment by behdad** [comment]
> Can you show that there was a problem and that this fixes it?

Running `test/fuzzing/hb-shape-fuzzer` on the font file that this commit adds was taking tens of seconds before this commit...

**Comment by behdad** [comment]
> I built and tested `main` with this PR’s test file and it passed.

It passes, just takes too long, which would timeout the fuzzers.

**Comment by behdad** [comment]
before:
```
$ time test/fuzzing/hb-shape-fuzzer ~/Downloads/clusterfuzz-testcase-hb-shape-fuzzer-5446125635633152 
/home/behdad/Downloads/clusterfuzz-testcase-hb-shape-fuzzer-5446125635633152 (655 bytes)

real	1m5.016s
user	1m4.852s
sys	0m0.003s
```

after:
```
$ time test/fuzzing/hb-shape-fuzzer ~/Downloads/clusterfuzz-testcase-hb-shape-fuzzer-5446125635633152 
/home/behdad/Downloads/clusterfuzz-testcase-hb-shape-fuzzer-5446125635633152 (655 bytes)

real	0m0.045s
user	0m0.042s
sys	0m0.002s
```

**Comment by dscorbett** [comment]
It would be good if fuzzed speed tests could have individual timeouts, so that without this change to the machine this test would fail the build, but I guess that is not necessary as part of this PR.

**Review by dscorbett — APPROVED** [review]

**Comment by behdad** [comment]
We used to have that I thought....

**Comment by behdad** [comment]
> We used to have that I thought....

Maybe we have for shape tests, but not the test/fuzzing....

**Pull request merged**
