### PR TITLE
CFF negative offset

### PR DESCRIPTION
**Pull request by behdad**
This is a little bit brittle as I don't know if I got all the offsets or not (quite possibly not). But otherwise seems to work.

### CODE REVIEW

**Comment by behdad** [comment]
Ugh. A lot of tests fail...

**Comment by behdad** [comment]
@garretrieger Can you help look int the subset-cff fails?

**Comment by garretrieger** [comment]
> @garretrieger Can you help look int the subset-cff fails?

Sure, no problem.

**Comment by behdad** [comment]
Ah I think I found it.

**Comment by behdad** [comment]
Tests pass now. @khaledhosny this is ready for review. Thanks.

**Pull request merged**
