### PR TITLE
[subset] fixed GPOS device table sanitize & serialize

### PR DESCRIPTION
**Pull request by blueshade7**
Fixed the following sub-issues found in #2060 :

1. Offsets to device tables in PairPosFormat1 were based on the lookup table, not on the PairSet table (see `PairSet::sanitize_closure_t` in `PairPosFormat1::sanitize`).
2. Device tables were not serialized when their offsets were listed in value records in SinglePosFormat1, SinglePosFormat2, PairPosFormat1, or PairPosFormat2.

Since variation data in the GPOS table are stored in a variant of a device table, above issues were preventing a GPOS table with variation data in a variable font to be subsetted correctly.

### CODE REVIEW

**Comment by garretrieger** [comment]
Looks good to me as well. Though would also like to see tests. If you don't mind waiting for us to get the lookup subsetting PR's merged, those will unblock you on adding tests.

**Comment by blueshade7** [comment]
@garretrieger You mean PR 2042? Yes I can wait for it and then add test.

**Comment by garretrieger** [comment]
Yeah, that's the one.

**Comment by blueshade7** [comment]
Actually, variation store for GPOS are stored in GDEF, currently dropped. For GPOS to function properly with VF, GDEF table needs to serialize variation store. If we are to subset it, outer/inner indices in device tables in GPOS need to be remapped. More work needed for a test to output the correct result.

**Comment by garretrieger** [comment]
Ah good point, I was hoping to start work on implementing GDEF subsetting in the near future.

**Comment by blueshade7** [comment]
In order to subset varStore in GDEF, outer/inner indices need collected from GPOS, JSTF, and GDEF itself. At least, PairPosFormat1 fix in this PR needs merged first. A sort of chicken-egg problem.
Shall we just merge this without adding a test?

**Comment by garretrieger** [comment]
I'm fine with merging this now if tests will be added in a later PR. FYI, we just got all of the script/lookup/feature subsetting PR's merged now.

**Pull request merged**
