### PR TITLE
Enable TRAK applying and add a test

### PR DESCRIPTION
**Pull request by ebraminio**
It doesn't look good however.

image

And the tests fail due to
```
Actual:   error: Safe-to-break test failed.
[0=0@502,0+1102|0=1@502,0+1102|0=2@502,0+1102|0=3@502,0+1102|0=4@502,0+1102]
Expected: [0=0@501,0+1101|0=1@501,0+1101|0=2@501,0+1101|0=3@501,0+1101|0=4@501,0+1101]
```
Which I need help here.

See also https://github.com/unicode-org/text-rendering-tests/issues/46

### CODE REVIEW

**Comment by ebraminio** [comment]
An interesting issue also noticed by asan,

```
=================================================================
==34387==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffedbe59ab4 at pc 0x7fd31621fb44 bp 0x7ffedbe59a40 sp 0x7ffedbe59a38
READ of size 1 at 0x7ffedbe59ab4 thread T0
    #0 0x7fd31621fb43 in BEInt<int, 4>::operator int() const /root/project/src/./hb-machinery.hh:691
    #1 0x7fd31621fb43 in ?? ??:0
    #2 0x7fd31621f51f in AAT::TrackData::get_tracking(void const*, float) const /root/project/src/./hb-aat-layout-trak-table.hh:117
    #3 0x7fd31621f51f in ?? ??:0
    #4 0x7fd3162104af in AAT::trak::apply(AAT::hb_aat_apply_context_t*) const /root/project/src/./hb-aat-layout-trak-table.hh:171
    #5 0x7fd3162104af in ?? ??:0
    #6 0x7fd31620f75e in hb_aat_layout_position(hb_font_t*, hb_buffer_t*) /root/project/src/hb-aat-layout.cc:101
    #7 0x7fd31620f75e in ?? ??:0
    #8 0x7fd31628cec4 in hb_ot_shape_internal(hb_ot_shape_context_t*) /root/project/src/hb-ot-shape.cc:918
    #9 0x7fd31628cec4 in ?? ??:0
    #10 0x7fd31628ca3c in _hb_ot_shape /root/project/src/hb-ot-shape.cc:945
    #11 0x7fd31628ca3c in ?? ??:0
    #12 0x7fd31620b25a in hb_shape_plan_execute /root/project/src/./hb-shaper-list.hh:43
    #13 0x7fd31620b25a in ?? ??:0
    #14 0x7fd31620a198 in hb_shape_full /root/project/src/hb-shape.cc:141
    #15 0x7fd31620a198 in ?? ??:0
    #16 0x52eeec in shape_options_t::shape(hb_font_t*, hb_buffer_t*, char const**) /root/project/util/./options.hh:238
    #17 0x52eeec in ?? ??:0
    #18 0x52e27f in shape_consumer_t<output_buffer_t>::consume_line(char const*, unsigned int, char const*, char const*) /root/project/util/./shape-consumer.hh:67
    #19 0x52e27f in ?? ??:0
    #20 0x52cef6 in main_font_text_t<shape_consumer_t<output_buffer_t>, 2147483647, 0>::main(int, char**) /root/project/util/./main-font-text.hh:81
    #21 0x52cef6 in ?? ??:0
    #22 0x52c7b5 in main /root/project/util/hb-shape.cc:164
    #23 0x52c7b5 in ?? ??:0
    #24 0x7fd3158bb09a in __libc_start_main ??:?
    #25 0x7fd3158bb09a in ?? ??:0
    #26 0x41d8c9 in _start ??:?
    #27 0x41d8c9 in ?? ??:0

Address 0x7ffedbe59ab4 is located in stack of thread T0 at offset 84 in frame
    #0 0x7fd31621f31f in AAT::TrackData::get_tracking(void const*, float) const /root/project/src/./hb-aat-layout-trak-table.hh:90
    #1 0x7fd31621f31f in ?? ??:0

  This frame has 3 object(s):
    [32, 40) 'base.addr'
    [64, 68) 'fixed_size' (line 97)
    [80, 84) 'size_table' (line 115) <== Memory access at offset 84 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
```

**Comment by behdad** [comment]
I was going to suggest we attack kerx first.  I'll take a look at this later.

**Comment by behdad** [comment]
Looking at the get_tracking function makes my eyes hurt. :)  I don't have immediate suggestions though.

Comments like this are redundant:
```
    // We couldn't match any, exit 
    if (!trackTableEntry) return 0.; 
```

**Comment by ebraminio** [comment]
Hehe, the whole thing is a port from Mozilla's `trak` handling, that particular line https://dxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxMacPlatformFontList.mm#628

Which part worries you more, the `trak` implementation, 'Safe-to-break test failed', or that 'asan' issue? I will try to improve them.

**Comment by behdad** [comment]
I have this working locally.

**Pull request closed without merging**
