### PR TITLE
[ci] Compile CoreText on CircleCI

### LINKED ISSUE #1131: CircleCI Mac bots do not --with-coretext

### PR DESCRIPTION
**Pull request by ebraminio**
Tries to fix #1131

### CODE REVIEW

**Comment by khaledhosny** [comment]
Any idea why it can’t find Core Text?

**Comment by ebraminio** [comment]
Not really but I didn't put lots of effort on it. Best part is you can connect the its shell for debugging :)

**Comment by khaledhosny** [comment]
Interesting! I did just that and I found it is choking on system headers. Dropping the `CC` and `CXX` env variables makes things work, looks like that is a too outdated compiler to build with system header. I guess we need a new job that uses the default compiler on the system.

**Comment by ebraminio** [comment]
> I guess we need a new job that uses the default compiler on the system.

What I was thinking also. Worth to have also so we can wrote hb-coretext specific and test CoreText AAT shaper without a macOS also.

**Comment by khaledhosny** [comment]
But then again we have Travis osx that do `--with-coretext`, so I guess #1131 just can’t be fixed due to limitations in these compilers.

**Comment by khaledhosny** [comment]
`macos-notest-apple-gcc-i686-4.2` can’t build with Core Text either, same issue. System headers seem to be mixing C and ObjC and these old compilers chock on that.
```
configure:20418: checking for CTFontRef
configure:20418: /Users/distiller/project/opt/local/bin/i686-apple-darwin15-gcc-apple-4.2.1 -std=gnu99 -c -g -O2  conftest.c >&5
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:53,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from conftest.c:51:
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFDateFormatter.h:53: error: expected ',' or '}' before '__attribute__'
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFDateFormatter.h:80: error: 'introduced' undeclared here (not in a function)
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:11,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from conftest.c:51:
```

**Comment by ebraminio** [comment]
> But then again we have Travis osx that do --with-coretext, so I guess #1131 just can’t be fixed due to limitations in these compilers.

I think the overlapping is OK as this bot will have SSH access also which can be very useful.

**Comment by behdad** [comment]
I'm fine closing, given that Travis tests this already.

**Pull request closed without merging**
