### PR TITLE
Revert "Reordering fails when GDEF table is absent #2140"

### PR DESCRIPTION
**Pull request by ebraminio**
This reverts commit f4cd99f28eefe695b86876736166fd119e22e04e.

As requested in https://github.com/harfbuzz/harfbuzz/issues/2516#issuecomment-670969185

@jfkthame @khaledhosny @simoncozens  can one you confirm this so I can make a release for it afterwards if no one oppose to? (as always will release with a PR so can get feedbacks and if everyone is happy about the release or no comment arises) Thanks!

### CODE REVIEW

**Comment by simoncozens** [comment]
Reverting this will fix #2516 and break #2140. Please see the tests in #2553.

**Comment by ebraminio** [comment]
> Reverting this will fix #2516 and break #2140. Please see the tests in #2553.

Okay makes sense, just wanted to follow https://github.com/harfbuzz/harfbuzz/issues/2516#issuecomment-670969185 so am letting you @jfkthame @khaledhosny @simoncozens to decide about this and am closing this (or will reopen if you decide to). Thanks!

**Comment by simoncozens** [comment]
Wait! It depends how long it's going to take us to fix #2140 (which is a fairly minor bug). #2516 is pretty bad and should be dealt with ASAP. I thought I had a fix in the PR I mentioned, but it needs review. If nobody can review my fix, then I think it's better to do this reversion and get a release out.

**Comment by ebraminio** [comment]
> If nobody can review my fix, then I think it's better to do this reversion and get a release out.

Exactly. So do you agree with the merge of this PR?

**Comment by simoncozens** [comment]
Here's what I suggest:

* Do the reversion
* Make a release to make distros happy
* Bring in *at least* my failing tests from #2553 
* If @behdad can fix, great; if not, bring in my "fix" from #2553 too.

**Comment by ebraminio** [comment]
Ok, will merge this per https://github.com/harfbuzz/harfbuzz/issues/2516#issuecomment-670969185 then will propose a release ask you if things are OK for the release.

**Comment by ebraminio** [comment]
> Bring in at least my failing tests from #2553

I like to have that, can you submit the one that is fixed by this revert as a PR? Thanks

**Comment by behdad** [comment]
@simoncozens let's do a half hour video call to get to the bottom of this. My schedule is fairly open. I'll follow up with you via email.

**Pull request merged**
