### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by ebraminio**
I guess this is the convention we have on harfbuzz.

### CODE REVIEW

**Comment by khaledhosny** [comment]
How can one use this?

**Comment by behdad** [comment]
I'm curious as well.  Does vim respect this? If yes, please let's add one to fonttools as well, so we stop fighting about tab vs spaces.

Also, if it makes code @rsheeter and @garretrieger write adhere to our conventions, then +10000000.

**Comment by ebraminio** [comment]
Oh sorry, I forgot to put more information. It has a builtin support or using a plugin by these http://editorconfig.org/#download software.

**Comment by ebraminio** [comment]
Vim has a plugin for it, https://github.com/editorconfig/editorconfig-vim that depends on what editor they use :)

**Comment by ebraminio** [comment]
Its tab width setting however is not working. At least on VSCode and Atom it has this issue https://github.com/editorconfig/editorconfig-vscode/issues/190

**Comment by jedmao** [comment]
Looks useful. It will probably be 100% useful for most if not all non-Atom editors. Even for Atom editors, at least it defines what the rules are for documentation purposes. The only reason it doesn't work on those editors is because "weird" indentation settings are enforced against and for good reason.

**Comment by behdad** [comment]
I gave it a try (installed vim plugin, checked out this branch); didn't see it immediately change my workflow. LGTM.

**Pull request merged**
