### PR TITLE
[subset] GPOS 5 MarkToLigature subsetting support

### PR DESCRIPTION
**Pull request by qxliu76**

### CODE REVIEW

**Comment by khaledhosny** [comment]
Is anything blocking merging this (apart from the merge conflict)?

**Comment by behdad** [comment]
Looks okay to me.

**Comment by khaledhosny** [comment]
OK, apparently this needs to be adapted to d7c012a08 as well.

**Comment by garretrieger** [comment]
qxliu76 is OOO at the moment so I can take over this fix the merge conflicts, and update it for d7c012a.

**Comment by garretrieger** [comment]
This has been replaced by #2701

**Pull request closed without merging**
