### PR TITLE
Config.h filename configuration

### PR DESCRIPTION
**Pull request by 1bsyl**
Hi,

We want to be able to have several config.h configuration, for various platform.
Maybe we can add HB_CONFIG_H_FILENAME and HB_CONFIG_OVERRIDE_H_FILENAME to allow config filenames customization.

### CODE REVIEW

**Comment by behdad** [comment]
You can create your own `config.h` and `config-override.h` that internally `#include HB_CONFIG_H_FILENAME` etc. Multiarch distros have been doing that for years.

**Comment by behdad** [comment]
That said, I'm open to this.

**Comment by behdad** [comment]
Sure. Send a PR.

**Comment by 1bsyl** [comment]
Goal is to keep several different config.h in our repository
(one for android, linux, mingw probably .. )
to still be able to compile for each platform

**Pull request closed without merging**
