### PR TITLE
[test] Add generated tests for emoji clusters

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes https://github.com/harfbuzz/harfbuzz/issues/3017

Uses AdobeBlank2.ttf from:
  https://github.com/adobe-fonts/adobe-blank-2

instead of a dummy empty font so that everything maps to GID 1 and control code points are kept instead of being dropped because there is
not space glyph (otherwise we’d need to identify control code points somehow when generating the expectations).

### CODE REVIEW

**Comment by behdad** [comment]
Thank you!!!

**Comment by behdad** [comment]
How much slower will it be if we don't chunk?

**Comment by khaledhosny** [comment]
> How much slower will it be if we don't chunk?

About 4 times slower on my machine, but still below 1 second over all.

**Comment by khaledhosny** [comment]
(apparently batch mode makes things pretty fast, the standalone test that from @rsheeter repo took about 30 seconds.

**Comment by behdad** [comment]
> (apparently batch mode makes things pretty fast, the standalone test that from @rsheeter repo took about 30 seconds.)

Yes, I was wondering since we are using batch mode.

If it's still under 1s, I"m inclined to leave it unchunked.

And I'd be happy to speed batch mode up instead.

**Comment by khaledhosny** [comment]
To give exact numbers, it goes from 0.15s to 1.15s (it was 0.8s when I checked earlier), but yeah not worth it and easier to read failure messages should be worth it.

**Comment by behdad** [comment]
> To give exact numbers, it goes from 0.15s to 1.15s (it was 0.8s when I checked earlier), but yeah not worth it and easier to read failure messages should be worth it.

I see. But yeah, do it the proper way and I'll take a stab at optimizing batch mode. I think currently it still reloads the face every time. Just not doing that would help.

**Pull request merged**
