### PR TITLE
Add BASE table

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by behdad** [comment]
Humm. Did you forget to add the main file in the end? This looks, not right.

**Comment by ebraminio** [comment]
Behdad, what is missing here? I could run https://github.com/eroux/harfbuzz-base-demo after some minor struggles.

**Comment by behdad** [comment]
Don't know. The diff doesn't show the main piece of code to me (hb-ot-layout-base-table.hh); and then we need an API.

**Comment by ebraminio** [comment]
Just click on "Load diff" :P

**Comment by ebraminio** [comment]
This look to have a good quality also, how about merging it but marking it somehow for further security review or something like?

**Comment by behdad** [comment]
> Just click on "Load diff" :P

Hah! UI fail...



> This look to have a good quality also, how about merging it but marking it somehow for further security review or something like?

I'll merge and review now.

**Comment by behdad** [comment]
Following up in https://github.com/harfbuzz/harfbuzz/pull/838

**Pull request closed without merging**
