### PR TITLE
Code reorg for HarfBuzz-next

### PR DESCRIPTION
**Pull request by behdad**
Eventually fixes https://github.com/harfbuzz/harfbuzz/issues/3372
Supersedes https://github.com/harfbuzz/harfbuzz/pull/3370

### CODE REVIEW

**Review by garretrieger — APPROVED** [review]

**Comment by behdad** [comment]
Let's go ahead and do more of this.

**Comment by garretrieger** [comment]
> Let's go ahead and do more of this.

Sounds good!

**Comment by behdad** [comment]
Let's continue other tables in separate PRs.

**Comment by xclaesse** [comment]
@behdad FYI, this caused a regression I fixed there: https://github.com/harfbuzz/harfbuzz/pull/3630.

**Pull request merged**
