### PR TITLE
More standard idioms

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by behdad** [comment]
cc @garretrieger

**Comment by behdad** [comment]
@khaledhosny @ebraminio can we make meson be more like autotools, printing out error logs when something fails? I'm out of clues re where to look...

**Comment by behdad** [comment]
The mentioned full logs are too verbose and not helpful.

**Comment by behdad** [comment]
Oh, it's a timeout. Why it shows here only I have no idea. Going to ignore it.

**Comment by khaledhosny** [comment]
This CI job has been randomly timing out for sometime now.

**Review by drott — APPROVED** [review]
PR is a bit large as it addresses several standard idioms at once, but code changes LGTM. Good to see this migration.

**Comment by khaledhosny** [comment]
This is breaking build with `-std=c++2a` (no idea what that is) on the [sanitizers job](https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/2659/workflows/04712040-d3ca-47c8-9548-76258e0e78a3/jobs/162652)

**Comment by behdad** [comment]
> This is breaking build with `-std=c++2a` (no idea what that is) on the [sanitizers job](https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/2659/workflows/04712040-d3ca-47c8-9548-76258e0e78a3/jobs/162652)

Looking into it. Any idea why I didn't see those in my PR? I thought I just saw the one fedora-valgrind failing.

**Comment by behdad** [comment]
Should be fixed.

**Comment by khaledhosny** [comment]
> Any idea why I didn't see those in my PR? I thought I just saw the one fedora-valgrind failing.

The `fedora-valgrind ` was failing earlier, then it fixed itself. The `sanitizers` one was failing for the last six builds and I have no idea why you missed it.

**Comment by behdad** [comment]
Oh. Sorry about that. Thanks.

**Pull request merged**
