### PR TITLE
[subset] In cmap planning, remove a qsort()

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by garretrieger** [comment]
Benchmarked this against the new glyphs benchmarks:

BM_subset_glyphs/subset_mplus1p/10_median                    +0.1113         +0.1119             1             1             1             1
BM_subset_glyphs/subset_mplus1p/64_median                    +0.1036         +0.1042             1             2             1             2
BM_subset_glyphs/subset_mplus1p/512_median                   +0.0622         +0.0625             2             2             2             2
BM_subset_glyphs/subset_mplus1p/4096_median                  -0.0490         -0.0465             7             6             7             6
BM_subset_glyphs/subset_mplus1p/10000_median                 -0.2288         -0.2283            15            11            15            11
BM_subset_glyphs/subset_notocjk/10_median                    +0.1702         +0.1708             6             7             6             7
BM_subset_glyphs/subset_notocjk/64_median                    +0.1635         +0.1637             7             8             7             8
BM_subset_glyphs/subset_notocjk/512_median                   +0.0811         +0.0814            13            14            13            14
BM_subset_glyphs/subset_notocjk/4096_median                  +0.0189         +0.0176            27            27            27            27
BM_subset_glyphs/subset_notocjk/32768_median                 -0.0066         -0.0074            92            91            92            91
BM_subset_glyphs/subset_notocjk/100000_median                -0.0639         -0.0642           156           146           156           146

Overall looks to be slower for small sizes but a decent improvement at larger input sizes.

**Comment by garretrieger** [comment]
> Benchmarked this against the new glyphs benchmarks:
> 
> BM_subset_glyphs/subset_mplus1p/10_median +0.1113 +0.1119 1 1 1 1 BM_subset_glyphs/subset_mplus1p/64_median +0.1036 +0.1042 1 2 1 2 BM_subset_glyphs/subset_mplus1p/512_median +0.0622 +0.0625 2 2 2 2 BM_subset_glyphs/subset_mplus1p/4096_median -0.0490 -0.0465 7 6 7 6 BM_subset_glyphs/subset_mplus1p/10000_median -0.2288 -0.2283 15 11 15 11 BM_subset_glyphs/subset_notocjk/10_median +0.1702 +0.1708 6 7 6 7 BM_subset_glyphs/subset_notocjk/64_median +0.1635 +0.1637 7 8 7 8 BM_subset_glyphs/subset_notocjk/512_median +0.0811 +0.0814 13 14 13 14 BM_subset_glyphs/subset_notocjk/4096_median +0.0189 +0.0176 27 27 27 27 BM_subset_glyphs/subset_notocjk/32768_median -0.0066 -0.0074 92 91 92 91 BM_subset_glyphs/subset_notocjk/100000_median -0.0639 -0.0642 156 146 156 146
> 
> Overall looks to be slower for small sizes but a decent improvement at larger input sizes.

Given this code path is meant primarily for use with large input set sizes, seems like that's a good tradeoff.

**Comment by behdad** [comment]
I agree. 20% speedup on subset of 10,000 codepoints is more meaningful than 10% slowdown on subsetting 10 codepoints.

**Comment by garretrieger** [comment]
> I agree. 20% speedup on subset of 10,000 codepoints is more meaningful than 10% slowdown on subsetting 10 codepoints.

Yeah definitely. This LGTM.

**Pull request merged**
