### PR TITLE
[WIP] Add APIs to get scripts properties

### LINKED ISSUE #1500: API to get justification character of a script, or, an API for querying info about hb_script_t?
As #586 and Ben comment [here](https://github.com/harfbuzz/harfbuzz/issues/1487#issuecomment-447977498), we like to provide primitives needed for justification, and I guess the best place to learn what APIs can we provide is our [hb-directwrite](https://github.com/harfbuzz/harfbuzz/blob/244a8627f7b0ed651d6010c7ee7e54fa8fcca400/src/hb-directwrite.cc#L688-L765) implementation which uses that DirectWrite primitives in-action...

So one bit that I was thinking about, which is a good start point also, and needed either we want to do all of the justification by our own or letting client to handle it, is an API equal to [GetScriptProperties](https://github.com/harfbuzz/harfbuzz/blob/244a8627f7b0ed651d6010c7ee7e54fa8fcca400/src/hb-directwrite.cc#L706-L709). The call provides different things about script by [DWRITE_SCRIPT_PROPERTIES](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite_1/ns-dwrite_1-dwrite_script_properties) which to me its only justificationCharacter field is useful for justification.

I wanted to just add that thing in an API maybe named `hb_script_get_justifciation_character` (not necessarily public and may be hold till we get other needed things anyway) but thought if we are going for having that, one may ask what about its other infos that dwrite call can provide, don't we need those? This is a sample of info it provides,

```
i	isoScriptCode	clusterLookahead	isBlockWriting	isConnectedWriting	isCursiveWriting	isDiscreteWriting	isDistributedWithinCluster	isoScriptNumber	justificationCharacter	reserved	restrictCaretToClusters	usesWordDividers
0	Zzzz	15	0	0	0	0	0	999	32	0	0	0
1	Zyyy	1	0	0	0	1	0	998	32	0	0	1
2	Zinh	15	0	0	0	0	0	994	32	0	1	0
3	Arab	8	0	1	1	0	0	160	1600	0	0	1
4	Armn	1	0	0	0	1	0	230	32	0	0	1
5	Avst	8	0	0	0	1	0	134	32	0	0	1
6	Bali	15	0	0	0	1	0	360	32	0	1	0
(...)
```

What are interesting columns we can have or provide, if any? As said, the interesting part to me was `justificationCharacter`, which is 1600 (Kashida) for `Arab`, `Mand`, `Syrc`, `Mani`, `Phlp`, 5760 for `Ogam`, and 32 (space) for others (which means that script doesn't have a Kashida-like character concept).

As said this may doesn't worth to have an API even, however I like to ask is Kashida of a script can be extract from unicode files directly? Is there any other library more suitable to provide such info?

Maybe better to have something like `hb-justification.h`, instead thinking about hb_script_get_* for this, and provide things like these there, populate it with an algorithm to detect good places for inserting Kashida?

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1500 and #64

### CODE REVIEW

**Comment by ebraminio** [comment]
Sure, how about separating get_justification_character into a separate PR, does that any chance separately?

**Comment by behdad** [comment]
> Sure, how about separating get_justification_character into a separate PR, does that have any chance separately?

Not without wider discussion of how such API is supposed to be used.

**Comment by khaledhosny** [comment]
The `get_justification_character` does not seem that useful as the application really needs to know more about the script to be able to use it. For example, LibreOffice uses kashida justification in Arabic only even though there are other scripts that can have kashida because it does not know where to insert kashida in these scripts.

**Comment by ebraminio** [comment]
It is equivalent to https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-directwrite.cc#L709 LO can add that to Syriac also as harfbuzz-old was doing so https://github.com/harfbuzz/harfbuzz-old/blob/master/src/harfbuzz-arabic.c#L51 we can ask about all these from Microsoft also maybe.

**Comment by khaledhosny** [comment]
I think this really needs a high level design for how this is going to be used before adding any API. All the issues being opened about this really confuses me and I’m a bit lost. Doing proper Arabic justification is still really an open question and a bit of research needs to be don here.

What Microsoft does it not really the best model and it has many known limitations (it does not distinguish between different style of Arabic, kashida is inserted after the text is shaped and no reshaping is done, fonts has zero control over it).

If you really want to work on this, then may be start with sketching the sort of font control that needs to be provided, fix `JSTF` table, and write a demo application that uses the APIs you want to added, so that you can actually test who useful it is.

**Comment by ebraminio** [comment]
Sure, makes sense. You know, I tried to find the most noncontroversial
parts, different point of view obviously :)

**Comment by jfkthame** [comment]
FWIW, I agree with @khaledhosny that a lot of background work is needed here, before thinking about adding API. Just adding something like `get_justification_character` isn't really useful, and reflects an inadequate model of how justification can/should be done.

**Comment by ebraminio** [comment]
OK, now I have the time to defend myself a bit here :)

> I don't want to copy DirectWrite API directly. Definitely not without discussing each point first. 

You said [here](https://github.com/harfbuzz/harfbuzz/issues/1500#issuecomment-4488498480) it can be useful, and I didn't mean to add whole thing straightly otherwise I was adding directly to the repo, so why the complain when reducing this is easier than adding more things...

> I think this really needs a high level design for how this is going to be used before adding any API.

Now that it has taken ten years, I can imagine it can take another ten years :) And no doubt that is not that important thing and that is also why it is not there yet.

> All the issues being opened about this really confuses me and I’m a bit lost.

Each is about different aspect of things, please focus more :P

> Doing proper Arabic justification is still really an open question and a bit of research needs to be don here.

Right. There is also proposal of using font variation for doing flexible Kashida elongation. I more think about something useful for today but well this patch in particular is not related

> What Microsoft does it not really the best model and it has many known limitations 

I wasn't talking about Microsoft API but how they are applying Kashida justification to non-Arabic scripts, something you said you don't know on "because it does not know where to insert kashida in these scripts" and we can ask them.

> it does not distinguish between different style of Arabic

At least it understands when to forget about Kashida, which is something I am discussing in #1503

> kashida is inserted after the text is shaped and no reshaping is done, fonts has zero control over it

Just speculating here, GetJustifiedGlyphs modifies all the things, and uses information generated by GetJustificationOpportunities which uses textString, so couldn't it theoretically reshape also?

> If you really want to work on this, then may be start with sketching the sort of font control that needs to be provided, fix JSTF table.

What is the issue? You said also it is not in that use so I didn't focus it.

> and write a demo application that uses the APIs you want to added, so that you can actually test who useful it is.

Right.

> Just adding something like get_justification_character isn't really useful, 

This PR was not only about that API of course but to defending it, for handling fallback justification anyway in fonts without `JSTF` or `just` (or futuristic plans like [using font variation](https://twitter.com/sahafshar/status/896389627065577472)), I can't imagine a case without need of this bit of information, Kashida justification, if not done while shaping, should be done either before or after the shaping, and both need such thing, so I wonder.

**Comment by ebraminio** [comment]
No interest apparently so let's close and think about it later. Thanks!

**Comment by behdad** [comment]
Yeah we'll add this properly when needed. The current PR doesn't make sense.

**Comment by ebraminio** [comment]
> Yeah we'll add this properly when needed. 

Guess this is most demanded one, https://github.com/flutter/engine/blob/728e473f1a4bce3f4a034474d81cc95b691c6cf0/third_party/txt/src/minikin/Layout.cpp#L398-L406

**Comment by behdad** [comment]
Right. I noted that in https://github.com/harfbuzz/harfbuzz/issues/64

**Pull request closed without merging**
