### PR TITLE
WIP [gobject] Use a identifier-filter

### PR DESCRIPTION
**Pull request by behdad**
Based on filter in
https://bugzilla.gnome.org/show_bug.cgi?id=706898

Doesn't quite work.  We now get hb.buffer.buffer_create()
instead of the old hb.buffer_create().  The filter itself
is also crude; not sure what it should do.

This is as much progress as I made tonight.  To be refined.

### CODE REVIEW

**Comment by khaledhosny** [comment]
`hb-gobject-identfilter.py` file is missing.

**Comment by behdad** [comment]
Added.

**Comment by timofonic** [comment]
@behdad What happened to this? :O

**Comment by behdad** [comment]
Should we abandon this?  I don't know of anyone using our GI API, but kinda leaving it as is sounds better?

**Comment by khaledhosny** [comment]
Closing in favor of #2462.

**Pull request closed without merging**
