### PR TITLE
 [ot-shape] Numeric runs native direction is LTR

### PR DESCRIPTION
**Pull request by khaledhosny**
See inline comments. Slightly modified version of the code from Jonathan Kew on the linked issue.

Fixes https://github.com/harfbuzz/harfbuzz/issues/501.

### CODE REVIEW

**Comment by behdad** [comment]
In the Arabic shaper there's this comment:
```
static void
apply_stch (const hb_ot_shape_plan_t *plan HB_UNUSED,
            hb_buffer_t              *buffer,
            hb_font_t                *font)
{
  if (likely (!(buffer->scratch_flags & HB_BUFFER_SCRATCH_FLAG_ARABIC_HAS_STCH)))
    return;

  /* The Arabic shaper currently always processes in RTL mode, so we should
   * stretch / position the stretched pieces to the left / preceding glyphs. */
```

Does this change break that assumption? If yes, we should either review & fix, or at least check and bail if not RTL.

**Comment by behdad** [comment]
> Does this change break that assumption?

At the least the good news is that there are no Syriac numberals.

**Comment by jfkthame** [comment]
No, but the ASCII digits have Script=Common, so presumably they would be merged with a surrounding Syriac context for the purposes of script-run analysis. (Not sure if this is a potential problem or not...?)

**Comment by khaledhosny** [comment]
It is potentially an issue if Syriac abbreviation mark gets applied to the digits, but this does not happens since HarfBuzz does not allow `HB_UNICODE_GENERAL_CATEGORY_DECIMAL_NUMBER` to be covered by the abbreviation mark.

**Comment by jfkthame** [comment]
Just FTR, I confirmed that this does break an existing testcase we have in Gecko (once we revert the hack from https://bugzilla.mozilla.org/show_bug.cgi?id=1716029, which otherwise "hides" this), where we use bidi-override to force directionality on an example with one of the format controls (see layout/reftests//bugs/1599841-1.html and the corresponding -ref file in the Mozilla tree). However, I'm OK with that; with this change, more things will work in the "natural" way authors would expect, so we'll adapt our (rather artificial/arbitrary) testcase as needed. In particular, it'll be possible to use the footnote marker, year sign, etc in Noto Nastaliq Urdu *without* needing to apply any direction overrides.

**Comment by behdad** [comment]
> In particular, it'll be possible to use the footnote marker, year sign, etc in Noto Nastaliq Urdu _without_ needing to apply any direction overrides.

Right. I think that's a worthwhile change. Thanks for the comment.

**Pull request merged**
