### PR TITLE
[unicode] Fix typo

### PR DESCRIPTION
**Pull request by arHSM**
I believe the `hb-unicode.h` has a typo where `HB_UNICODE_COMBINING_CLASS_CCC133	= 132,` is supposed to be `HB_UNICODE_COMBINING_CLASS_CCC132`

### CODE REVIEW

**Comment by behdad** [comment]
Thanks!

**Comment by dscorbett** [comment]
Should `HB_UNICODE_COMBINING_CLASS_CCC133` exist for backwards compatibility?

**Comment by behdad** [comment]
Thinking more, probably yes.

**Comment by behdad** [comment]
Should I add it with a value of 132 or 133?

**Comment by behdad** [comment]
hb_unicode_combining_class_t is rather unused publicly. It was a mistake to expose it IMO.

**Comment by dscorbett** [comment]
I think it should have the value 133. I would treat this as a combination of a bug fix (`HB_UNICODE_COMBINING_CLASS_CCC133` should always have had the value 133) and a new feature (`HB_UNICODE_COMBINING_CLASS_CCC132` exists).

**Comment by behdad** [comment]
Agreed. I'll add it to `hb-deprecated.h` as a macro.

**Comment by behdad** [comment]
> Agreed. I'll add it to `hb-deprecated.h` as a macro.

Done.

**Comment by dscorbett** [comment]
See [L2/12-286](https://www.unicode.org/L2/L2012/12286-ccc133.pdf) for how this typo appeared in the first place.

**Pull request merged**
