### PR TITLE
[aat] Use set digest to speed up

### PR DESCRIPTION
**Pull request by behdad**
Still not cached in an accelerator, but shows up promising results.

### CODE REVIEW

**Comment by behdad** [comment]
And cached now. I see 25% speedup for en-thelittleprince benchmark, and 8% for en-words.

**Comment by behdad** [comment]
This is with morx only. Kerx is not done yet.

**Comment by behdad** [comment]
> This is with morx only. Kerx is not done yet.

Done for kern / kerx as well.

en-thelittleprince benchmark is 30% faster, en-words is 10% faster with HelveticaNeue.

**Comment by drott** [comment]
@kojiishi [kicked off benchmarks](https://pinpoint-dot-chromeperf.appspot.com/job/1422a2be010000) and initial measurements show an improvement in the Editor-TipTap 10% subtest of speedometer3 (long text shaping: french, CJK and code) and an overall speedometer score 1.2% improvement in Chromium. This is great, thank you! LGTU, happy to see this landed. Not sure if the fuzzer findings are caused by this set of changes or from main.

**Comment by behdad** [comment]
Yeah the CIFuzz breakage is real. I'm looking into it.

**Comment by behdad** [comment]
I think I fixed the fuzzer issue. In that case this is ready to be merged.

**Comment by jfkthame** [comment]
Very nice! Maybe worth a new release sometime soon?

**Comment by behdad** [comment]
> Very nice! Maybe worth a new release sometime soon?

Yes, I just asked @khaledhosny for one.

**Pull request merged**
