### PR TITLE
[CBLC] Fix assert failure

### PR DESCRIPTION
**Pull request by ckitagawa-work**
If there are multiple IndexSubtableRecord and at least one succeeds in serialization before another fails we currently fail to cleanup extra push() calls before returning. This leads to an assert failure downstream when trying to add a link. The fix is to simply discard these push() calls before returning.

### CODE REVIEW

**Comment by ckitagawa-work** [comment]
@garretrieger PTAL Thanks!

**Comment by behdad** [comment]
There might be a better way to do it.  Let me check.  THis is not the kind of cleanup code you should need to write.

**Comment by garretrieger** [comment]
I think you can do this using snapshot()/revert() on the serializer. Start a snapshot before you begin adding the records and then call revert() if you need to bail out.

**Comment by behdad** [comment]
Creating objects for records without popping them is plain wrong.

**Comment by behdad** [comment]
You cannot push each record, then pop each record.  I mean, you can.  But there's no reason you should.

**Comment by behdad** [comment]
Right.  If specific order is need you shouldn't be using the object packer.

You can use Offset::serialize() currently for that.  But I'm going to slightly change that.

**Comment by garretrieger** [comment]
In the meantime should we merge this to fix the fuzzer error?

**Comment by ebraminio** [comment]
I believe we should

**Comment by behdad** [comment]
I'm fine with that.  We just need to clean this as soon as we develop better solution.  THat's is happening at https://github.com/harfbuzz/harfbuzz/issues/2164#issuecomment-617436277

**Pull request merged**
