### PR TITLE
[subset] If repacking fails for GSUB/GPOS retry with extension promotion.

### PR DESCRIPTION
**Pull request by garretrieger**
In rare cases a subsetting operation may have expanded the non-extension space data enough to make it unable to be repacked. So if we encounter a case that does not repack successfully retry the operation with extension promotion recalculation enabled.

We don't do extension promotion by default since it's rarely needed and it will slow down repacking + increase the repacking size when enabled and not needed.

### CODE REVIEW

**Comment by behdad** [comment]
I dislike the option. I think we should just do what's right. I'm fine with promoting all lookups to extension if packing fails...

**Comment by garretrieger** [comment]
> I dislike the option. I think we should just do what's right. I'm fine with promoting all lookups to extension if packing fails...

Alright, in that case I could do something like this: if repacking fails in space 0, then re-run the entire operation but with extension promotion enabled. How does that sound?

The downside is it will approx double repacking times in the rare cases which hit this scenario.

**Comment by behdad** [comment]
Sounds good. Thanks.

**Comment by garretrieger** [comment]
> Sounds good. Thanks.

Ok, I'll rework this.

**Comment by garretrieger** [comment]
> > Sounds good. Thanks.
> 
> Ok, I'll rework this.



> > Sounds good. Thanks.
> 
> Ok, I'll rework this.

Done, please take another look.

**Comment by behdad** [comment]
I don't fully understand but I trust you know what you are doing. :)

**Pull request merged**
