### PR TITLE
[circleci] Couple of fixes

### LINKED ISSUE #1196: clang everything bot
We have -Wno-documentation and -Wno-documentation-unknown-command.  But I'm seeing a lot of those in the log, making the bot useless: https://circleci.com/gh/harfbuzz/harfbuzz/34694

### LINKED ISSUE #1199: [msan] Fix the bot
Now that the bots builds both glib and freetype with the flags we should fix its issues I believe,

```diff
diff --git a/test/api/hb-test.h b/test/api/hb-test.h
index 307845f6..a7785c1c 100644
--- a/test/api/hb-test.h
+++ b/test/api/hb-test.h
@@ -183,7 +183,7 @@ hb_test_add_func (const char *test_path,
   g_test_add_func (normal_path, test_func);
   g_free (normal_path);
 }
-#define hb_test_add(Func) hb_test_add_func (#Func, Func)
+#define hb_test_add(Func) hb_test_add_func (#Func "\0", Func)
```

And replace `g_string_append_c (gs, '?');`s to `g_string_append (gs, "?");` and the complain now is,

```
Uninitialized bytes in __interceptor_strlen at offset 8 inside [0x701000000190, 9)
==29184==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f0df596a1b2 in g_strdup ??:?
    #1 0x7f0df596a1b2 in ?? ??:0
    #2 0x7f0df597f4a3 in g_set_prgname ??:?
    #3 0x7f0df597f4a3 in ?? ??:0
    #4 0x7f0df5957715 in g_option_context_parse ??:?
    #5 0x7f0df5957715 in ?? ??:0
    #6 0x4a497e in option_parser_t::parse(int*, char***) /home/ebrahim/Desktop/harfbuzz/build/util/../../util/options.cc:155
    #7 0x4a497e in ?? ??:0
    #8 0x4a05dc in main_font_text_t<shape_consumer_t<output_buffer_t>, 2147483647, 0>::main(int, char**) /home/ebrahim/Desktop/harfbuzz/build/util/../../util/main-font-text.hh:62
    #9 0x4a05dc in ?? ??:0
    #10 0x4a039e in main /home/ebrahim/Desktop/harfbuzz/build/util/../../util/hb-shape.cc:164
    #11 0x4a039e in ?? ??:0
    #12 0x7f0df46aab96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #13 0x7f0df46aab96 in ?? ??:0
    #14 0x41d459 in _start ??:?
    #15 0x41d459 in ?? ??:0
```

Any hope?

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1196
Fixes #1199

### CODE REVIEW

**Comment by behdad** [comment]
The hb_glib_blob_create fail is really curious.  Definitely need to understand it first.  I don't like these hacks at all. :|

**Comment by khaledhosny** [comment]
https://github.com/auchenberg/volkswagen

**Comment by behdad** [comment]
> The hb_glib_blob_create fail is really curious. Definitely need to understand it first. I don't like these hacks at all. :|

https://github.com/harfbuzz/harfbuzz/issues/1204

**Comment by ebraminio** [comment]
> https://github.com/auchenberg/volkswagen

Considering stars has given to that repo, that project apparently is even more important than hb

> Both of the SKIP* need to be reverted and fixed properly.

#1204

**Comment by khaledhosny** [comment]
C libraries don’t get that many stars on GitHub, JS ones, on the other hand, get them by the thousands :stuck_out_tongue:

**Pull request merged**
