### PR TITLE
Fix glyph class properties (#2516 and #2140)

### PR DESCRIPTION
**Pull request by simoncozens**
Adds tests for these two bugs, and then fixes them. Please note that I am not entirely sure why it works, but tests pass. :-/

### CODE REVIEW

**Comment by ebraminio** [comment]
@khaledhosny @jfkthame can you give your input on this and maybe merge if it looks good? or https://github.com/harfbuzz/harfbuzz/pull/2556#issuecomment-657057044 

@simoncozens feel free to have a look at https://github.com/harfbuzz/harfbuzz/issues/2558#issuecomment-657056861 also.

**Comment by behdad** [comment]
I'm reviewing now.

**Comment by xadxura** [comment]
Any update on when this might be fixed? This seems to have broken Egyptian clustering in shipping versions of Chrome:
image
which used to display correctly as:
image

**Comment by behdad** [comment]
I'll figure it out tomorrow. Sorry about that.

**Comment by yairc2223** [comment]
hello there I am trying to write a vtp file that will later be converted into a ttf file but the lookups with context just don't work on html 
in the other hand it works perfectly on VOLT proofing tool here are the lookups:
`DEF_FEATURE NAME "Mark Positioning" TAG "mark"
 LOOKUP "glyph36321move" LOOKUP "p28270" LOOKUP "g1m" LOOKUP "g2m" LOOKUP "g3m" LOOKUP "g4m"
END_FEATURE
END_LANGSYS
END_SCRIPT
DEF_GROUP "g1"
 ENUM RANGE "glyph3" TO "glyph10000" END_ENUM
END_GROUP
DEF_GROUP "g2"
 ENUM RANGE "glyph10001" TO "glyph20000" END_ENUM
END_GROUP
DEF_GROUP "g3"
 ENUM RANGE "glyph20001" TO "glyph30000" END_ENUM
END_GROUP
DEF_GROUP "g4"
 ENUM RANGE "glyph30001" TO "glyph37813" END_ENUM
END_GROUP
DEF_GROUP "markers"
 ENUM RANGE "glyph37814" TO "glyph37818" END_ENUM
END_GROUP
DEF_GROUP "numbers"
 ENUM RANGE "glyph37819" TO "glyph38318" END_ENUM
END_GROUP
DEF_LOOKUP "glyph36321move" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GLYPH "glyph36321" BY POS ADV -98 DY -249 END_POS
END_ADJUST
END_POSITION
DEF_LOOKUP "p28270" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GLYPH "glyph28270" BY POS ADV -96 DX 250 DY 200 END_POS
END_ADJUST
END_POSITION
DEF_LOOKUP "g1m" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "g1" BY POS DY -200 END_POS
END_ADJUST
END_POSITION
DEF_LOOKUP "g2m" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "g2" BY POS DY -200 END_POS
END_ADJUST
END_POSITION
DEF_LOOKUP "g3m" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "g3" BY POS DY -200 END_POS
END_ADJUST
END_POSITION
DEF_LOOKUP "g4m" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
 RIGHT GROUP "numbers"
 RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "g4" BY POS DY -240 END_POS
END_ADJUST
END_POSITION
CMAP_FORMAT 0 3 4
CMAP_FORMAT 0 4 12
CMAP_FORMAT 1 0 0
CMAP_FORMAT 3 1 4
CMAP_FORMAT 3 10 12 END
`

**Comment by behdad** [comment]
Please file a new issue.

**Comment by yairc2223** [comment]
I am having trouble with the following lookups.
When I use them on Chrome, using a font loaded in ann HTML, they do not work, and show this:


10e99b74-6516-4f71-b97e-865a5d8e6245

But they do work perfectly on VOLT proofing tool:



5bd83470-dc73-4f7c-b9d3-97ff9a59851a

 
If I remove the context group they work great so I am having trouble with making the context work.

Here are a minimal example of lookups:
python
DEF_FEATURE NAME "Mark Positioning" TAG "mark"
LOOKUP "g1m"
END_FEATURE
END_LANGSYS
END_SCRIPT
DEF_GROUP "g1"
ENUM RANGE "glyph3" TO "glyph10000" END_ENUM
END_GROUP
DEF_GROUP "numbers"
ENUM RANGE "glyph37819" TO "glyph38318" END_ENUM
END_GROUP
DEF_LOOKUP "g1m" PROCESS_BASE PROCESS_MARKS ALL DIRECTION LTR
IN_CONTEXT
RIGHT GROUP "numbers"
RIGHT GROUP "numbers"
END_CONTEXT
AS_POSITION
ADJUST_SINGLE GROUP "g1" BY POS DY -200 END_POS
END_ADJUST
END_POSITION
CMAP_FORMAT 0 3 4
CMAP_FORMAT 0 4 12
CMAP_FORMAT 1 0 0
CMAP_FORMAT 3 1 4
CMAP_FORMAT 3 10 12 END

**Pull request closed without merging**
